const {SUPABASE_URL,serverHeaders,cors,json,readBody,getSupabaseUser,requireAdminUser}=require('../lib');

const SHIPROCKET_EMAIL=String(process.env.SHIPROCKET_EMAIL||'').trim();
const SHIPROCKET_PASSWORD=String(process.env.SHIPROCKET_PASSWORD||'').trim();
const SHIPROCKET_PICKUP_LOCATION=String(process.env.SHIPROCKET_PICKUP_LOCATION||'').trim();
const SHIPROCKET_PICKUP_PINCODE=String(process.env.SHIPROCKET_PICKUP_PINCODE||'').trim();
const SHIPROCKET_BASE='https://apiv2.shiprocket.in/v1/external';
let tokenCache={token:'',expiresAt:0};

async function rest(path,options={}){const response=await fetch(SUPABASE_URL+'/rest/v1/'+path,{...options,headers:{...serverHeaders,...(options.headers||{})}});const data=await response.json().catch(()=>null);if(!response.ok){const error=new Error(data?.message||data?.error||'Shipping database request failed');error.status=response.status;throw error}return data}
function apiCredentialsConfigured(){return Boolean(SHIPROCKET_EMAIL&&SHIPROCKET_PASSWORD)}
function configured(){return Boolean(apiCredentialsConfigured()&&SHIPROCKET_PICKUP_LOCATION)}
function serviceabilityConfigured(){return Boolean(configured()&&/^\d{6}$/.test(SHIPROCKET_PICKUP_PINCODE))}
function positive(value,label){const n=Number(value);if(!Number.isFinite(n)||n<=0)throw new Error(label+' must be greater than zero');return Math.round(n*1000)/1000}
function numberOrNull(value){const n=Number(value);return Number.isFinite(n)?n:null}
function safeShipment(row){if(!row)return null;return{order_id:row.order_id,provider:row.provider,direction:row.direction,courier_name:row.courier_name||null,awb_code:row.awb_code||null,status:row.status||'pending',provider_status:row.provider_status||null,tracking_url:row.tracking_url||null,label_url:row.label_url||null,pickup_requested_at:row.pickup_requested_at||null,last_synced_at:row.last_synced_at||null,created_at:row.created_at||null}}
const ORDER_SELECT='id,user_id,display_order_id,status,payment_method,fulfillment_status,customer_name,customer_email,customer_phone,shipping_address,items,total_amount,currency,created_at';
async function getOrder(id){const rows=await rest('orders?id=eq.'+encodeURIComponent(id)+'&select='+ORDER_SELECT+'&limit=1');if(!rows?.[0]){const error=new Error('Order not found');error.status=404;throw error}return rows[0]}
async function getOrderByKey(key){const value=String(key||'').trim();if(!value){const error=new Error('Invalid order reference');error.status=400;throw error}const filter=/^\d+$/.test(value)?'id=eq.'+encodeURIComponent(value):'display_order_id=eq.'+encodeURIComponent(value);const rows=await rest('orders?'+filter+'&select='+ORDER_SELECT+'&limit=1');if(!rows?.[0]){const error=new Error('Order not found');error.status=404;throw error}return rows[0]}
async function getShipment(orderId){const rows=await rest('order_shipments?order_id=eq.'+encodeURIComponent(orderId)+'&direction=eq.forward&select=*&limit=1');return rows?.[0]||null}
async function updateShipment(orderId,patch){const now=new Date().toISOString(),rows=await rest('order_shipments?order_id=eq.'+encodeURIComponent(orderId)+'&direction=eq.forward',{method:'PATCH',headers:{'Content-Type':'application/json','Prefer':'return=representation'},body:JSON.stringify({...patch,updated_at:now})});if(!rows?.[0]){const error=new Error('Shipment record not found');error.status=404;throw error}return rows[0]}
function assertShippable(order){const fulfillment=String(order.fulfillment_status||'ordered').toLowerCase(),method=String(order.payment_method||'').toLowerCase(),status=String(order.status||'').toLowerCase();if(fulfillment!=='packed')throw new Error('Mark the order Packed before creating a courier shipment');if(method==='prepaid'&&status!=='paid')throw new Error('Only paid prepaid orders can be shipped');if(method==='cod'&&!['cod_pending','cod_collected'].includes(status))throw new Error('This COD order is not eligible for shipping');if(!['prepaid','cod'].includes(method))throw new Error('Unsupported payment method')}
async function shiprocketToken(){if(!configured()){const error=new Error('Shiprocket credentials or pickup location are not configured');error.status=503;throw error}if(tokenCache.token&&Date.now()<tokenCache.expiresAt)return tokenCache.token;const response=await fetch(SHIPROCKET_BASE+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:SHIPROCKET_EMAIL,password:SHIPROCKET_PASSWORD})});const data=await response.json().catch(()=>({}));if(!response.ok||!data?.token){const error=new Error(data?.message||'Shiprocket authentication failed');error.status=502;throw error}tokenCache={token:data.token,expiresAt:Date.now()+8*60*60*1000};return data.token}
async function shiprocket(path,options={}){const token=await shiprocketToken();const response=await fetch(SHIPROCKET_BASE+path,{...options,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data?.message||data?.error||'Shiprocket request failed');error.status=502;throw error}return data}
function orderDate(value){const d=value?new Date(value):new Date();const p=n=>String(n).padStart(2,'0');return d.getUTCFullYear()+'-'+p(d.getUTCMonth()+1)+'-'+p(d.getUTCDate())+' '+p(d.getUTCHours())+':'+p(d.getUTCMinutes())}
function cleanPhone(value){return String(value||'').replace(/\D/g,'').slice(-10)}
function payloadFor(order,box){const a=order.shipping_address||{},phone=cleanPhone(a.phone||order.customer_phone),items=Array.isArray(order.items)?order.items:[];if(!items.length)throw new Error('Order has no items to ship');if(!a.address_line1||!a.city||!a.state||!a.postal_code||!phone)throw new Error('Order delivery address is incomplete for courier booking');const orderItems=items.map((item,index)=>({name:String(item.name||'Product').slice(0,190),sku:String(item.sku||('FF-'+order.id+'-'+(index+1))).slice(0,100),units:Number(item.qty||1),selling_price:Math.max(0.01,Math.round((Number(item.line_total||0)||Number(item.unit_price||0)*Number(item.qty||1))/Math.max(1,Number(item.qty||1))*100)/100),discount:0,tax:0,hsn:''}));return{order_id:'FF-'+String(order.display_order_id||order.id).replace(/[^A-Za-z0-9_-]/g,'-'),order_date:orderDate(order.created_at),pickup_location:SHIPROCKET_PICKUP_LOCATION,billing_customer_name:String(a.full_name||order.customer_name||'Customer').slice(0,100),billing_last_name:'',billing_address:String(a.address_line1).slice(0,200),billing_address_2:String(a.address_line2||'').slice(0,200),billing_city:String(a.city).slice(0,100),billing_pincode:String(a.postal_code).trim(),billing_state:String(a.state).slice(0,100),billing_country:String(a.country||'India').slice(0,100),billing_email:String(order.customer_email||'').slice(0,150),billing_phone:phone,shipping_is_billing:true,order_items:orderItems,payment_method:String(order.payment_method).toLowerCase()==='cod'?'COD':'Prepaid',sub_total:Math.max(0.01,Math.round(Number(order.total_amount||0)*100)/100),length:box.length,breadth:box.breadth,height:box.height,weight:box.weight}}
async function checkServiceability(orderId,body){if(!serviceabilityConfigured()){const error=new Error('Shiprocket serviceability needs credentials, pickup location and SHIPROCKET_PICKUP_PINCODE');error.status=503;throw error}const order=await getOrder(orderId);assertShippable(order);const a=order.shipping_address||{},delivery=String(a.postal_code||'').trim();if(!/^\d{6}$/.test(delivery))throw new Error('Order delivery pincode is invalid for courier serviceability');const weight=positive(body.weight_kg,'Package weight'),q=new URLSearchParams({pickup_postcode:SHIPROCKET_PICKUP_PINCODE,delivery_postcode:delivery,cod:String(String(order.payment_method).toLowerCase()==='cod'?1:0),weight:String(weight),is_new_hyperlocal:'0'});for(const [key,input] of [['length',body.length_cm],['breadth',body.breadth_cm],['height',body.height_cm]]){if(input!=null&&String(input)!=='')q.set(key,String(positive(input,'Package '+key)))}q.set('declared_value',String(Math.max(0,Number(order.total_amount||0))));const data=await shiprocket('/courier/serviceability/?'+q.toString(),{method:'GET'}),payload=data?.data||{},recommended=payload.recommended_courier_company_id??payload.shiprocket_recommended_courier_id??null,list=Array.isArray(payload.available_courier_companies)?payload.available_courier_companies:[];const couriers=list.slice(0,20).map(c=>({courier_id:c.courier_company_id==null?null:String(c.courier_company_id),courier_name:c.courier_name||null,rate:numberOrNull(c.rate)??numberOrNull(c.freight_charge)??numberOrNull(c.cost),estimated_delivery_days:c.estimated_delivery_days==null?null:String(c.estimated_delivery_days),etd:c.etd==null?null:String(c.etd),rating:numberOrNull(c.rating)??numberOrNull(c.delivery_performance),mode:c.is_surface===true?'Surface':c.mode==null?null:String(c.mode),recommended:String(c.courier_company_id)===String(recommended)}));return{recommended_courier_id:recommended==null?null:String(recommended),couriers}}
async function createShipment(orderId,body){if(!configured()){const error=new Error('Shiprocket is not active yet. Configure server credentials and pickup location first.');error.status=503;throw error}const order=await getOrder(orderId);assertShippable(order);const existing=await getShipment(orderId);if(existing?.provider_shipment_id||existing?.provider_order_id)return{created:false,idempotent:true,shipment:safeShipment(existing)};const box={weight:positive(body.weight_kg,'Package weight'),length:positive(body.length_cm,'Package length'),breadth:positive(body.breadth_cm,'Package breadth'),height:positive(body.height_cm,'Package height')};const data=await shiprocket('/orders/create/adhoc',{method:'POST',body:JSON.stringify(payloadFor(order,box))});const providerOrderId=data?.order_id??data?.data?.order_id??null,providerShipmentId=data?.shipment_id??data?.data?.shipment_id??null;if(!providerOrderId&&!providerShipmentId){const error=new Error('Shiprocket did not return an order or shipment ID');error.status=502;throw error}const now=new Date().toISOString(),record={order_id:order.id,provider:'shiprocket',direction:'forward',provider_order_id:providerOrderId==null?null:String(providerOrderId),provider_shipment_id:providerShipmentId==null?null:String(providerShipmentId),awb_code:data?.awb_code?String(data.awb_code):null,courier_id:data?.courier_company_id?String(data.courier_company_id):null,courier_name:data?.courier_name?String(data.courier_name):null,status:'created',provider_status:data?.status?String(data.status):'created',tracking_url:data?.tracking_url?String(data.tracking_url):null,label_url:null,package_weight_kg:box.weight,package_length_cm:box.length,package_breadth_cm:box.breadth,package_height_cm:box.height,last_synced_at:now,updated_at:now};const rows=await rest('order_shipments?on_conflict=order_id,direction',{method:'POST',headers:{'Content-Type':'application/json','Prefer':'resolution=merge-duplicates,return=representation'},body:JSON.stringify(record)});return{created:true,idempotent:false,shipment:safeShipment(rows?.[0]||record),provider_response:{order_id:record.provider_order_id,shipment_id:record.provider_shipment_id}}}
async function assignAwb(orderId,body){const shipment=await getShipment(orderId);if(!shipment?.provider_shipment_id)throw new Error('Create the Shiprocket shipment before assigning an AWB');if(shipment.awb_code)return{assigned:true,idempotent:true,shipment:safeShipment(shipment)};const courier=String(body.courier_id||'').trim(),payload={shipment_id:/^\d+$/.test(String(shipment.provider_shipment_id))?Number(shipment.provider_shipment_id):shipment.provider_shipment_id};if(courier){if(!/^\d+$/.test(courier))throw new Error('Courier ID must be numeric');payload.courier_id=Number(courier)}const data=await shiprocket('/courier/assign/awb',{method:'POST',body:JSON.stringify(payload)}),provider=data?.response?.data||data?.data||{},awb=provider.awb_code??data?.awb_code??null;if(!awb){const pending=Boolean(data?.success)||String(data?.message||'').toLowerCase().includes('processing');if(!pending){const error=new Error(data?.message||'Shiprocket did not assign an AWB');error.status=502;throw error}const row=await updateShipment(orderId,{courier_id:courier||shipment.courier_id||null,status:'awb_pending',provider_status:'AWB assignment requested',last_synced_at:new Date().toISOString()});return{assigned:false,pending:true,idempotent:false,shipment:safeShipment(row)}}const row=await updateShipment(orderId,{awb_code:String(awb),courier_id:provider.courier_company_id==null?(courier||shipment.courier_id||null):String(provider.courier_company_id),courier_name:provider.courier_name?String(provider.courier_name):shipment.courier_name||null,status:'awb_assigned',provider_status:'AWB Assigned',last_synced_at:new Date().toISOString()});return{assigned:true,pending:false,idempotent:false,shipment:safeShipment(row)}}
async function requestPickup(orderId){const shipment=await getShipment(orderId);if(!shipment?.provider_shipment_id)throw new Error('Create the Shiprocket shipment before requesting pickup');if(!shipment.awb_code)throw new Error('Assign an AWB before requesting pickup');if(shipment.pickup_requested_at)return{requested:true,idempotent:true,shipment:safeShipment(shipment)};const shipmentId=/^\d+$/.test(String(shipment.provider_shipment_id))?Number(shipment.provider_shipment_id):shipment.provider_shipment_id,data=await shiprocket('/courier/generate/pickup',{method:'POST',body:JSON.stringify({shipment_id:[shipmentId]})}),generated=Number(data?.pickup_generated||0)===1||Boolean(data?.pickup_token_number)||Boolean(data?.pickup_scheduled_date),now=new Date().toISOString(),row=await updateShipment(orderId,{pickup_requested_at:now,status:generated?'pickup_generated':'pickup_requested',provider_status:generated?'Pickup Generated':'Pickup Requested',last_synced_at:now});return{requested:true,generated,pickup_scheduled_date:data?.pickup_scheduled_date||null,shipment:safeShipment(row)}}
async function syncTracking(orderId){const shipment=await getShipment(orderId);if(!shipment?.awb_code)throw new Error('AWB is required before tracking can be synced');const data=await shiprocket('/courier/track/awb/'+encodeURIComponent(shipment.awb_code),{method:'GET'}),tracking=data?.tracking_data||{},track=Array.isArray(tracking.shipment_track)?tracking.shipment_track[0]:null,current=track?.current_status||tracking.current_status||tracking.shipment_status||shipment.provider_status||'Tracking available',url=tracking.track_url||shipment.tracking_url||null,now=new Date().toISOString(),normalized=String(current).trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')||'tracking',row=await updateShipment(orderId,{status:normalized,provider_status:String(current),tracking_url:url?String(url):null,last_synced_at:now});return{synced:true,shipment:safeShipment(row)}}
async function adminList(){const rows=await rest('order_shipments?direction=eq.forward&select=id,order_id,provider,direction,provider_order_id,provider_shipment_id,awb_code,courier_id,courier_name,status,provider_status,tracking_url,label_url,package_weight_kg,package_length_cm,package_breadth_cm,package_height_cm,pickup_requested_at,last_synced_at,created_at&order=created_at.desc&limit=100');return rows||[]}
async function customerStatus(user,key){const order=await getOrderByKey(key);if(String(order.user_id)!==String(user.id)){const error=new Error('Order not found');error.status=404;throw error}return safeShipment(await getShipment(order.id))}
function validOrderId(value){const id=Number(value);return Number.isInteger(id)&&id>0?id:null}
function logShippingFailure(error){const status=Number(error?.status)||400;if(status>=500)console.error('shipping error:',error);else console.warn('shipping rejected:',{status,message:error?.message||'Shipping operation rejected'})}

module.exports=async function shipping(req,res){cors(req,res);if(req.method==='OPTIONS'){res.statusCode=204;return res.end()}if(req.method!=='POST')return json(req,res,405,{error:'Method not allowed'});try{const body=await readBody(req),action=String(body.action||'').trim();if(action==='customer_status'){const user=await getSupabaseUser(req),key=String(body.order_key??body.order_id??'').trim();return json(req,res,200,{ok:true,shipment:await customerStatus(user,key)})}await requireAdminUser(req);if(action==='config')return json(req,res,200,{ok:true,provider:'shiprocket',configured:configured(),serviceability_configured:serviceabilityConfigured(),api_credentials_configured:apiCredentialsConfigured(),pickup_location_configured:Boolean(SHIPROCKET_PICKUP_LOCATION),pickup_pincode_configured:/^\d{6}$/.test(SHIPROCKET_PICKUP_PINCODE)});if(action==='admin_list')return json(req,res,200,{ok:true,shipments:await adminList()});const id=validOrderId(body.order_id);if(!id)return json(req,res,400,{error:'Invalid order ID'});if(action==='check_serviceability')return json(req,res,200,{ok:true,...await checkServiceability(id,body)});if(action==='create_shipment')return json(req,res,200,{ok:true,...await createShipment(id,body)});if(action==='assign_awb')return json(req,res,200,{ok:true,...await assignAwb(id,body)});if(action==='request_pickup')return json(req,res,200,{ok:true,...await requestPickup(id)});if(action==='sync_tracking')return json(req,res,200,{ok:true,...await syncTracking(id)});return json(req,res,400,{error:'Invalid shipping action'})}catch(error){logShippingFailure(error);return json(req,res,error.status||400,{error:error.message||'Shipping operation failed'})}};