const {SUPABASE_URL,serverHeaders,cors,json,readBody,getSupabaseUser,requireAdminUser}=require('../lib');

const SHIPROCKET_EMAIL=String(process.env.SHIPROCKET_EMAIL||'').trim();
const SHIPROCKET_PASSWORD=String(process.env.SHIPROCKET_PASSWORD||'').trim();
const SHIPROCKET_PICKUP_LOCATION=String(process.env.SHIPROCKET_PICKUP_LOCATION||'').trim();
const SHIPROCKET_BASE='https://apiv2.shiprocket.in/v1/external';
let tokenCache={token:'',expiresAt:0};

async function rest(path,options={}){const response=await fetch(SUPABASE_URL+'/rest/v1/'+path,{...options,headers:{...serverHeaders,...(options.headers||{})}});const data=await response.json().catch(()=>null);if(!response.ok){const error=new Error(data?.message||data?.error||'Shipping database request failed');error.status=response.status;throw error}return data}
function configured(){return Boolean(SHIPROCKET_EMAIL&&SHIPROCKET_PASSWORD&&SHIPROCKET_PICKUP_LOCATION)}
function positive(value,label){const n=Number(value);if(!Number.isFinite(n)||n<=0)throw new Error(label+' must be greater than zero');return Math.round(n*1000)/1000}
function safeShipment(row){if(!row)return null;return{order_id:row.order_id,provider:row.provider,direction:row.direction,courier_name:row.courier_name||null,awb_code:row.awb_code||null,status:row.status||'pending',provider_status:row.provider_status||null,tracking_url:row.tracking_url||null,label_url:row.label_url||null,last_synced_at:row.last_synced_at||null,created_at:row.created_at||null}}
const ORDER_SELECT='id,user_id,display_order_id,status,payment_method,fulfillment_status,customer_name,customer_email,customer_phone,shipping_address,items,total_amount,currency,created_at';
async function getOrder(id){const rows=await rest('orders?id=eq.'+encodeURIComponent(id)+'&select='+ORDER_SELECT+'&limit=1');if(!rows?.[0]){const error=new Error('Order not found');error.status=404;throw error}return rows[0]}
async function getOrderByKey(key){const value=String(key||'').trim();if(!value){const error=new Error('Invalid order reference');error.status=400;throw error}const filter=/^\d+$/.test(value)?'id=eq.'+encodeURIComponent(value):'display_order_id=eq.'+encodeURIComponent(value);const rows=await rest('orders?'+filter+'&select='+ORDER_SELECT+'&limit=1');if(!rows?.[0]){const error=new Error('Order not found');error.status=404;throw error}return rows[0]}
async function getShipment(orderId){const rows=await rest('order_shipments?order_id=eq.'+encodeURIComponent(orderId)+'&direction=eq.forward&select=*&limit=1');return rows?.[0]||null}
function assertShippable(order){const fulfillment=String(order.fulfillment_status||'ordered').toLowerCase(),method=String(order.payment_method||'').toLowerCase(),status=String(order.status||'').toLowerCase();if(fulfillment!=='packed')throw new Error('Mark the order Packed before creating a courier shipment');if(method==='prepaid'&&status!=='paid')throw new Error('Only paid prepaid orders can be shipped');if(method==='cod'&&!['cod_pending','cod_collected'].includes(status))throw new Error('This COD order is not eligible for shipping');if(!['prepaid','cod'].includes(method))throw new Error('Unsupported payment method')}
async function shiprocketToken(){if(!configured()){const error=new Error('Shiprocket credentials or pickup location are not configured');error.status=503;throw error}if(tokenCache.token&&Date.now()<tokenCache.expiresAt)return tokenCache.token;const response=await fetch(SHIPROCKET_BASE+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:SHIPROCKET_EMAIL,password:SHIPROCKET_PASSWORD})});const data=await response.json().catch(()=>({}));if(!response.ok||!data?.token){const error=new Error(data?.message||'Shiprocket authentication failed');error.status=502;throw error}tokenCache={token:data.token,expiresAt:Date.now()+8*60*60*1000};return data.token}
async function shiprocket(path,options={}){const token=await shiprocketToken();const response=await fetch(SHIPROCKET_BASE+path,{...options,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data?.message||data?.error||'Shiprocket request failed');error.status=502;throw error}return data}
function orderDate(value){const d=value?new Date(value):new Date();const p=n=>String(n).padStart(2,'0');return d.getUTCFullYear()+'-'+p(d.getUTCMonth()+1)+'-'+p(d.getUTCDate())+' '+p(d.getUTCHours())+':'+p(d.getUTCMinutes())}
function cleanPhone(value){return String(value||'').replace(/\D/g,'').slice(-10)}
function payloadFor(order,box){const a=order.shipping_address||{},phone=cleanPhone(a.phone||order.customer_phone),items=Array.isArray(order.items)?order.items:[];if(!items.length)throw new Error('Order has no items to ship');if(!a.address_line1||!a.city||!a.state||!a.postal_code||!phone)throw new Error('Order delivery address is incomplete for courier booking');const orderItems=items.map((item,index)=>({name:String(item.name||'Product').slice(0,190),sku:String(item.sku||('FF-'+order.id+'-'+(index+1))).slice(0,100),units:Number(item.qty||1),selling_price:Math.max(0.01,Math.round((Number(item.line_total||0)||Number(item.unit_price||0)*Number(item.qty||1))/Math.max(1,Number(item.qty||1))*100)/100),discount:0,tax:0,hsn:''}));return{order_id:'FF-'+String(order.display_order_id||order.id).replace(/[^A-Za-z0-9_-]/g,'-'),order_date:orderDate(order.created_at),pickup_location:SHIPROCKET_PICKUP_LOCATION,billing_customer_name:String(a.full_name||order.customer_name||'Customer').slice(0,100),billing_last_name:'',billing_address:String(a.address_line1).slice(0,200),billing_address_2:String(a.address_line2||'').slice(0,200),billing_city:String(a.city).slice(0,100),billing_pincode:String(a.postal_code).trim(),billing_state:String(a.state).slice(0,100),billing_country:String(a.country||'India').slice(0,100),billing_email:String(order.customer_email||'').slice(0,150),billing_phone:phone,shipping_is_billing:true,order_items:orderItems,payment_method:String(order.payment_method).toLowerCase()==='cod'?'COD':'Prepaid',sub_total:Math.max(0.01,Math.round(Number(order.total_amount||0)*100)/100),length:box.length,breadth:box.breadth,height:box.height,weight:box.weight}}
async function createShipment(orderId,body){if(!configured()){const error=new Error('Shiprocket is not active yet. Configure server credentials and pickup location first.');error.status=503;throw error}const order=await getOrder(orderId);assertShippable(order);const existing=await getShipment(orderId);if(existing?.provider_shipment_id||existing?.provider_order_id)return{created:false,idempotent:true,shipment:safeShipment(existing)};const box={weight:positive(body.weight_kg,'Package weight'),length:positive(body.length_cm,'Package length'),breadth:positive(body.breadth_cm,'Package breadth'),height:positive(body.height_cm,'Package height')};const data=await shiprocket('/orders/create/adhoc',{method:'POST',body:JSON.stringify(payloadFor(order,box))});const providerOrderId=data?.order_id??data?.data?.order_id??null,providerShipmentId=data?.shipment_id??data?.data?.shipment_id??null;if(!providerOrderId&&!providerShipmentId){const error=new Error('Shiprocket did not return an order or shipment ID');error.status=502;throw error}const now=new Date().toISOString(),record={order_id:order.id,provider:'shiprocket',direction:'forward',provider_order_id:providerOrderId==null?null:String(providerOrderId),provider_shipment_id:providerShipmentId==null?null:String(providerShipmentId),awb_code:data?.awb_code?String(data.awb_code):null,courier_id:data?.courier_company_id?String(data.courier_company_id):null,courier_name:data?.courier_name?String(data.courier_name):null,status:'created',provider_status:data?.status?String(data.status):'created',tracking_url:data?.tracking_url?String(data.tracking_url):null,label_url:null,package_weight_kg:box.weight,package_length_cm:box.length,package_breadth_cm:box.breadth,package_height_cm:box.height,last_synced_at:now,updated_at:now};const rows=await rest('order_shipments?on_conflict=order_id,direction',{method:'POST',headers:{'Content-Type':'application/json','Prefer':'resolution=merge-duplicates,return=representation'},body:JSON.stringify(record)});return{created:true,idempotent:false,shipment:safeShipment(rows?.[0]||record),provider_response:{order_id:record.provider_order_id,shipment_id:record.provider_shipment_id}}}
async function adminList(){const rows=await rest('order_shipments?direction=eq.forward&select=id,order_id,provider,direction,provider_order_id,provider_shipment_id,awb_code,courier_name,status,provider_status,tracking_url,label_url,package_weight_kg,package_length_cm,package_breadth_cm,package_height_cm,last_synced_at,created_at&order=created_at.desc&limit=100');return rows||[]}
async function customerStatus(user,key){const order=await getOrderByKey(key);if(String(order.user_id)!==String(user.id)){const error=new Error('Order not found');error.status=404;throw error}return safeShipment(await getShipment(order.id))}

module.exports=async function shipping(req,res){cors(req,res);if(req.method==='OPTIONS'){res.statusCode=204;return res.end()}if(req.method!=='POST')return json(req,res,405,{error:'Method not allowed'});try{const body=await readBody(req),action=String(body.action||'').trim();if(action==='customer_status'){const user=await getSupabaseUser(req),key=String(body.order_key??body.order_id??'').trim();return json(req,res,200,{ok:true,shipment:await customerStatus(user,key)})}const admin=await requireAdminUser(req);void admin;if(action==='config')return json(req,res,200,{ok:true,provider:'shiprocket',configured:configured(),pickup_location_configured:Boolean(SHIPROCKET_PICKUP_LOCATION)});if(action==='admin_list')return json(req,res,200,{ok:true,shipments:await adminList()});if(action==='create_shipment'){const id=Number(body.order_id);if(!Number.isInteger(id)||id<1)return json(req,res,400,{error:'Invalid order ID'});return json(req,res,200,{ok:true,...await createShipment(id,body)})}return json(req,res,400,{error:'Invalid shipping action'})}catch(error){console.error('shipping error:',error);return json(req,res,error.status||400,{error:error.message||'Shipping operation failed'})}};
