const crypto=require("crypto");
const {KEY_SECRET,SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY,cors,json,readBody,basicAuth,getSupabaseUser}=require("../lib");
const serverHeaders={apikey:SUPABASE_SERVICE_ROLE_KEY,Authorization:"Bearer "+SUPABASE_SERVICE_ROLE_KEY};
async function rpc(name,args){const r=await fetch(SUPABASE_URL+"/rest/v1/rpc/"+name,{method:"POST",headers:{...serverHeaders,"Content-Type":"application/json"},body:JSON.stringify(args)});if(!r.ok){let d={};try{d=await r.json()}catch{}throw new Error(d?.message||"Could not finalize promotions")}}
module.exports=async function(req,res){cors(res);if(req.method==="OPTIONS"){res.statusCode=204;return res.end()}if(req.method!=="POST")return json(res,405,{error:"Method not allowed"});if(!KEY_SECRET)return json(res,500,{error:"Razorpay server key is not configured"});try{
 const user=await getSupabaseUser(req),body=await readBody(req);const {order_id,razorpay_payment_id,razorpay_order_id,razorpay_signature}=body;if(!order_id||!razorpay_payment_id||!razorpay_order_id||!razorpay_signature)return json(res,400,{verified:false,error:"Missing payment fields"});if(order_id!==razorpay_order_id)return json(res,400,{verified:false,error:"Order ID mismatch"});
 const expected=crypto.createHmac("sha256",KEY_SECRET).update(order_id+"|"+razorpay_payment_id).digest("hex"),a=Buffer.from(expected,"utf8"),b=Buffer.from(razorpay_signature,"utf8");if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return json(res,400,{verified:false,error:"Invalid payment signature"});
 const pr=await fetch("https://api.razorpay.com/v1/payments/"+encodeURIComponent(razorpay_payment_id),{headers:{Authorization:basicAuth()}}),payment=await pr.json();if(!pr.ok)return json(res,502,{verified:false,error:"Could not verify payment status"});if(payment.order_id!==order_id)return json(res,400,{verified:false,error:"Payment/order mismatch"});if(payment.status!=="captured")return json(res,400,{verified:false,error:"Payment is not captured yet"});
 const lr=await fetch(SUPABASE_URL+"/rest/v1/orders?razorpay_order_id=eq."+encodeURIComponent(order_id)+"&select=id,user_id,total_amount,status,items,coupon_code,coupon_discount,gift_card_code,gift_card_discount",{headers:serverHeaders}),orders=await lr.json();if(!lr.ok||!orders.length)return json(res,404,{verified:false,error:"Store order was not found"});const o=orders[0];if(o.user_id!==user.id)return json(res,403,{verified:false,error:"This order does not belong to the current user"});if(Math.round(Number(o.total_amount)*100)!==Number(payment.amount))return json(res,400,{verified:false,error:"Payment amount does not match order amount"});
 if(o.status==="paid")return json(res,200,{verified:true,already_processed:true,payment_id:razorpay_payment_id,order_id,store_order_id:o.id,status:"paid"});
 try{await rpc("finalize_order_promotions",{p_order_id:o.id,p_user_id:user.id})}catch(e){console.error("Promotion finalize failed:",e);return json(res,409,{verified:false,error:"Payment is captured, but offer redemption needs support review. Please do not pay again.",store_order_id:o.id})}
 const ur=await fetch(SUPABASE_URL+"/rest/v1/orders?razorpay_order_id=eq."+encodeURIComponent(order_id)+"&user_id=eq."+encodeURIComponent(user.id),{method:"PATCH",headers:{...serverHeaders,"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify({razorpay_payment_id,status:"paid"})}),updated=await ur.json();if(!ur.ok)return json(res,500,{verified:false,error:"Payment was verified but the store order could not be updated",store_order_id:o.id});return json(res,200,{verified:true,payment_id:razorpay_payment_id,order_id,store_order_id:o.id,status:"paid"});
}catch(error){console.error("verify-payment error:",error);return json(res,400,{verified:false,error:error.message||"Payment verification failed"})}};