(function(){
'use strict';
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const fmt=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})};
const typeLabel=t=>t==='exchange_size'?'Exchange Size':t==='return_refund'?'Return for Refund':'Report an Issue';
const statusLabel=s=>String(s||'requested').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const statusTone=s=>{s=String(s||'').toLowerCase();if(['completed','approved'].includes(s))return'good';if(['rejected','cancelled'].includes(s))return'bad';return'warn'};
let installed=false,requests=[],orderMap=new Map();
function ensureStyles(){if(document.getElementById('accountReturnsStyles'))return;const s=document.createElement('style');s.id='accountReturnsStyles';s.textContent=`
.return-card{border:1px solid var(--line);border-radius:12px;background:#fff;overflow:hidden}.return-card+.return-card{margin-top:12px}.return-top{padding:13px 16px;background:#fafbfc;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;gap:16px}.return-main{padding:16px;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:18px}.return-title{font-size:14px;font-weight:900;margin-bottom:5px}.return-meta{font-size:11px;color:var(--muted);line-height:1.6}.return-reason{margin-top:10px;padding:10px 11px;border-radius:9px;background:#f8f9fb;font-size:11px;line-height:1.55;color:#4f5663}.return-link{align-self:start}.return-note{margin-top:12px;font-size:11px;color:var(--muted);line-height:1.6}`;document.head.appendChild(s)}
function ensureView(){if(installed)return true;const menu=document.querySelector('.menu'),refundBtn=menu?.querySelector('[data-view="refunds"]'),section=document.querySelector('.layout > section');if(!menu||!section)return false;ensureStyles();const btn=document.createElement('button');btn.type='button';btn.dataset.view='returns';btn.textContent='Returns & Exchanges';if(refundBtn)menu.insertBefore(btn,refundBtn);else menu.insertBefore(btn,menu.querySelector('.danger'));const view=document.createElement('div');view.id='returnsView';view.className='view';view.innerHTML='<div class="panel"><div class="panel-head"><h2>Returns & exchanges</h2><button class="btn" id="refreshReturns" type="button">↻ Refresh</button></div><div class="panel-body"><div id="returnsList"><div class="empty">Loading return and exchange requests…</div></div></div></div>';const refunds=document.getElementById('refundsView');if(refunds)refunds.after(view);else section.appendChild(view);btn.addEventListener('click',()=>activate());view.querySelector('#refreshReturns').addEventListener('click',loadRequests);installed=true;return true}
function activate(){if(!ensureView())return;document.querySelectorAll('.menu button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='returns'));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='returnsView'));const title=document.getElementById('viewTitle'),sub=document.getElementById('viewSub');if(title)title.textContent='Returns & Exchanges';if(sub)sub.textContent='Track exchange, return and issue requests from delivered orders.';if(location.hash!=='#returns')history.replaceState(null,'','#returns');loadRequests()}
function orderRef(r){const o=orderMap.get(String(r.order_id));return o?.display_order_id||r.order_id}
function itemName(r){const o=orderMap.get(String(r.order_id)),x=Array.isArray(o?.items)?o.items[r.item_index]:null;return x?.name||x?.product_name||`Order item ${Number(r.item_index||0)+1}`}
function render(){const el=document.getElementById('returnsList');if(!el)return;if(!requests.length){el.innerHTML='<div class="empty">No return, exchange or issue requests yet.<div class="return-note">Open a delivered order to start an eligible request.</div></div>';return}el.innerHTML=requests.map(r=>`<article class="return-card"><div class="return-top"><div><div class="meta-label">${esc(typeLabel(r.request_type))}</div><div class="meta-value">Order #${esc(orderRef(r))}</div></div><span class="badge ${statusTone(r.status)}">${esc(statusLabel(r.status))}</span></div><div class="return-main"><div><div class="return-title">${esc(itemName(r))}</div><div class="return-meta">Quantity ${esc(r.quantity)}${r.requested_size?` · Requested size ${esc(r.requested_size)}`:''} · Requested ${esc(fmt(r.created_at))}${r.updated_at&&r.updated_at!==r.created_at?` · Updated ${esc(fmt(r.updated_at))}`:''}</div><div class="return-reason">${esc(r.reason)}</div>${r.admin_note?`<div class="return-note"><b>Store update:</b> ${esc(r.admin_note)}</div>`:''}</div><a class="btn return-link" href="order-details.html?id=${encodeURIComponent(r.order_id)}">View order</a></div></article>`).join('')}
async function loadRequests(){const el=document.getElementById('returnsList');if(el)el.innerHTML='<div class="empty">Loading return and exchange requests…</div>';try{const{data:{session},error:se}=await supabaseClient.auth.getSession();if(se||!session?.user)throw new Error('Please sign in again.');const{data,error}=await supabaseClient.from('return_requests').select('id,order_id,item_index,request_type,quantity,reason,requested_size,status,admin_note,created_at,updated_at,resolved_at').eq('user_id',session.user.id).order('created_at',{ascending:false});if(error)throw error;requests=data||[];const ids=[...new Set(requests.map(r=>Number(r.order_id)).filter(Number.isFinite))];orderMap=new Map();if(ids.length){const{data:orders,error:oe}=await supabaseClient.from('orders').select('id,display_order_id,items').eq('user_id',session.user.id).in('id',ids);if(oe)throw oe;(orders||[]).forEach(o=>orderMap.set(String(o.id),o))}render()}catch(e){if(el)el.innerHTML='<div class="empty">Could not load return activity. '+esc(e.message||'Please try again.')+'</div>'}}
function install(){if(!ensureView())return false;if(location.hash==='#returns')activate();return true}
let tries=0;const timer=setInterval(()=>{tries++;if(install()||tries>50)clearInterval(timer)},100);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
