(function(){'use strict';
const auditFields='id,display_order_id,status,payment_method,created_at,cancellation_reason,cancelled_at,refund_id,refund_status,refund_reference,refund_amount,refund_updated_at';
function refundTone(status){const s=String(status||'').toLowerCase();if(s==='refunded'||s==='processed')return['Refunded','good'];if(s==='refund_failed'||s==='failed')return['Refund needs attention','bad'];return['Refund in progress','warn']}
function refundCard(o){const st=refundTone(o.refund_status||o.status),display=o.display_order_id||o.id,amount=o.refund_amount==null?'Pending confirmation':money(o.refund_amount),updated=o.refund_updated_at?fmtDate(o.refund_updated_at):'',reference=o.refund_reference?'<div><div class="meta-label">Reference</div><div class="meta-value">'+esc(o.refund_reference)+'</div></div>':'',reason=o.cancellation_reason?'<div class="muted" style="margin-top:8px">Cancellation reason: '+esc(o.cancellation_reason)+'</div>':'';return '<article class="order"><div class="order-head"><div class="order-meta"><div><div class="meta-label">Order</div><div class="meta-value">#'+esc(display)+'</div></div><div><div class="meta-label">Refund amount</div><div class="meta-value">'+esc(amount)+'</div></div><div><div class="meta-label">Destination</div><div class="meta-value">Original payment method</div></div>'+reference+'</div><span class="badge '+st[1]+'">'+esc(st[0])+'</span></div><div class="order-body"><div><div class="pname">Refund status</div><div class="muted">Processor status: '+esc(o.refund_status||String(o.status||'').replaceAll('_',' '))+(updated?' · Updated '+esc(updated):'')+'</div>'+reason+'</div><div class="order-total">'+esc(amount)+'</div></div><div class="order-actions"><a class="btn primary" href="order-details.html?id='+encodeURIComponent(o.id)+'#help">View refund details</a></div></article>'}
function mergeAudit(rows){const byId=new Map((rows||[]).map(r=>[String(r.id),r]));ordersCache=ordersCache.map(o=>({...o,...(byId.get(String(o.id))||{})}))}
async function hydrateAudit(){if(!currentUser?.id)return;const{data,error}=await supabaseClient.from('orders').select(auditFields).eq('user_id',currentUser.id).order('created_at',{ascending:false});if(error)throw error;mergeAudit(data||[]);renderRefunds()}
function install(){if(typeof renderRefunds!=='function'||typeof ordersCache==='undefined'||typeof $!=='function'||typeof loadOrders!=='function')return false;renderRefunds=function(){const list=ordersCache.filter(o=>['refund_pending','refund_initiated','refund_failed','refunded'].includes(String(o.status||'').toLowerCase())||o.refund_id),box=$('refundsList');if(!box)return;if(!list.length){box.innerHTML='<div class="empty">No refund activity yet.</div>';return}box.innerHTML=list.map(refundCard).join('')};loadOrders=async function(){const box=$('ordersList');box.innerHTML='<div class="empty">Loading orders…</div>';const{data,error}=await supabaseClient.from('orders').select('id,display_order_id,total_amount,currency,status,payment_method,fulfillment_status,created_at,items,gift_card_discount,cancellation_reason,cancelled_at,refund_id,refund_status,refund_reference,refund_amount,refund_updated_at').eq('user_id',currentUser.id).order('created_at',{ascending:false});if(error)throw error;ordersCache=data||[];renderOrders()};if(currentUser?.id)hydrateAudit().catch(e=>console.error('refund audit hydration error:',e));return true}
let tries=0;const timer=setInterval(()=>{tries++;if(install()||tries>40)clearInterval(timer)},100);
})();
