(function(){
'use strict';
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const fmt=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('en-IN',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})};
const money=v=>'₹'+Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const typeLabel=t=>t==='exchange_size'?'Exchange Size':t==='return_refund'?'Return for Refund':'Report an Issue';
const statusLabel=s=>String(s||'requested').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const STATUSES=['requested','under_review','approved','rejected','exchange_processing','return_processing','completed','cancelled'];
let rows=[],orderMap=new Map(),ready=false;
function styles(){if(document.getElementById('adminReturnsStyles'))return;const s=document.createElement('style');s.id='adminReturnsStyles';s.textContent=`
#adminReturnsCard .return-filters{display:flex;gap:8px;align-items:center;flex-wrap:wrap}#adminReturnsCard .return-filters select{padding:8px 10px;border:1px solid #ccc;border-radius:4px;background:#fff}#adminReturnsTable textarea{width:220px;min-height:58px;padding:7px;border:1px solid #ccc;border-radius:4px;resize:vertical}#adminReturnsTable select{min-width:150px;padding:7px;border:1px solid #ccc;border-radius:4px;background:#fff}.return-sub{font-size:11px;color:#777;line-height:1.45;margin-top:4px}.return-reason{max-width:260px;white-space:normal;line-height:1.45}.return-status{font-weight:700}.return-inline-status{font-size:11px;margin-top:6px;min-height:16px}.return-inline-status.ok{color:#2e7d32}.return-inline-status.err{color:#c62828}.return-actions{display:flex;flex-direction:column;gap:7px}.refund-meta{margin-top:7px;padding:8px;border-radius:6px;background:#f7f8fa;font-size:11px;line-height:1.5}`;document.head.appendChild(s)}
function mount(){if(document.getElementById('adminReturnsCard'))return true;const container=document.querySelector('#dashboard .container');if(!container)return false;styles();const section=document.createElement('section');section.className='card';section.id='adminReturnsCard';section.innerHTML=`<div class="card-header"><div><h2>Returns & Exchanges</h2><div class="return-sub">Review requests. Approved prepaid return refunds can be initiated securely from here.</div></div><div class="return-filters"><select id="adminReturnFilter"><option value="active">Active requests</option><option value="all">All requests</option><option value="closed">Closed requests</option></select><button class="secondary" id="refreshAdminReturns" type="button">↻ Refresh</button></div></div><div class="card-body"><div id="adminReturnsStatus" class="status"></div><div class="table-wrapper"><table><thead><tr><th>REQUEST</th><th>ORDER / ITEM</th><th>DETAILS</th><th>STATUS</th><th>ADMIN NOTE</th><th>ACTION</th></tr></thead><tbody id="adminReturnsTable"><tr><td colspan="6">Loading…</td></tr></tbody></table></div></div>`;container.appendChild(section);section.querySelector('#refreshAdminReturns').addEventListener('click',load);section.querySelector('#adminReturnFilter').addEventListener('change',render);return true}
function orderInfo(r){return orderMap.get(String(r.order_id))||null}
function itemInfo(r){const o=orderInfo(r),items=Array.isArray(o?.items)?o.items:[];return items[Number(r.item_index)]||null}
function isClosed(s){return ['rejected','completed','cancelled'].includes(String(s||'').toLowerCase())}
function filtered(){const mode=document.getElementById('adminReturnFilter')?.value||'active';if(mode==='all')return rows;if(mode==='closed')return rows.filter(r=>isClosed(r.status));return rows.filter(r=>!isClosed(r.status))}
function refundMeta(r){if(!r.refund_id)return'';return `<div class="refund-meta"><b>Refund:</b> ${esc(statusLabel(r.refund_status||'pending'))}${r.refund_amount!=null?` · ${esc(money(r.refund_amount))}`:''}${r.refund_reference?`<br><b>Reference:</b> ${esc(r.refund_reference)}`:''}${r.refund_updated_at?`<br>Updated ${esc(fmt(r.refund_updated_at))}`:''}</div>`}
function render(){const body=document.getElementById('adminReturnsTable');if(!body)return;const list=filtered();if(!list.length){body.innerHTML='<tr><td colspan="6" style="text-align:center;padding:28px">No matching return or exchange requests.</td></tr>';return}body.innerHTML=list.map(r=>{const o=orderInfo(r),item=itemInfo(r),ref=o?.display_order_id||r.order_id;const canRefund=r.request_type==='return_refund'&&['approved','return_processing'].includes(String(r.status||'').toLowerCase())&&!r.refund_id;return `<tr data-request="${esc(r.id)}"><td><b>${esc(typeLabel(r.request_type))}</b><div class="return-sub">#${esc(r.id)} · ${esc(fmt(r.created_at))}</div></td><td><b>Order #${esc(ref)}</b><div class="return-sub">${esc(item?.name||item?.product_name||('Item '+(Number(r.item_index)+1)))} · Qty ${esc(r.quantity)}</div></td><td class="return-reason">${esc(r.reason)}${r.requested_size?`<div class="return-sub"><b>Requested size:</b> ${esc(r.requested_size)}</div>`:''}${refundMeta(r)}</td><td><select data-status>${STATUSES.map(s=>`<option value="${s}"${s===r.status?' selected':''}>${esc(statusLabel(s))}</option>`).join('')}</select><div class="return-sub">Current: <span class="return-status">${esc(statusLabel(r.status))}</span></div></td><td><textarea data-note maxlength="1000" placeholder="Internal note">${esc(r.admin_note||'')}</textarea></td><td><div class="return-actions"><button class="primary" data-save type="button">Save update</button>${canRefund?'<button class="secondary" data-refund type="button">Initiate refund</button>':''}</div><div class="return-inline-status" aria-live="polite"></div></td></tr>`}).join('');body.querySelectorAll('[data-save]').forEach(btn=>btn.addEventListener('click',()=>save(btn.closest('tr'))));body.querySelectorAll('[data-refund]').forEach(btn=>btn.addEventListener('click',()=>processRefund(btn.closest('tr'))))}
async function save(tr){const id=Number(tr?.dataset.request),status=tr?.querySelector('[data-status]')?.value,note=tr?.querySelector('[data-note]')?.value.trim()||null,feedback=tr?.querySelector('.return-inline-status'),btn=tr?.querySelector('[data-save]');if(!Number.isInteger(id)||!STATUSES.includes(status))return;btn.disabled=true;if(feedback){feedback.textContent='Saving…';feedback.className='return-inline-status'}try{const resolved=isClosed(status)?new Date().toISOString():null;const{data,error}=await supabaseClient.from('return_requests').update({status,admin_note:note,updated_at:new Date().toISOString(),resolved_at:resolved}).eq('id',id).select('id,status,admin_note,updated_at,resolved_at').single();if(error)throw error;const target=rows.find(r=>Number(r.id)===id);if(target)Object.assign(target,data);if(feedback){feedback.textContent='Saved';feedback.className='return-inline-status ok'}render()}catch(e){if(feedback){feedback.textContent=e.message||'Could not save';feedback.className='return-inline-status err'}}finally{btn.disabled=false}}
async function processRefund(tr){const id=Number(tr?.dataset.request),feedback=tr?.querySelector('.return-inline-status'),btn=tr?.querySelector('[data-refund]');if(!Number.isInteger(id)||!btn)return;btn.disabled=true;if(feedback){feedback.textContent='Initiating refund…';feedback.className='return-inline-status'}try{const{data:{session},error:se}=await supabaseClient.auth.getSession();if(se||!session?.access_token)throw new Error('Admin session required');const response=await fetch('/api/process-return-refund',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+session.access_token},body:JSON.stringify({return_request_id:id})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Refund could not be initiated');if(feedback){feedback.textContent=data.already_initiated?'Refund was already initiated.':'Refund initiated successfully.';feedback.className='return-inline-status ok'}await load()}catch(e){if(feedback){feedback.textContent=e.message||'Could not initiate refund';feedback.className='return-inline-status err'}btn.disabled=false}}
async function load(){const body=document.getElementById('adminReturnsTable');if(body)body.innerHTML='<tr><td colspan="6">Loading…</td></tr>';try{const{data:{session},error:se}=await supabaseClient.auth.getSession();if(se||!session?.user)throw new Error('Admin session required');const{data:profile,error:pe}=await supabaseClient.from('profiles').select('is_admin').eq('id',session.user.id).maybeSingle();if(pe||!profile?.is_admin)throw new Error('Administrator access required');const{data,error}=await supabaseClient.from('return_requests').select('id,user_id,order_id,item_index,request_type,quantity,reason,requested_size,status,admin_note,refund_id,refund_status,refund_reference,refund_amount,refund_updated_at,created_at,updated_at,resolved_at').order('created_at',{ascending:false}).limit(250);if(error)throw error;rows=data||[];const ids=[...new Set(rows.map(r=>Number(r.order_id)).filter(Number.isFinite))];orderMap=new Map();if(ids.length){const{data:orders,error:oe}=await supabaseClient.from('orders').select('id,display_order_id,items').in('id',ids);if(oe)throw oe;(orders||[]).forEach(o=>orderMap.set(String(o.id),o))}render()}catch(e){if(body)body.innerHTML='<tr><td colspan="6" style="color:#c62828">'+esc(e.message||'Could not load return requests')+'</td></tr>'}}
function init(){if(ready)return;if(!mount())return;ready=true;load()}
let tries=0;const timer=setInterval(()=>{tries++;if(document.querySelector('#dashboard .container')){init();clearInterval(timer)}else if(tries>60)clearInterval(timer)},100);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
