(function(){
'use strict';
if(!window.supabaseClient)return;
if((location.pathname.split('/').pop()||'index.html')!=='index.html')return;
const supa=window.supabaseClient;
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
let defaultAddress=null,loading=false,allowCheckout=false;
function card(){return document.getElementById('ffCheckoutAddress')}
function install(){const btn=document.getElementById('checkoutBtn');if(!btn)return setTimeout(install,200);if(card())return;const box=document.createElement('div');box.id='ffCheckoutAddress';box.style.cssText='margin:12px 0;padding:12px;border:1px solid #ddd;border-radius:7px;background:#fff;font-size:13px;line-height:1.5';btn.parentNode.insertBefore(box,btn);btn.addEventListener('click',guard,true);refresh();document.addEventListener('click',e=>{if(e.target.closest('#cartBtn,#cartButton,[data-cart],.cart-button'))setTimeout(refresh,150)});supa.auth.onAuthStateChange(()=>setTimeout(refresh,50))}
async function refresh(){const box=card();if(!box||loading)return;loading=true;box.innerHTML='<b>Delivery Address</b><div style="color:#777;margin-top:5px">Checking saved address...</div>';try{const{data:{user}}=await supa.auth.getUser();if(!user){defaultAddress=null;box.innerHTML='<b>Delivery Address</b><div style="color:#777;margin-top:5px">Login to use your saved delivery address.</div>';return}const{data,error}=await supa.from('customer_addresses').select('id,label,full_name,phone,address_line1,address_line2,city,state,postal_code,country,is_default').eq('user_id',user.id).eq('is_default',true).limit(1).maybeSingle();if(error)throw error;defaultAddress=data||null;if(!data){box.innerHTML='<b>Delivery Address</b><div style="color:#c62828;margin-top:5px">No default delivery address selected.</div><a href="account.html" style="display:inline-block;margin-top:7px;color:#2874f0;font-weight:700">+ Add / Select Address</a>';return}box.innerHTML='<div style="display:flex;justify-content:space-between;gap:10px"><b>Deliver to '+esc(data.label||'Address')+'</b><a href="account.html" style="color:#2874f0;font-weight:700">Change</a></div><div style="margin-top:6px"><b>'+esc(data.full_name)+'</b> · '+esc(data.phone)+'<br>'+esc(data.address_line1)+(data.address_line2?'<br>'+esc(data.address_line2):'')+'<br>'+esc(data.city)+', '+esc(data.state)+' - '+esc(data.postal_code)+'</div>'}catch(err){console.error('Address load error:',err);defaultAddress=null;box.innerHTML='<b>Delivery Address</b><div style="color:#c62828;margin-top:5px">Unable to load saved address.</div>'}finally{loading=false}}
async function guard(e){if(allowCheckout){allowCheckout=false;return}e.preventDefault();e.stopImmediatePropagation();const btn=document.getElementById('checkoutBtn');const old=btn.textContent;btn.disabled=true;btn.textContent='Checking address…';await refresh();btn.disabled=false;btn.textContent=old;if(!defaultAddress){alert('Please add and select a default delivery address before checkout.');location.href='account.html';return}if(typeof window.checkout!=='function'){alert('Checkout is still loading. Please try again.');return}allowCheckout=true;window.checkout()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();