(function(){
'use strict';
if(!window.supabaseClient)return;
const supa=window.supabaseClient,page=location.pathname.split('/').pop()||'index.html';
let isAdmin=page==='admin.html',isCustomer=['index.html','account.html'].includes(page);
if(!isAdmin&&!isCustomer)return;
const style=document.createElement('style');style.textContent=`#ffSupportLauncher{position:fixed;right:18px;bottom:18px;z-index:9998;border:0;border-radius:999px;padding:13px 18px;background:#2874f0;color:#fff;font-weight:700;box-shadow:0 4px 18px #0003}#ffSupportPanel{position:fixed;right:18px;bottom:72px;width:360px;max-width:calc(100vw - 36px);height:520px;max-height:70vh;z-index:9999;background:#fff;border:1px solid #ddd;border-radius:12px;box-shadow:0 8px 35px #0004;display:none;overflow:hidden}#ffSupportPanel.open{display:flex;flex-direction:column}#ffSupportHead{padding:13px 15px;background:#2874f0;color:#fff;display:flex;justify-content:space-between;align-items:center;font-weight:700}#ffSupportClose{background:transparent;border:0;color:#fff;font-size:22px}#ffSupportBody{padding:14px;overflow:auto;flex:1}.ffMsg{padding:9px 11px;border-radius:10px;margin:7px 0;max-width:85%;font-size:13px;white-space:pre-wrap}.ffCustomer{margin-left:auto;background:#e3f2fd}.ffAdmin{background:#f1f1f1}.ffReq{padding:10px;border:1px solid #ddd;border-radius:8px;margin:8px 0}.ffBtn,.ffReq button{display:block;width:100%;margin:7px 0;padding:9px;border:0;border-radius:6px;background:#2874f0;color:#fff;font-weight:600}.ffInput{display:flex;gap:7px;padding:10px;border-top:1px solid #eee}.ffInput input{flex:1;padding:9px;border:1px solid #bbb;border-radius:6px}.ffInput button{border:0;border-radius:6px;background:#2874f0;color:#fff;padding:9px 12px}.ffForm input,.ffForm textarea{width:100%;margin:5px 0;padding:9px;border:1px solid #bbb;border-radius:6px;box-sizing:border-box}.ffForm textarea{min-height:75px}.ffForm button{width:100%;margin-top:6px;padding:9px;border:0;border-radius:6px;background:#2874f0;color:#fff;font-weight:700}.ffBack{background:#666!important}`;document.head.appendChild(style);
async function resolveRole(){
  if(isAdmin)return;
  try{
    const u=(await supa.auth.getUser()).data.user;
    if(!u)return;
    const{data:p}=await supa.from('profiles').select('is_admin').eq('id',u.id).maybeSingle();
    if(p?.is_admin===true){isAdmin=true;isCustomer=false;}
  }catch(e){console.error('Support role check failed:',e)}
}
function shell(){const b=document.createElement('button');b.id='ffSupportLauncher';b.textContent=isAdmin?'🔔 Admin Support':'💬 Customer Care';document.body.appendChild(b);const p=document.createElement('div');p.id='ffSupportPanel';p.innerHTML='<div id="ffSupportHead"><span>'+(isAdmin?'Admin Support Inbox':'Customer Care')+'</span><button id="ffSupportClose">×</button></div><div id="ffSupportBody"></div><div class="ffInput" id="ffSupportInput" style="display:none"><input id="ffSupportText" placeholder="Type your message"><button id="ffSupportSend">Send</button></div>';document.body.appendChild(p);b.onclick=()=>{p.classList.toggle('open');if(p.classList.contains('open'))isAdmin?loadAdmin():customerHome()};document.getElementById('ffSupportClose').onclick=()=>p.classList.remove('open')}
const body=()=>document.getElementById('ffSupportBody'),input=()=>document.getElementById('ffSupportInput');async function user(){return(await supa.auth.getUser()).data.user}function esc(v){return String(v||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
async function customerHome(){input().style.display='none';const u=await user();if(u){const{data:r}=await supa.from('customer_support_requests').select('*').eq('user_id',u.id).in('status',['pending','accepted']).order('created_at',{ascending:false}).limit(1).maybeSingle();if(r){showCustomerChat(r);return}}body().innerHTML='<p><b>Hi! How can we help you?</b></p><button class="ffBtn" data-faq="delivery">Delivery & Shipping</button><button class="ffBtn" data-faq="order">Order Help</button><button class="ffBtn" data-faq="payment">Payment Help</button><button class="ffBtn" data-faq="return">Return / Refund</button><button class="ffBtn" id="ffAgent">👤 Connect me to an Agent</button>';document.querySelectorAll('[data-faq]').forEach(x=>x.onclick=()=>faq(x.dataset.faq));document.getElementById('ffAgent').onclick=agentForm}
function faq(k){const a={delivery:'Free delivery is available when the order subtotal is ₹299 or more. Below ₹299, delivery charge is ₹49.',order:'For order-related help, please check My Account → Orders. If you still need help, choose Connect me to an Agent.',payment:'If payment fails, do not pay repeatedly. Check your order/payment status first. If money was deducted but the order is not confirmed, connect to an agent.',return:'For return or refund assistance, please connect to an agent and describe the order issue.'};body().innerHTML='<div class="ffReq">'+esc(a[k])+'</div><button class="ffBtn ffBack" id="ffBack">← Back</button><button class="ffBtn" id="ffAgent">👤 Connect me to an Agent</button>';document.getElementById('ffBack').onclick=customerHome;document.getElementById('ffAgent').onclick=agentForm}
async function agentForm(){const u=await user();if(!u){body().innerHTML='<p>Agent se connect hone ke liye please login karein.</p><a href="login.html">Login</a><button class="ffBtn ffBack" id="ffBack">← Back</button>';document.getElementById('ffBack').onclick=customerHome;return}body().innerHTML='<div class="ffForm"><p><b>Connect me to an Agent</b></p><input id="ffName" placeholder="Your name"><input id="ffPhone" placeholder="Mobile number"><textarea id="ffIssue" placeholder="Describe your issue"></textarea><button id="ffCreate">Send request to agent</button><button class="ffBack" id="ffBack">Cancel</button></div>';const{data:p}=await supa.from('profiles').select('full_name,phone').eq('id',u.id).maybeSingle();if(p){ffName.value=p.full_name||'';ffPhone.value=p.phone||''}document.getElementById('ffBack').onclick=customerHome;document.getElementById('ffCreate').onclick=async()=>{const name=ffName.value.trim(),phone=ffPhone.value.trim(),issue=ffIssue.value.trim();if(!name||!phone||!issue){alert('Name, mobile and issue are required.');return}const{data,error}=await supa.from('customer_support_requests').insert({user_id:u.id,customer_name:name,customer_phone:phone,customer_email:u.email||null,issue}).select().single();if(error)alert(error.message);else showCustomerChat(data)}}
function showCustomerChat(r){body().innerHTML='<div class="ffReq"><b>Agent request #'+r.id+'</b><br>Status: '+(r.status==='pending'?'Waiting for admin to accept':r.status)+'<br><small>'+esc(r.issue)+'</small></div><div id="ffMessages"></div>';input().style.display=r.status==='accepted'?'flex':'none';loadMessages(r.id);subscribeCustomer(r.id)}async function loadMessages(id){const{data}=await supa.from('customer_support_messages').select('*').eq('request_id',id).order('created_at');const b=document.getElementById('ffMessages');if(b)b.innerHTML=(data||[]).map(m=>'<div class="ffMsg '+(m.sender_type==='customer'?'ffCustomer':'ffAdmin')+'">'+esc(m.message)+'</div>').join('')}
function subscribeCustomer(id){if(window.__ffSupportChannel)supa.removeChannel(window.__ffSupportChannel);window.__ffSupportChannel=supa.channel('support-customer-'+id).on('postgres_changes',{event:'*',schema:'public',table:'customer_support_messages',filter:'request_id=eq.'+id},()=>loadMessages(id)).on('postgres_changes',{event:'UPDATE',schema:'public',table:'customer_support_requests',filter:'id=eq.'+id},()=>customerHome()).subscribe()}
document.addEventListener('click',async e=>{if(!isCustomer||e.target.id!=='ffSupportSend')return;const t=document.getElementById('ffSupportText'),msg=t.value.trim();if(!msg)return;const u=await user(),{data:r}=await supa.from('customer_support_requests').select('id').eq('user_id',u.id).eq('status','accepted').order('created_at',{ascending:false}).limit(1).maybeSingle();if(!r)return;const{error}=await supa.from('customer_support_messages').insert({request_id:r.id,sender_type:'customer',sender_user_id:u.id,message:msg});if(error)alert(error.message);else t.value=''})
async function loadAdmin(){input().style.display='none';const u=await user();if(!u){body().innerHTML='Please login.';return}const{data:p}=await supa.from('profiles').select('is_admin').eq('id',u.id).maybeSingle();if(!p?.is_admin){body().innerHTML='Access denied.';return}const{data:rs,error}=await supa.from('customer_support_requests').select('*').in('status',['pending','accepted']).order('created_at',{ascending:false});if(error){body().innerHTML=esc(error.message);return}body().innerHTML=(rs||[]).map(r=>'<div class="ffReq"><b>'+esc(r.customer_name)+'</b> · '+esc(r.customer_phone)+'<br><small>'+esc(r.issue)+'</small><br><small>Status: '+r.status+'</small><br>'+(r.status==='pending'?'<button data-accept="'+r.id+'">Accept Chat</button>':'<button data-chat="'+r.id+'">Open Chat</button>')+'</div>').join('')||'<p>No customer has requested an agent.</p>';document.querySelectorAll('[data-accept]').forEach(x=>x.onclick=()=>accept(x.dataset.accept));document.querySelectorAll('[data-chat]').forEach(x=>x.onclick=()=>adminChat(x.dataset.chat));subscribeAdmin()}
async function accept(id){const u=await user(),{error}=await supa.from('customer_support_requests').update({status:'accepted',assigned_admin_id:u.id,updated_at:new Date().toISOString()}).eq('id',id).eq('status','pending');if(error)alert(error.message);else adminChat(id)}async function adminChat(id){body().innerHTML='<div class="ffReq"><b>Live customer chat #'+id+'</b></div><div id="ffMessages"></div>';input().style.display='flex';loadMessages(id);if(window.__ffSupportChannel)supa.removeChannel(window.__ffSupportChannel);window.__ffSupportChannel=supa.channel('support-admin-'+id).on('postgres_changes',{event:'*',schema:'public',table:'customer_support_messages',filter:'request_id=eq.'+id},()=>loadMessages(id)).subscribe();document.getElementById('ffSupportSend').onclick=async()=>{const t=document.getElementById('ffSupportText'),msg=t.value.trim();if(!msg)return;const u=await user(),{error}=await supa.from('customer_support_messages').insert({request_id:Number(id),sender_type:'admin',sender_user_id:u.id,message:msg});if(error)alert(error.message);else t.value=''}}function subscribeAdmin(){if(window.__ffSupportAdmin)supa.removeChannel(window.__ffSupportAdmin);window.__ffSupportAdmin=supa.channel('support-admin-requests').on('postgres_changes',{event:'*',schema:'public',table:'customer_support_requests'},()=>{if(document.getElementById('ffSupportPanel')?.classList.contains('open'))loadAdmin()}).subscribe()}
async function init(){await resolveRole();shell()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();