(function(){
'use strict';
const money=v=>'₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function api(){return window.FashionVariantCart}
async function variantMap(lines){const ids=[...new Set(lines.map(l=>Number(l.variant_id)).filter(Number.isInteger))];if(!ids.length)return new Map();const{data,error}=await window.supabaseClient.from('product_variants').select('id,product_id,title,size,color,sku,price_override,image_url,is_active').in('id',ids).eq('is_active',true);if(error)throw error;return new Map((data||[]).map(v=>[Number(v.id),v]))}
async function productMap(lines){const ids=[...new Set(lines.map(l=>Number(l.id)).filter(Number.isInteger))];if(!ids.length)return new Map();const{data,error}=await window.supabaseClient.from('products').select('id,name,category,price,image_url,gst_rate,is_active').in('id',ids).eq('is_active',true);if(error)throw error;return new Map((data||[]).map(p=>[Number(p.id),p]))}
function variantText(v){if(!v)return'';return [v.size&&('Size '+v.size),v.color&&('Color '+v.color),v.title&&!v.size&&!v.color&&v.title,v.sku&&('SKU '+v.sku)].filter(Boolean).join(' · ')}
function image(p,v,cls){const src=v?.image_url||p?.image_url;return src?'<img class="'+cls+'" src="'+esc(src)+'" alt="'+esc(p?.name||'Product')+'">':'<div class="fallback">Image unavailable</div>'}
async function renderCart(){const cartBox=document.getElementById('cart');if(!cartBox||!api()?.readLines)return false;const lines=api().readLines();if(!lines.some(l=>l.variant_id))return false;const[pMap,vMap]=await Promise.all([productMap(lines),variantMap(lines)]);const active=lines.filter(l=>pMap.has(Number(l.id)));if(!active.length)return false;cartBox.innerHTML=active.map(line=>{const p=pMap.get(Number(line.id)),v=vMap.get(Number(line.variant_id)),price=Number(v?.price_override??p.price??0),q=Number(line.qty),key=String(line.id)+':'+(line.variant_id??'base');return '<article class="item" data-variant-line="'+esc(key)+'">'+image(p,v,'pic')+'<div><div class="name"><a href="product.html?id='+encodeURIComponent(p.id)+'">'+esc(p.name)+'</a></div><div class="meta">'+esc(p.category||'General')+' · GST '+Number(p.gst_rate||0)+'%</div>'+(v?'<div class="meta"><strong>'+esc(variantText(v))+'</strong></div>':'')+'<div class="unit">'+money(price)+' / piece</div>'+(q>=10?'<div class="bulk">LARGER QUANTITY · '+q+' PCS</div>':'')+'<div class="controls"><div class="qty"><button data-vdec>−</button><input data-vqty type="number" min="1" max="500" value="'+q+'"><button data-vinc>+</button></div><button class="remove" data-vremove>REMOVE</button></div></div><div><div class="line-total">'+money(price*q)+'</div><div class="line-gst">before applicable GST</div></div></article>'}).join('');
cartBox.querySelectorAll('[data-variant-line]').forEach(el=>{const [pid,vidRaw]=el.dataset.variantLine.split(':'),vid=vidRaw==='base'?null:Number(vidRaw),line=active.find(x=>String(x.id)===pid&&String(x.variant_id??'base')===vidRaw);el.querySelector('[data-vinc]').onclick=()=>{api().updateLine(pid,vid,Math.min(500,line.qty+1));location.reload()};el.querySelector('[data-vdec]').onclick=()=>{api().updateLine(pid,vid,line.qty-1);location.reload()};el.querySelector('[data-vqty]').onchange=e=>{api().updateLine(pid,vid,Math.max(1,Math.min(500,Math.floor(Number(e.target.value)||1))));location.reload()};el.querySelector('[data-vremove]').onclick=()=>{api().removeLine(pid,vid);location.reload()}});return true}
async function renderCheckout(){const box=document.getElementById('itemsBox');if(!box||!api()?.readLines)return false;const lines=api().readLines();if(!lines.some(l=>l.variant_id))return false;const[pMap,vMap]=await Promise.all([productMap(lines),variantMap(lines)]);const active=lines.filter(l=>pMap.has(Number(l.id)));if(!active.length)return false;box.className='';box.innerHTML=active.map(line=>{const p=pMap.get(Number(line.id)),v=vMap.get(Number(line.variant_id)),price=Number(v?.price_override??p.price??0),q=Number(line.qty);return '<div class="item">'+image(p,v,'thumb')+'<div><div class="name">'+esc(p.name)+'</div><div class="meta">'+esc(p.category||'General')+(v?' · <strong>'+esc(variantText(v))+'</strong>':'')+'</div><div class="price">'+money(price)+' <span style="font-size:11px;color:#697386;font-weight:600">/ piece</span></div>'+(q>=10?'<div class="bulk-note">Larger quantity · '+q+' pieces</div>':'')+'<div class="meta" style="margin-top:10px">Quantity: '+q+'</div></div><div class="line-total">'+money(price*q)+'</div></div>'}).join('');return true}
async function start(){try{if(location.pathname.endsWith('cart.html'))await renderCart();if(location.pathname.endsWith('checkout.html'))await renderCheckout()}catch(e){console.error('Variant cart UI enhancement failed',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(start,250),{once:true});else setTimeout(start,250);
})();
