'use strict';
const BACKEND_URL=window.FF_API_ORIGIN||'',CART_KEY='fashion_fussion_cart',CHECKOUT_KEY='fashion_fussion_checkout_key';
let session=null,products=[],addresses=[],address=null,quote=null,appliedCoupon='',appliedGift='',refreshSeq=0;
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=v=>'₹'+Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:0,maximumFractionDigits:2});
function paymentMethod(){return document.querySelector('input[name="paymentMethod"]:checked')?.value||'prepaid'}
function loadCart(){try{return JSON.parse(localStorage.getItem(CART_KEY)||'{}')||{}}catch{return{}}}
let cart=loadCart();
function items(){return Object.entries(cart).map(([id,qty])=>({id:Number(id),qty:Number(qty)})).filter(x=>Number.isInteger(x.id)&&Number.isInteger(x.qty)&&x.qty>0&&x.qty<=500)}
function newCheckoutKey(){const id=globalThis.crypto?.randomUUID?.()||('ff_'+Date.now()+'_'+Math.random().toString(36).slice(2)+Math.random().toString(36).slice(2));sessionStorage.setItem(CHECKOUT_KEY,id);return id}
function checkoutKey(){return sessionStorage.getItem(CHECKOUT_KEY)||newCheckoutKey()}
function clearCompletedCheckout(){localStorage.removeItem(CART_KEY);sessionStorage.removeItem(CHECKOUT_KEY)}
function setStatus(message,type='error'){const el=document.getElementById('checkoutStatus');el.textContent=message||'';el.className='status'+(message?' show '+type:'')}
function saveCart(){localStorage.setItem(CART_KEY,JSON.stringify(cart));quote=null;renderItems();refreshQuote()}
function selectAddress(id){const next=addresses.find(a=>String(a.id)===String(id));if(!next)return;address=next;newCheckoutKey();renderAddress();syncButton()}
function renderAddress(){const b=document.getElementById('addressBox'),state=document.getElementById('addressState');if(!addresses.length){address=null;state.textContent='Address required';b.className='empty';b.innerHTML='No saved delivery address. <a class="change" href="account.html?return=checkout#addresses">Add an address</a>';syncButton();return}if(!address)address=addresses.find(a=>a.is_default)||addresses[0];state.textContent='✓ Selected';b.className='address-wrap';b.innerHTML='<div class="address-tools"><p>Choose where this order should be delivered.</p><a class="change" href="account.html?return=checkout#addresses">Manage addresses</a></div><div class="address-list">'+addresses.map(a=>{const selected=String(a.id)===String(address.id);return '<label class="address-option '+(selected?'selected':'')+'"><input type="radio" name="deliveryAddress" value="'+a.id+'" '+(selected?'checked':'')+'><div><div class="address-name">'+esc(a.full_name)+'</div><div class="address-text">'+esc(a.address_line1)+(a.address_line2?', '+esc(a.address_line2):'')+'<br>'+esc(a.city)+', '+esc(a.state)+' '+esc(a.postal_code)+' · '+esc(a.phone)+'</div></div><span class="address-label '+(a.is_default?'default':'')+'">'+esc(a.is_default?'DEFAULT':(a.label||'ADDRESS'))+'</span></label>'}).join('')+'</div>';b.querySelectorAll('input[name="deliveryAddress"]').forEach(r=>r.addEventListener('change',()=>selectAddress(r.value)));syncButton()}
function imageMarkup(p){return p.image_url?'<img class="thumb" data-product-image src="'+esc(p.image_url)+'" alt="'+esc(p.name)+'" loading="lazy">':'<div class="thumb-fallback">Product image<br>unavailable</div>'}
function replaceBrokenImage(img){if(!img?.isConnected)return;const fallback=document.createElement('div');fallback.className='thumb-fallback';fallback.append(document.createTextNode('Product image'),document.createElement('br'),document.createTextNode('unavailable'));img.replaceWith(fallback)}
function renderItems(){const box=document.getElementById('itemsBox');if(!products.length){box.className='empty';box.textContent='Your cart is empty.';return}box.className='';box.innerHTML=products.map(p=>{const q=Number(cart[p.id]||0),bulk=q>=10?'<div class="bulk-note">Business / bulk quantity</div>':'';return '<div class="item">'+imageMarkup(p)+'<div><div class="name">'+esc(p.name)+'</div><div class="meta">'+esc(p.category||'General')+'</div><div class="price">'+money(p.price)+' <span class="meta">/ unit</span></div><div class="qty"><button type="button" aria-label="Decrease quantity" data-dec="'+p.id+'">−</button><span>'+q+'</span><button type="button" aria-label="Increase quantity" data-inc="'+p.id+'">+</button></div>'+bulk+'</div><div class="line-total">'+money(Number(p.price)*q)+'</div></div>'}).join('');box.querySelectorAll('[data-product-image]').forEach(img=>img.addEventListener('error',()=>replaceBrokenImage(img),{once:true}));box.querySelectorAll('[data-inc]').forEach(b=>b.addEventListener('click',()=>{cart[b.dataset.inc]=Math.min(500,Number(cart[b.dataset.inc]||0)+1);newCheckoutKey();saveCart()}));box.querySelectorAll('[data-dec]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.dec,n=Number(cart[id]||0)-1;if(n<=0){delete cart[id];products=products.filter(p=>cart[p.id])}else cart[id]=n;newCheckoutKey();saveCart()}))}
async function api(path,body){const{data:{session:fresh},error:sessionError}=await window.supabaseClient.auth.getSession();if(sessionError||!fresh?.access_token)throw new Error('Your login session has expired. Please log in again.');session=fresh;const r=await fetch(BACKEND_URL+path,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+fresh.access_token},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||'Request failed');e.data=d;e.status=r.status;throw e}return d}
async function getQuote(){return api('/api/quote-order',{items:items(),coupon_code:appliedCoupon,gift_card_code:appliedGift,payment_method:paymentMethod()})}
function renderPrice(){const p=quote?.pricing,box=document.getElementById('priceBox'),benefit=document.getElementById('benefitBox');if(!p){box.innerHTML='<div class="price-row"><span>Calculating...</span></div>';benefit.innerHTML='';return}const subtotal=Number(p.subtotal||0),delivery=Number(p.delivery||0),remaining=Math.max(0,299-subtotal);benefit.innerHTML=delivery===0?'<div class="benefit">✓ ₹299 delivery benefit unlocked for this order.</div>':'<div class="benefit">Add '+money(remaining)+' more in product value to unlock the ₹299 delivery benefit.</div>';let h='<div class="price-row"><span>Product subtotal</span><span>'+money(p.subtotal)+'</span></div><div class="price-row"><span>GST</span><span>'+money(p.gst)+'</span></div><div class="price-row"><span>Delivery</span><span>'+(delivery===0?'<span class="saving">FREE</span>':money(delivery))+'</span></div>';if(Number(p.coupon_discount)>0)h+='<div class="price-row saving"><span>Coupon discount</span><span>− '+money(p.coupon_discount)+'</span></div>';if(Number(p.gift_card_discount)>0)h+='<div class="price-row saving"><span>Gift card</span><span>− '+money(p.gift_card_discount)+'</span></div>';h+='<div class="price-row total"><span>Total payable</span><span>'+money(p.total)+'</span></div>';if(delivery>0)h+='<div class="delivery-note">₹49 delivery charge applies below ₹299 product subtotal and is non-refundable as per the store delivery policy.</div>';box.innerHTML=h}
function syncButton(){const btn=document.getElementById('continueBtn');btn.textContent=paymentMethod()==='cod'?'PLACE ORDER • COD':'PAY SECURELY';btn.disabled=!quote||!address||!products.length}
async function refreshQuote(){const seq=++refreshSeq;document.getElementById('continueBtn').disabled=true;setStatus('');try{const q=await getQuote();if(seq!==refreshSeq)return;quote=q;renderPrice();syncButton()}catch(e){if(seq!==refreshSeq)return;quote=null;renderPrice();setStatus(e.message);syncButton()}}
async function apply(kind){const input=document.getElementById(kind==='coupon'?'couponCode':'giftCode'),msg=document.getElementById(kind==='coupon'?'couponMsg':'giftMsg'),val=input.value.trim().toUpperCase();if(kind==='coupon')appliedCoupon=val;else appliedGift=val;newCheckoutKey();msg.textContent='Checking...';msg.classList.remove('error');try{quote=await getQuote();renderPrice();msg.textContent=val?'Applied successfully':'Removed';syncButton()}catch(e){if(kind==='coupon')appliedCoupon='';else appliedGift='';msg.textContent=e.message;msg.classList.add('error');await refreshQuote()}}
async function reconcile(storeOrderId){for(let attempt=0;attempt<3;attempt++){await new Promise(r=>setTimeout(r,1200*(attempt+1)));try{const d=await api('/api/reconcile-payment',{store_order_id:storeOrderId});if(d.reconciled&&d.status==='paid')return d}catch(e){console.error('Reconcile attempt failed',e)}}return null}
function finish(storeOrderId){clearCompletedCheckout();location.href='order-confirmation.html?id='+encodeURIComponent(storeOrderId)}
async function handleRazorpay(d,body,btn){const rz=new Razorpay({key:d.key_id,amount:d.order.amount,currency:d.order.currency||'INR',name:'Fashion Fussion',description:'Secure order payment',order_id:d.order.id,prefill:{name:body.customer_name,email:session.user.email||'',contact:body.customer_phone},handler:async pr=>{btn.disabled=true;btn.textContent='CONFIRMING PAYMENT...';setStatus('Payment received. Confirming your order…','ok');try{const vd=await api('/api/verify-payment',{order_id:d.order.id,razorpay_payment_id:pr.razorpay_payment_id,razorpay_order_id:pr.razorpay_order_id,razorpay_signature:pr.razorpay_signature});if(vd.verified){finish(vd.store_order_id||d.store_order_id);return}}catch(e){if(e.data?.captured||e.data?.recoverable){setStatus('Payment captured. We are reconciling your order automatically. Do not pay again.','ok');const recovered=await reconcile(d.store_order_id);if(recovered){finish(recovered.store_order_id||d.store_order_id);return}location.href='account.html#orders';return}setStatus(e.message||'Payment verification failed. Please check My Orders before retrying.')}syncButton()},modal:{ondismiss:()=>{setStatus('Payment window closed. No new payment was recorded.');syncButton()}}});rz.on('payment.failed',response=>{setStatus(response?.error?.description||'Payment failed. You can try again or choose COD.');syncButton()});rz.open()}
async function pay(){const btn=document.getElementById('continueBtn');if(!quote||!address)return;btn.disabled=true;btn.textContent='PREPARING ORDER...';setStatus('');try{const{data:profile,error}=await window.supabaseClient.from('profiles').select('full_name,phone').eq('id',session.user.id).maybeSingle();if(error)throw error;const body={checkout_key:checkoutKey(),items:items(),customer_name:String(profile?.full_name||address?.full_name||'').trim(),customer_phone:String(profile?.phone||address?.phone||'').trim(),shipping_address:{id:address.id},coupon_code:appliedCoupon,gift_card_code:appliedGift,payment_method:paymentMethod()};const d=await api('/api/create-order',body);if(d.completed){setStatus(d.payment_method==='cod'?'Cash on Delivery order placed successfully.':'Order placed successfully.','ok');finish(d.store_order_id);return}if(!d.order?.id||!d.key_id)throw new Error('Payment order could not be prepared.');await handleRazorpay(d,body,btn)}catch(e){console.error(e);if(e.data?.retry_with_new_checkout){newCheckoutKey();setStatus((e.message||'Previous checkout session expired.')+' Please try again.');syncButton();return}setStatus(e.message||'Unable to start checkout');syncButton()}}
async function init(){const{data:{session:s},error}=await window.supabaseClient.auth.getSession();if(error)throw error;session=s;if(!session){location.href='login.html?redirect=checkout';return}const ci=items();if(!ci.length){document.getElementById('itemsBox').textContent='Your cart is empty.';return}const ids=ci.map(x=>x.id);const[{data:ps,error:pe},{data:as,error:ae}]=await Promise.all([window.supabaseClient.from('products').select('id,name,category,price,image_url,is_active').in('id',ids).eq('is_active',true),window.supabaseClient.from('customer_addresses').select('id,label,full_name,phone,address_line1,address_line2,city,state,postal_code,country,is_default,created_at').eq('user_id',session.user.id).order('is_default',{ascending:false}).order('created_at',{ascending:false})]);if(pe)throw pe;if(ae)throw ae;products=(ps||[]).filter(p=>cart[p.id]);addresses=as||[];address=addresses.find(a=>a.is_default)||addresses[0]||null;renderAddress();renderItems();await refreshQuote()}
document.getElementById('applyCoupon').addEventListener('click',()=>apply('coupon'));
document.getElementById('applyGift').addEventListener('click',()=>apply('gift'));
document.getElementById('continueBtn').addEventListener('click',pay);
document.querySelectorAll('input[name="paymentMethod"]').forEach(r=>r.addEventListener('change',()=>{newCheckoutKey();refreshQuote()}));
init().catch(e=>{console.error(e);setStatus('Checkout could not be loaded. '+(e.message||''))});
