'use strict';
const $=id=>document.getElementById(id),money=v=>'₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2}),esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let user=null,profile=null,products=[];
function message(text){const e=$('creatorMessage');e.textContent=text;e.hidden=!text}
function creatorUrl(p,code){return location.origin+location.pathname.replace(/creators\.html$/,'product.html')+'?id='+encodeURIComponent(p)+'&ref='+encodeURIComponent(code)}
async function dashboard(){const{data,error}=await supabaseClient.rpc('get_creator_dashboard');if(error)throw error;const d=data||{};profile=d.profile||null;$('creatorStatus').textContent=profile?.status?profile.status.toUpperCase():'NOT APPLIED';$('creatorOrders').textContent=Number(d.orders||0);$('creatorCommission').textContent=money(d.estimated_commission||0);if(profile){$('displayName').value=profile.display_name||'';$('handle').value=profile.handle||'';$('creatorFormTitle').textContent='Creator profile';if(profile.status==='approved')$('linkBuilder').hidden=false}return d}
async function loadProfileDetails(){if(!user)return;const{data}=await supabaseClient.from('creator_profiles').select('display_name,handle,bio,social_handle,status,commission_rate').eq('user_id',user.id).maybeSingle();if(data){$('displayName').value=data.display_name||'';$('handle').value=data.handle||'';$('bio').value=data.bio||'';$('socialHandle').value=data.social_handle||'';profile=data}}
async function loadProducts(){const{data,error}=await supabaseClient.from('products').select('id,name,price').eq('is_active',true).order('id',{ascending:false});if(error)throw error;products=data||[];$('productSelect').innerHTML=products.map(p=>'<option value="'+p.id+'">'+esc(p.name)+' · '+money(p.price)+'</option>').join('')}
async function loadLinks(){if(!user)return;const{data,error}=await supabaseClient.from('creator_links').select('id,product_id,code,active,created_at').eq('creator_id',user.id).order('created_at',{ascending:false});if(error)throw error;const box=$('creatorLinks');box.innerHTML=(data||[]).length?(data||[]).map(link=>{const p=products.find(x=>Number(x.id)===Number(link.product_id)),url=creatorUrl(link.product_id,link.code);return '<div class="link-row"><div><b>'+esc(p?.name||('Product #'+link.product_id))+'</b><div class="muted">Code '+esc(link.code)+(link.active?' · Active':' · Paused')+'</div></div><button class="btn secondary" data-copy="'+esc(url)+'">Copy link</button></div>'}).join(''):'<p class="muted">No referral links yet.</p>';box.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.dataset.copy);b.textContent='Copied'})}
async function saveProfile(e){e.preventDefault();const row={user_id:user.id,display_name:$('displayName').value.trim(),handle:$('handle').value.trim().toLowerCase(),bio:$('bio').value.trim()||null,social_handle:$('socialHandle').value.trim()||null,updated_at:new Date().toISOString()};message('Saving…');const{data:existing}=await supabaseClient.from('creator_profiles').select('user_id').eq('user_id',user.id).maybeSingle();let result;if(existing)result=await supabaseClient.from('creator_profiles').update({display_name:row.display_name,handle:row.handle,bio:row.bio,social_handle:row.social_handle,updated_at:row.updated_at}).eq('user_id',user.id);else result=await supabaseClient.from('creator_profiles').insert(row);if(result.error){message(result.error.message);return}message(existing?'Creator profile updated.':'Application submitted for review.');await loadProfileDetails();await dashboard()}
async function createLink(e){e.preventDefault();const productId=Number($('productSelect').value);const{error}=await supabaseClient.from('creator_links').insert({creator_id:user.id,product_id:productId});if(error&&error.code!=='23505'){message(error.message);return}message(error?.code==='23505'?'This product already has your referral link.':'Referral link created.');await loadLinks()}
async function init(){if(window.ffSupabaseReady)await window.ffSupabaseReady;const{data:{user:u}}=await supabaseClient.auth.getUser();user=u;if(!user)return;$('creatorGate').hidden=true;$('creatorWorkspace').hidden=false;await Promise.all([loadProfileDetails(),loadProducts()]);await dashboard();if(profile?.status==='approved')await loadLinks();$('creatorForm').addEventListener('submit',saveProfile);$('linkForm').addEventListener('submit',createLink)}
init().catch(e=>{console.error(e);message('Creator dashboard could not be loaded. '+(e.message||''))});
