'use strict';
const $=id=>document.getElementById(id),money=v=>'₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2}),esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c])),fmt=d=>d?new Date(d).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}):'—';
let user=null,profile=null,products=[];
function message(text){const e=$('creatorMessage');if(!e)return;e.textContent=text;e.hidden=!text}
function slugify(v){return String(v||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,65)}
function creatorUrl(p,code){return location.origin+location.pathname.replace(/creators\.html$/,'product.html')+'?id='+encodeURIComponent(p)+'&ref='+encodeURIComponent(code)}
function statusLabel(v){return String(v||'pending').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function renderLedger(entries){const box=$('creatorLedgerRows');if(!box)return;box.innerHTML=(entries||[]).length?(entries||[]).map(e=>'<div class="ledger-row"><div><b>'+esc(e.product_name||('Product #'+e.product_id))+'</b><div class="muted">Order #'+esc(e.order_id)+' · '+money(e.attributed_value)+' attributed · '+Number(e.rate||0)+'%</div><small class="muted">'+(e.status==='pending'&&e.eligible_at?'Available after '+fmt(e.eligible_at):statusLabel(e.status))+'</small></div><div class="ledger-amount"><strong>'+money(e.commission)+'</strong><span class="ledger-status status-'+esc(e.status)+'">'+esc(statusLabel(e.status))+'</span></div></div>').join(''):'<p class="muted">No attributed commission entries yet.</p>'}
async function dashboard(){const{data,error}=await supabaseClient.rpc('get_creator_dashboard');if(error)throw error;const d=data||{};profile=d.profile||null;$('creatorStatus').textContent=profile?.status?profile.status.toUpperCase():'NOT APPLIED';$('creatorOrders').textContent=Number(d.orders||0);$('creatorPending').textContent=money(Number(d.pending_commission||0)+Number(d.on_hold_commission||0));$('creatorAvailable').textContent=money(d.available_commission||0);$('creatorPaid').textContent=money(d.paid_commission||0);renderLedger(d.entries||[]);if(profile){$('displayName').value=profile.display_name||'';$('handle').value=profile.handle||'';$('creatorFormTitle').textContent='Creator profile';if(profile.status==='approved'){$('fashionFinds').hidden=false;$('linkBuilder').hidden=false;$('lookBuilder').hidden=false}}return d}
async function loadProfileDetails(){if(!user)return;const{data}=await supabaseClient.from('creator_profiles').select('display_name,handle,bio,social_handle,status,commission_rate').eq('user_id',user.id).maybeSingle();if(data){$('displayName').value=data.display_name||'';$('handle').value=data.handle||'';$('bio').value=data.bio||'';$('socialHandle').value=data.social_handle||'';profile=data}}
async function loadProducts(){let data,error;if(profile?.status==='approved'){({data,error}=await supabaseClient.rpc('get_creator_matchable_products',{p_limit:200}))}else{({data,error}=await supabaseClient.from('products').select('id,name,price').eq('is_active',true).order('id',{ascending:false}).limit(200))}if(error)throw error;products=data||[];const options=products.map(p=>'<option value="'+p.id+'">'+esc(p.name)+' · '+money(p.price)+'</option>').join('');$('productSelect').innerHTML=options;$('lookProducts').innerHTML=options;renderFashionFinds()}
function renderFashionFinds(){const box=$('fashionFindsGrid');if(!box)return;box.innerHTML=products.length?products.map(p=>'<article class="product"><img src="'+esc(p.image||'assets/placeholder.svg')+'" alt=""><div class="body"><b>'+esc(p.name)+'</b><div class="muted">'+esc(p.category||'Fashion')+(p.verified_seller?' · Verified seller':'')+'</div><div class="price">'+money(p.price)+'</div><div class="find-signals">'+(p.value_signal&&p.value_signal!=='standard'?'<span>'+esc(statusLabel(p.value_signal))+'</span>':'')+(p.visibility_boost_active?'<span>LaunchPad</span>':'')+'</div><button class="btn creator-find-link" data-find-link="'+p.id+'">Create link</button></div></article>').join(''):'<p class="muted">No creator-ready products are available yet.</p>';box.querySelectorAll('[data-find-link]').forEach(b=>b.onclick=async()=>{const productId=Number(b.dataset.findLink);const{error}=await supabaseClient.from('creator_links').insert({creator_id:user.id,product_id:productId});if(error&&error.code!=='23505'){message(error.message);return}message(error?.code==='23505'?'You already have a referral link for this product.':'Referral link created from Fashion Finds.');$('productSelect').value=String(productId);await loadLinks();document.getElementById('linkBuilder')?.scrollIntoView({behavior:'smooth',block:'start'})})}
async function loadLinks(){if(!user)return;const{data,error}=await supabaseClient.from('creator_links').select('id,product_id,code,active,created_at').eq('creator_id',user.id).order('created_at',{ascending:false});if(error)throw error;const box=$('creatorLinks');box.innerHTML=(data||[]).length?(data||[]).map(link=>{const p=products.find(x=>Number(x.id)===Number(link.product_id)),url=creatorUrl(link.product_id,link.code);return '<div class="link-row"><div><b>'+esc(p?.name||('Product #'+link.product_id))+'</b><div class="muted">Code '+esc(link.code)+(link.active?' · Active':' · Paused')+'</div></div><button class="btn secondary" data-copy="'+esc(url)+'">Copy link</button></div>'}).join(''):'<p class="muted">No referral links yet.</p>';box.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.dataset.copy);b.textContent='Copied'})}
async function loadLooks(){if(!user)return;const{data,error}=await supabaseClient.from('shop_looks').select('id,title,slug,status,created_at').eq('creator_id',user.id).order('created_at',{ascending:false});if(error)throw error;const box=$('creatorLooks');box.innerHTML=(data||[]).length?(data||[]).map(l=>'<div class="link-row"><div><b>'+esc(l.title)+'</b><div class="muted">'+esc(l.status)+'</div></div><a class="btn secondary" href="shop-look.html?slug='+encodeURIComponent(l.slug)+'">Open look</a></div>').join(''):'<p class="muted">No published looks yet.</p>'}
async function saveProfile(e){e.preventDefault();const row={user_id:user.id,display_name:$('displayName').value.trim(),handle:$('handle').value.trim().toLowerCase(),bio:$('bio').value.trim()||null,social_handle:$('socialHandle').value.trim()||null,updated_at:new Date().toISOString()};message('Saving…');const{data:existing}=await supabaseClient.from('creator_profiles').select('user_id').eq('user_id',user.id).maybeSingle();let result;if(existing)result=await supabaseClient.from('creator_profiles').update({display_name:row.display_name,handle:row.handle,bio:row.bio,social_handle:row.social_handle,updated_at:row.updated_at}).eq('user_id',user.id);else result=await supabaseClient.from('creator_profiles').insert(row);if(result.error){message(result.error.message);return}message(existing?'Creator profile updated.':'Application submitted for review.');await loadProfileDetails();await dashboard()}
async function createLink(e){e.preventDefault();const productId=Number($('productSelect').value);const{error}=await supabaseClient.from('creator_links').insert({creator_id:user.id,product_id:productId});if(error&&error.code!=='23505'){message(error.message);return}message(error?.code==='23505'?'This product already has your referral link.':'Referral link created.');await loadLinks()}
async function createLook(e){e.preventDefault();const selected=[...$('lookProducts').selectedOptions].map(o=>Number(o.value)).filter(Boolean);if(selected.length<2){message('Choose at least two products for a shoppable look.');return}const title=$('lookTitle').value.trim(),slug=(slugify(title)+'-'+Date.now().toString(36)).slice(0,80);const{data:look,error}=await supabaseClient.from('shop_looks').insert({creator_id:user.id,title,slug,status:'published'}).select('id,slug').single();if(error){message(error.message);return}const rows=selected.map((product_id,i)=>({look_id:look.id,product_id,sort_order:i}));const{error:itemError}=await supabaseClient.from('shop_look_items').insert(rows);if(itemError){await supabaseClient.from('shop_looks').update({status:'archived'}).eq('id',look.id);message('Look products could not be saved. '+itemError.message);return}$('lookTitle').value='';[...$('lookProducts').options].forEach(o=>o.selected=false);message('Shop the Look published.');await loadLooks()}
async function init(){if(window.ffSupabaseReady)await window.ffSupabaseReady;const{data:{user:u}}=await supabaseClient.auth.getUser();user=u;if(!user)return;$('creatorGate').hidden=true;$('creatorWorkspace').hidden=false;await loadProfileDetails();await dashboard();await loadProducts();if(profile?.status==='approved')await Promise.all([loadLinks(),loadLooks()]);$('creatorForm').addEventListener('submit',saveProfile);$('linkForm').addEventListener('submit',createLink);$('lookForm').addEventListener('submit',createLook)}
init().catch(e=>{console.error(e);message('Creator dashboard could not be loaded. '+(e.message||''))});
