'use strict';
const form=document.getElementById('signupForm'),button=document.getElementById('signupButton'),message=document.getElementById('message'),businessFields=document.getElementById('businessSignupFields');
const params=new URLSearchParams(location.search),redirectRaw=params.get('redirect');
const GSTIN=/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/;
const safe=(e,fallback)=>window.ffCustomerMessage?window.ffCustomerMessage(e,fallback):fallback;
function show(text,type){message.textContent=text;message.className='message '+type;message.hidden=false}
function safeReturnPath(){if(!redirectRaw)return null;const aliases={checkout:'checkout.html',account:'account.html',orders:'account.html#orders'};const candidate=aliases[redirectRaw]||redirectRaw;try{const u=new URL(candidate,location.href);if(u.origin!==location.origin)return null;const page=u.pathname.split('/').pop();const allowed=new Set(['checkout.html','account.html','cart.html','wishlist.html','notifications.html','coupons.html','gift-cards.html','order-details.html','order-confirmation.html','quote-checkout.html']);if(!allowed.has(page))return null;return page+u.search+u.hash}catch{return null}}
function selectedAccountType(){return document.querySelector('input[name="accountType"]:checked')?.value==='business'?'business':'retail'}
function syncAccountType(){const business=selectedAccountType()==='business';businessFields.hidden=!business;['businessName','businessBilling'].forEach(id=>document.getElementById(id).required=business);button.textContent=business?'Create Business Account':'Create Account'}
function loginHref(){const target=safeReturnPath(),p=new URLSearchParams();if(target)p.set('redirect',target);return 'login.html'+(p.toString()?'?'+p.toString():'')}
const loginLink=document.querySelector('.links a[href="login.html"]');if(loginLink)loginLink.href=loginHref();
const requested=params.get('account');if(requested==='business'){const radio=document.querySelector('input[name="accountType"][value="business"]');if(radio)radio.checked=true}document.querySelectorAll('input[name="accountType"]').forEach(r=>r.addEventListener('change',syncAccountType));syncAccountType();
form.addEventListener('submit',async e=>{e.preventDefault();const accountType=selectedAccountType(),fullName=document.getElementById('fullName').value.trim(),rawPhone=document.getElementById('phone').value.trim(),email=document.getElementById('email').value.trim(),password=document.getElementById('password').value,confirm=document.getElementById('confirmPassword').value;const phone=rawPhone.replace(/[^0-9+]/g,'');let businessName='',gstin='',businessBilling='';if(fullName.length<2){show('Enter your full name.','error');return}if(!/^\+?[0-9]{10,15}$/.test(phone)){show('Enter a valid mobile number.','error');return}if(accountType==='business'){businessName=document.getElementById('businessName').value.trim();gstin=document.getElementById('businessGstin').value.trim().toUpperCase();businessBilling=document.getElementById('businessBilling').value.trim();if(businessName.length<2){show('Enter your business or legal name.','error');return}if(gstin&&!GSTIN.test(gstin)){show('GSTIN format is invalid.','error');return}if(businessBilling.length<5){show('Enter your business billing address.','error');return}}if(password.length<10){show('Password must be at least 10 characters.','error');return}if(password!==confirm){show('Passwords do not match.','error');return}button.disabled=true;button.textContent='Creating account…';message.hidden=true;message.textContent='';message.className='message';try{const target=safeReturnPath(),afterConfirm=target||(accountType==='business'?'account.html#business':'account.html'),emailRedirectTo=new URL(afterConfirm,location.href).href;const metadata={full_name:fullName,phone,account_type:accountType};if(accountType==='business'){metadata.business_name=businessName;metadata.business_gstin=gstin||null;metadata.business_billing_address=businessBilling}const{data,error}=await window.supabaseClient.auth.signUp({email,password,options:{emailRedirectTo,data:metadata}});if(error)throw error;if(!data?.user)throw new Error('Account could not be created.');if(!data.session){show(accountType==='business'?'Business account created. Confirm your email, then sign in to continue business account setup.':'Account created. Check your email and confirm your account before signing in.','success');form.reset();const defaultRetail=document.querySelector('input[name="accountType"][value="retail"]');if(defaultRetail)defaultRetail.checked=true;syncAccountType()}else{show(accountType==='business'?'Business account created. Opening your Business & Bulk account…':'Account created successfully. Redirecting…','success');setTimeout(()=>location.href=target||(accountType==='business'?'account.html#business':'account.html'),500)}}catch(err){console.error(err);show(safe(err,'Unable to create account. Please check your details and try again.'),'error')}finally{button.disabled=false;syncAccountType()}});