document.addEventListener('error',event=>{const target=event.target;if(!(target instanceof HTMLImageElement))return;const cls=target.dataset.cspFallbackClass;if(!cls)return;const fallback=document.createElement('div');fallback.className=cls;fallback.textContent=target.dataset.cspFallbackText||'Image unavailable';target.replaceWith(fallback)},true);
'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c])),money=v=>'₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2});let currentUser=null,ordersCache=[],addressesCache=[],editingAddressId=null;
function statusInfo(o){const s=String(o.status||'').toLowerCase(),f=String(o.fulfillment_status||'ordered').toLowerCase();if(s==='refunded')return['Refunded','good'];if(s==='refund_failed')return['Refund failed','bad'];if(['refund_pending','refund_initiated'].includes(s))return['Refund in progress','warn'];if(['cancelled','cod_cancelled'].includes(s)||f==='cancelled')return['Cancelled','bad'];if(f==='delivered')return['Delivered','good'];if(f==='out_for_delivery')return['Out for delivery','warn'];if(f==='shipped')return['Shipped','warn'];if(f==='packed')return['Packed',''];return['Order placed','']}
function fmtDate(v){const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}
function image(x){return x.image_url?'<img src="'+esc(x.image_url)+'" alt="'+esc(x.name||'Product')+'" data-csp-fallback-class="fallback" data-csp-fallback-text="Image unavailable">':'<div class="fallback">Image unavailable</div>'}
function canCancel(o){const s=String(o.status||'').toLowerCase(),f=String(o.fulfillment_status||'ordered').toLowerCase();if(!['ordered','packed'].includes(f))return false;if(o.payment_method==='cod')return s==='cod_pending';return o.payment_method==='prepaid'&&s==='paid'&&Number(o.gift_card_discount||0)===0}
function orderCard(o){const items=Array.isArray(o.items)?o.items:[],st=statusInfo(o),display=o.display_order_id||o.id,itemHtml=(items.slice(0,3).map(x=>'<div class="itemrow">'+image(x)+'<div><div class="pname">'+esc(x.name||'Product')+'</div><div class="muted">Qty '+esc(x.qty||x.quantity||1)+(x.category?' · '+esc(x.category):'')+(x.gst_rate!=null?' · GST '+esc(x.gst_rate)+'%':'')+'</div></div></div>').join('')||'<div class="muted">Order item details unavailable.</div>')+(items.length>3?'<div class="muted" data-csp-style="csp-html-account-2">+'+(items.length-3)+' more item(s)</div>':'');return '<article class="order"><div class="order-head"><div class="order-meta"><div><div class="meta-label">Order</div><div class="meta-value">#'+esc(display)+'</div></div><div><div class="meta-label">Placed</div><div class="meta-value">'+esc(fmtDate(o.created_at))+'</div></div><div><div class="meta-label">Payment</div><div class="meta-value">'+esc(o.payment_method==='cod'?'Cash on Delivery':'Online payment')+'</div></div></div><span class="badge '+st[1]+'">'+esc(st[0])+'</span></div><div class="order-body"><div>'+itemHtml+'</div><div class="order-total">'+money(o.total_amount)+'</div></div><div class="order-actions"><a class="btn primary" href="order-details.html?id='+encodeURIComponent(o.id)+'">View details</a><a class="btn" href="order-details.html?id='+encodeURIComponent(o.id)+'#tracking">Track order</a>'+(canCancel(o)?'<a class="btn danger" href="order-details.html?id='+encodeURIComponent(o.id)+'#cancel">Cancel order</a>':'')+'<a class="btn" href="order-details.html?id='+encodeURIComponent(o.id)+'#help">Need help</a></div></article>'}
function renderOrders(){const box=$('ordersList');if(!ordersCache.length){box.innerHTML='<div class="empty">You have not placed any orders yet.<br><br><a class="btn primary" href="index.html">Continue shopping</a></div>';return}box.innerHTML=ordersCache.map(orderCard).join('');renderRefunds()}
function renderRefunds(){const list=ordersCache.filter(o=>['refund_pending','refund_initiated','refund_failed','refunded'].includes(String(o.status||'').toLowerCase())),box=$('refundsList');if(!list.length){box.innerHTML='<div class="empty">No refund activity yet.</div>';return}box.innerHTML=list.map(o=>orderCard(o)).join('')}
async function loadOrders(){const box=$('ordersList');box.innerHTML='<div class="empty">Loading orders…</div>';const{data,error}=await supabaseClient.from('orders').select('id,display_order_id,total_amount,currency,status,payment_method,fulfillment_status,created_at,items,gift_card_discount').eq('user_id',currentUser.id).order('created_at',{ascending:false});if(error)throw error;ordersCache=data||[];renderOrders()}
async function loadProfile(){const[profileResult,addressResult]=await Promise.all([supabaseClient.from('profiles').select('id,full_name,phone').eq('id',currentUser.id).maybeSingle(),supabaseClient.from('customer_addresses').select('full_name,phone').eq('user_id',currentUser.id).order('is_default',{ascending:false}).order('created_at',{ascending:false}).limit(1).maybeSingle()]);if(profileResult.error)throw profileResult.error;if(addressResult.error)console.warn('Address identity fallback unavailable',addressResult.error);const data=profileResult.data||{},fallback=addressResult.data||{},meta=currentUser.user_metadata||{},full=String(data.full_name||meta.full_name||meta.name||fallback.full_name||'').trim(),phone=String(data.phone||meta.phone||currentUser.phone||fallback.phone||'').trim();localStorage.removeItem('customer_name');localStorage.removeItem('customer_phone');$('fullName').value=full;$('phone').value=phone;$('email').value=currentUser.email||'';syncName();lockProfile()}
function syncName(){const n=$('fullName').value.trim()||'Customer';$('miniName').textContent=n;$('avatar').textContent=(n[0]||'U').toUpperCase()}
function lockProfile(){$('fullName').readOnly=true;$('phone').readOnly=true;$('saveProfile').hidden=true;$('editProfile').hidden=false}function unlockProfile(){$('fullName').readOnly=false;$('phone').readOnly=false;$('saveProfile').hidden=false;$('editProfile').hidden=true;$('fullName').focus()}
function showStatus(msg,type='success'){$('profileStatus').innerHTML='<div class="alert '+type+'">'+esc(msg)+'</div>';setTimeout(()=>{$('profileStatus').innerHTML=''},3500)}
async function saveProfile(e){e.preventDefault();const full=$('fullName').value.trim(),phone=$('phone').value.trim();if(!full||!phone){showStatus('Please enter your full name and phone number.','error');return}const b=$('saveProfile');b.disabled=true;b.textContent='Saving…';try{const{data,error}=await supabaseClient.from('profiles').upsert({id:currentUser.id,full_name:full,phone,updated_at:new Date().toISOString()},{onConflict:'id'}).select('id,full_name,phone').single();if(error)throw error;$('fullName').value=data?.full_name||full;$('phone').value=data?.phone||phone;syncName();lockProfile();showStatus('Profile saved successfully.')}catch(err){showStatus(err.message||'Could not save profile.','error')}finally{b.disabled=false;b.textContent='Save profile'}}
function addressMessage(msg,type='success'){$('addressStatus').innerHTML=msg?'<div class="alert '+type+'">'+esc(msg)+'</div>':'';if(msg)setTimeout(()=>{$('addressStatus').innerHTML=''},3500)}
function renderAddresses(){const box=$('addressList');if(!addressesCache.length){box.innerHTML='<div class="empty">No delivery address saved yet.</div>';return}box.innerHTML=addressesCache.map(a=>'<article class="address-card"><div class="address-top"><div><div class="address-title">'+esc(a.label||'Address')+(a.is_default?'<span class="address-default">DEFAULT</span>':'')+'</div><div class="address-text"><b>'+esc(a.full_name)+'</b> · '+esc(a.phone)+'<br>'+esc(a.address_line1)+(a.address_line2?'<br>'+esc(a.address_line2):'')+'<br>'+esc(a.city)+', '+esc(a.state)+' - '+esc(a.postal_code)+'</div></div><div class="address-actions"><button class="btn" data-edit-address="'+a.id+'" type="button">Edit</button>'+(!a.is_default?'<button class="btn" data-default-address="'+a.id+'" type="button">Make default</button>':'')+'<button class="btn danger" data-delete-address="'+a.id+'" type="button">Delete</button></div></div></article>').join('');box.querySelectorAll('[data-edit-address]').forEach(b=>b.onclick=()=>openAddressForm(addressesCache.find(a=>String(a.id)===String(b.dataset.editAddress))));box.querySelectorAll('[data-default-address]').forEach(b=>b.onclick=()=>makeDefaultAddress(Number(b.dataset.defaultAddress)));box.querySelectorAll('[data-delete-address]').forEach(b=>b.onclick=()=>deleteAddress(Number(b.dataset.deleteAddress)))}
async function loadAddresses(){const box=$('addressList');box.innerHTML='<div class="empty">Loading addresses…</div>';const{data,error}=await supabaseClient.from('customer_addresses').select('id,user_id,label,full_name,phone,address_line1,address_line2,city,state,postal_code,country,is_default,created_at,updated_at').eq('user_id',currentUser.id).order('is_default',{ascending:false}).order('created_at',{ascending:false});if(error)throw error;addressesCache=data||[];renderAddresses()}
function openAddressForm(a=null){editingAddressId=a?.id||null;$('addressFormTitle').textContent=a?'Edit delivery address':'Add delivery address';$('addressName').value=a?.full_name||$('fullName').value||'';$('addressPhone').value=a?.phone||$('phone').value||'';$('addressLine1').value=a?.address_line1||'';$('addressLine2').value=a?.address_line2||'';$('addressCity').value=a?.city||'';$('addressState').value=a?.state||'';$('addressPin').value=a?.postal_code||'';$('addressLabel').value=a?.label||'Home';$('addressDefault').checked=!!a?.is_default;$('addressForm').classList.add('show');$('addressForm').scrollIntoView({behavior:'smooth',block:'nearest'})}
function closeAddressForm(){editingAddressId=null;$('addressForm').reset();$('addressLabel').value='Home';$('addressForm').classList.remove('show')}
function isPlaceholderValue(v){const s=String(v||'').trim();return !s||/^0+$/.test(s)}
async function saveAddress(e){e.preventDefault();addressMessage('');const pin=$('addressPin').value.trim(),phone=$('addressPhone').value.trim();if(!/^\d{6}$/.test(pin)){addressMessage('Please enter a valid 6-digit PIN code.','error');return}if(!/^\+?[0-9 -]{10,20}$/.test(phone)){addressMessage('Please enter a valid phone number.','error');return}const row={user_id:currentUser.id,label:$('addressLabel').value.trim()||'Home',full_name:$('addressName').value.trim(),phone,address_line1:$('addressLine1').value.trim(),address_line2:$('addressLine2').value.trim()||null,city:$('addressCity').value.trim(),state:$('addressState').value.trim(),postal_code:pin,country:'India',updated_at:new Date().toISOString()},wantDefault=$('addressDefault').checked,wasEditing=Boolean(editingAddressId);if(isPlaceholderValue(row.full_name)||row.full_name.length<2||isPlaceholderValue(row.address_line1)||row.address_line1.length<3||isPlaceholderValue(row.city)||row.city.length<2||isPlaceholderValue(row.state)||row.state.length<2){addressMessage('Please enter a complete delivery address. Placeholder values such as 0 are not allowed.','error');return}const saveBtn=$('saveAddress');saveBtn.disabled=true;saveBtn.textContent='Saving…';try{let savedId=editingAddressId;if(wasEditing){const{error}=await supabaseClient.from('customer_addresses').update(row).eq('id',editingAddressId).eq('user_id',currentUser.id);if(error)throw error}else{const firstAddress=addressesCache.length===0;const{data,error}=await supabaseClient.from('customer_addresses').insert({...row,is_default:false}).select('id').single();if(error)throw error;savedId=data.id;if(firstAddress)$('addressDefault').checked=true}if(wantDefault||(!wasEditing&&$('addressDefault').checked)){const{error}=await supabaseClient.rpc('set_default_customer_address',{p_address_id:Number(savedId)});if(error)throw error}closeAddressForm();addressMessage(wasEditing?'Address updated.':'Address saved.');await loadAddresses()}catch(err){addressMessage(err.message||'Could not save address.','error')}finally{saveBtn.disabled=false;saveBtn.textContent='Save address'}}
async function makeDefaultAddress(id){const{error}=await supabaseClient.rpc('set_default_customer_address',{p_address_id:Number(id)});if(error){addressMessage(error.message||'Could not change default address.','error');return}addressMessage('Default delivery address changed.');await loadAddresses()}
async function deleteAddress(id){if(!confirm('Delete this delivery address?'))return;const{error}=await supabaseClient.from('customer_addresses').delete().eq('id',id).eq('user_id',currentUser.id);if(error){addressMessage(error.message||'Could not delete address.','error');return}addressMessage('Address deleted.');await loadAddresses()}
function switchView(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('.menu button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const map={orders:['ordersView','My Orders','Track purchases, delivery progress, cancellations and refunds.'],profile:['profileView','Profile','Manage your personal account information.'],addresses:['addressesView','Addresses','Manage saved delivery addresses and your default checkout address.'],refunds:['refundsView','Payments & Refunds','Review refund progress linked to your orders.']},m=map[view]||map.orders;$(m[0]).classList.add('active');$('viewTitle').textContent=m[1];$('viewSub').textContent=m[2];history.replaceState(null,'',location.pathname+'#'+(map[view]?view:'orders'));if(view==='addresses'&&!addressesCache.length)loadAddresses().catch(e=>addressMessage(e.message||'Could not load addresses.','error'))}
async function logout(){try{await supabaseClient.auth.signOut()}finally{localStorage.removeItem('customer_name');localStorage.removeItem('customer_phone');location.href='index.html'}}
async function init(){const{data:{user},error}=await supabaseClient.auth.getUser();if(error||!user){location.href='login.html';return}currentUser=user;await Promise.all([loadProfile(),loadOrders()]);$('loading').hidden=true;$('app').hidden=false;switchView((location.hash||'#orders').slice(1))}
document.querySelectorAll('.menu button[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('refreshOrders').onclick=()=>loadOrders().catch(e=>{$('ordersList').innerHTML='<div class="alert error">'+esc(e.message||'Could not load orders.')+'</div>'});$('editProfile').onclick=unlockProfile;$('profileForm').onsubmit=saveProfile;$('addAddress').onclick=()=>openAddressForm();$('cancelAddress').onclick=closeAddressForm;$('addressForm').onsubmit=saveAddress;$('topLogout').onclick=logout;$('menuLogout').onclick=logout;window.addEventListener('hashchange',()=>switchView((location.hash||'#orders').slice(1)));init().catch(e=>{console.error(e);$('loading').textContent='Account could not be loaded.'});
