'use strict';
const form=document.getElementById('form'),email=document.getElementById('email'),password=document.getElementById('password'),submit=document.getElementById('submit'),banner=document.getElementById('banner');
const redirectRaw=new URLSearchParams(location.search).get('redirect');
const OTP_API='https://seller.fashionfussion.in/api/whatsapp-otp';
const safe=(e,fallback)=>window.ffCustomerMessage?window.ffCustomerMessage(e,fallback):fallback;
function show(msg,type='error'){banner.textContent=msg;banner.className='banner show '+type}
function safeReturnPath(){if(!redirectRaw)return null;const aliases={checkout:'checkout.html',account:'account.html',orders:'account.html#orders'};const candidate=aliases[redirectRaw]||redirectRaw;try{const u=new URL(candidate,location.href);if(u.origin!==location.origin)return null;const page=u.pathname.split('/').pop();const allowed=new Set(['checkout.html','account.html','cart.html','wishlist.html','notifications.html','coupons.html','gift-cards.html','order-details.html','order-confirmation.html','quote-checkout.html']);if(!allowed.has(page))return null;return page+u.search+u.hash}catch{return null}}
function syncSignupLinks(){const target=safeReturnPath();[['personalSignupLink','retail'],['businessSignupLink','business']].forEach(([id,account])=>{const link=document.getElementById(id);if(!link)return;const p=new URLSearchParams({account});if(target)p.set('redirect',target);link.href='signup.html?'+p.toString()})}
function adminDestination(){const origin=String(window.FF_ADMIN_ORIGIN||'https://admin.fashionfussion.in').replace(/\/+$/,'');return origin+'/'}
async function profile(user){const{data}=await window.supabaseClient.from('profiles').select('is_admin,account_type,phone_verified_at').eq('id',user.id).maybeSingle();return data||{}}
async function finalizePendingPhone(session,p){if(!session?.access_token||p?.is_admin===true||p?.phone_verified_at)return p;const audience=p?.account_type==='business'?'retailer':'customer';const r=await fetch(OTP_API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token},body:JSON.stringify({action:'finalize',audience})});if(r.ok)return await profile(session.user);if(r.status===409)return p;const d=await r.json().catch(()=>({}));console.warn('[Customer auth] Pending WhatsApp verification could not be finalized',d.error||r.status);return p}
async function destination(user,p=null){const current=p||await profile(user);if(current?.is_admin===true)return adminDestination();return safeReturnPath()||'account.html#orders'}
async function redirectExisting(){const{data:{session},error}=await window.supabaseClient.auth.getSession();if(error)return;if(session?.user){let p=await profile(session.user);p=await finalizePendingPhone(session,p);location.replace(await destination(session.user,p))}}
form.addEventListener('submit',async e=>{e.preventDefault();const mail=email.value.trim();if(!mail||!password.value){show('Enter your email and password.');return}submit.disabled=true;submit.textContent='Signing in…';try{const{data,error}=await window.supabaseClient.auth.signInWithPassword({email:mail,password:password.value});if(error)throw error;if(!data?.user)throw new Error('Sign in could not be completed.');let p=await profile(data.user);p=await finalizePendingPhone(data.session,p);show('Signed in successfully.','success');location.replace(await destination(data.user,p))}catch(err){show(safe(err,'Unable to sign in. Please check your details and try again.'))}finally{submit.disabled=false;submit.textContent='Sign in'}});
document.getElementById('forgot').onclick=async()=>{const mail=email.value.trim();if(!mail){show('Enter your email address first.');email.focus();return}try{const redirectTo=new URL('reset-password.html',location.href).href;const{error}=await window.supabaseClient.auth.resetPasswordForEmail(mail,{redirectTo});if(error)throw error;show('Password reset email sent. Check your inbox.','success')}catch(err){show(safe(err,'Unable to send the reset email. Please try again.'))}};
syncSignupLinks();redirectExisting().catch(console.error);