'use strict';
(function(){
const signalMap=new Map();
let busy=false,queued=false;
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function productId(card){const b=card.querySelector('[data-add]');return b?Number(b.dataset.add):0}
function label(s){if(s.value_signal==='great_value')return 'Great value';if(s.value_signal==='competitive')return 'Competitive price';return ''}
function decorateCard(card){const id=productId(card),s=signalMap.get(id);if(!id||!s)return;card.dataset.marketplaceBoost=String(Number(s.relevance_boost||0));let row=card.querySelector('.ff-marketplace-signals');if(!row){row=document.createElement('div');row.className='ff-marketplace-signals';const body=card.querySelector('.body');if(body)body.insertBefore(row,body.firstChild)}if(!row)return;const bits=[];if(s.verified_seller)bits.push('<span class="ff-signal verified" title="Seller identity and payout account are verified by Fashion Fussion">✓ Verified Seller</span>');const priceLabel=label(s);if(priceLabel){const ref=Number(s.category_reference_price||0);bits.push('<span class="ff-signal value" title="Compared only with active products in the same Fashion Fussion category'+(ref?' · category median '+esc('₹'+ref.toLocaleString('en-IN')):'')+'">'+esc(priceLabel)+'</span>')}if(s.visibility_boost_active)bits.push('<span class="ff-signal launch" title="New seller LaunchPad visibility window">New brand</span>');row.innerHTML=bits.join('')}
function reorder(container){const sort=document.getElementById('sort');if(sort&&sort.value!=='relevance')return;const cards=[...container.children].filter(x=>x.classList?.contains('product'));if(cards.length<2)return;const ordered=cards.map((el,i)=>({el,i,b:Number(el.dataset.marketplaceBoost||0)})).sort((a,b)=>b.b-a.b||a.i-b.i);if(ordered.every((x,i)=>x.el===cards[i]))return;ordered.forEach(x=>container.appendChild(x.el))}
function apply(){if(busy)return;busy=true;try{document.querySelectorAll('article.product').forEach(decorateCard);const home=document.getElementById('productsGrid'),search=document.getElementById('grid');if(home)reorder(home);if(search)reorder(search)}finally{busy=false}}
function schedule(){if(queued)return;queued=true;setTimeout(()=>{queued=false;apply()},30)}
async function load(){try{if(window.ffSupabaseReady)await window.ffSupabaseReady;if(!window.supabaseClient)return;const{data,error}=await window.supabaseClient.rpc('get_marketplace_product_signals');if(error)throw error;(data||[]).forEach(s=>signalMap.set(Number(s.product_id),s));apply();const observer=new MutationObserver(schedule);['productsGrid','grid'].forEach(id=>{const e=document.getElementById(id);if(e)observer.observe(e,{childList:true,subtree:true})});const sort=document.getElementById('sort');if(sort)sort.addEventListener('change',schedule)}catch(e){console.warn('[Marketplace signals]',e?.message||e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();
})();
