(async function(){
  const root=document.getElementById('promoRoot');
  const db=window.supabaseClient||(window.ffSupabaseReady?await window.ffSupabaseReady:null);
  if(!db){if(root)root.innerHTML='<div class="ff-empty">Offers could not be loaded. Please refresh and try again.</div>';return}
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const money=v=>'₹'+Number(v||0).toLocaleString('en-IN');
  function css(){if(document.getElementById('promotionsRuntimeStyles'))return;const s=document.createElement('link');s.rel='stylesheet';s.href='runtime-promotions-1.css?v=1';s.id='promotionsRuntimeStyles';document.head.appendChild(s)}
  async function resolvedUser(){const{data:{user},error}=await db.auth.getUser();if(user)return user;if(error){try{const{data:{session}}=await db.auth.getSession();return session?.user||null}catch{}}return null}
  async function init(){css();const kind=document.body.dataset.promoKind;if(!root)return;const user=await resolvedUser();if(!user){const target=(kind==='coupons'?'coupons.html':'gift-cards.html')+location.search+location.hash;location.replace('login.html?redirect='+encodeURIComponent(target));return}const isCoupon=kind==='coupons';const table=isCoupon?'coupons':'gift_cards';const fields=isCoupon?'id,code,title,description,discount_type,discount_value,min_order_amount,max_discount,starts_at,expires_at,is_active,created_at':'id,title,amount,description,validity_days,is_active,created_at';const {data,error}=await db.from(table).select(fields).order('created_at',{ascending:false});if(error){root.innerHTML='<div class="ff-empty">Unable to load offers. Please refresh and try again.</div>';return}root.innerHTML=`<a class="ff-back" href="index.html">← Back to Store</a><h1>${isCoupon?'Coupons':'Gift Cards'}</h1><div class="sub">${isCoupon?'Available savings for your next order.':'Choose an available Fashion_Fussion gift card.'}</div>${!data?.length?'<div class="ff-empty">No active offers available right now.</div>':`<div class="ff-pgrid">${data.map(x=>isCoupon?`<article class="ff-pcard"><span class="ff-code">${esc(x.code)}</span><div class="ff-value">${x.discount_type==='percent'?esc(x.discount_value)+'% OFF':money(x.discount_value)+' OFF'}</div><strong>${esc(x.title)}</strong><div class="ff-meta">${esc(x.description||'')}<br>Minimum order: ${money(x.min_order_amount)}${x.expires_at?'<br>Valid till: '+new Date(x.expires_at).toLocaleDateString('en-IN'):''}</div></article>`:`<article class="ff-pcard"><span class="ff-code">GIFT CARD</span><div class="ff-value">${money(x.amount)}</div><strong>${esc(x.title)}</strong><div class="ff-meta">${esc(x.description||'')}<br>Validity: ${esc(x.validity_days)} days</div></article>`).join('')}</div>`}`}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>init().catch(handleError),{once:true});else await init()
  function handleError(error){console.error(error);if(root)root.innerHTML='<div class="ff-empty">Offers could not be loaded. Please refresh and try again.</div>'}
})().catch(error=>{console.error(error);const root=document.getElementById('promoRoot');if(root)root.innerHTML='<div class="ff-empty">Offers could not be loaded. Please refresh and try again.</div>'});
