(function(){
'use strict';
if(!document.querySelector('script[data-desktop-checkout-loader]')){const s=document.createElement('script');s.src='desktop-checkout-loader.js?v=2';s.async=false;s.setAttribute('data-desktop-checkout-loader','true');document.head.appendChild(s)}
const money=v=>'₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function pageName(){const leaf=location.pathname.split('/').filter(Boolean).pop()||'index.html';return leaf.includes('.')?leaf:leaf+'.html'}
function api(){return window.FashionVariantCart}
async function repairLines(){const cart=api();if(!cart?.readLines||!cart?.resolveSingleSellableVariants)return;const lines=cart.readLines();if(!lines.some(l=>l.variant_id==null))return;await cart.resolveSingleSellableVariants({items:lines.map(l=>({id:l.id,variant_id:l.variant_id,qty:l.qty}))})}
async function variantMap(lines){const ids=[...new Set(lines.map(l=>Number(l.variant_id)).filter(Number.isInteger))];if(!ids.length)return new Map();const{data,error}=await window.supabaseClient.from('product_variants').select('id,product_id,title,size,color,sku,price_override,image_url,is_active').in('id',ids).eq('is_active',true);if(error)throw error;return new Map((data||[]).map(v=>[Number(v.id),v]))}
async function productMap(lines){const ids=[...new Set(lines.map(l=>Number(l.id)).filter(Number.isInteger))];if(!ids.length)return new Map();const{data,error}=await window.supabaseClient.from('products').select('id,name,category,price,image_url,gst_rate,is_active,has_variants').in('id',ids).eq('is_active',true);if(error)throw error;return new Map((data||[]).map(p=>[Number(p.id),p]))}
function variantText(v){if(!v)return'';return [v.size&&('Size '+v.size),v.color&&('Color '+v.color),v.title&&!v.size&&!v.color&&v.title,v.sku&&('SKU '+v.sku)].filter(Boolean).join(' · ')}
function image(p,v,cls){const src=v?.image_url||p?.image_url;return src?'<img class="'+cls+'" src="'+esc(src)+'" alt="'+esc(p?.name||'Product')+'">':'<div class="fallback">Image unavailable</div>'}
function lineState(line,p,v){if(line.variant_id!=null&&!v)return'invalid';if(p?.has_variants===true&&line.variant_id==null)return'choose';return'ready'}
function blockedMessage(state){return state==='choose'?'Choose size / colour options before checkout.':'The selected product option is no longer available.'}
async function renderCart(){const cartBox=document.getElementById('cart');if(!cartBox||!api()?.readLines)return false;await repairLines();const lines=api().readLines();const[pMap,vMap]=await Promise.all([productMap(lines),variantMap(lines)]);const active=lines.filter(l=>pMap.has(Number(l.id)));if(!active.length)return false;const enhanced=active.some(line=>line.variant_id!=null||pMap.get(Number(line.id))?.has_variants===true);if(!enhanced)return false;let blocked=false;cartBox.innerHTML=active.map(line=>{const p=pMap.get(Number(line.id)),v=vMap.get(Number(line.variant_id)),state=lineState(line,p,v),q=Number(line.qty),key=String(line.id)+':'+(line.variant_id??'base');if(state!=='ready'){blocked=true;return '<article class="item" data-variant-line="'+esc(key)+'">'+image(p,null,'pic')+'<div><div class="name"><a href="product.html?id='+encodeURIComponent(p.id)+'">'+esc(p.name)+'</a></div><div class="meta">'+esc(p.category||'General')+'</div><div class="meta"><strong>'+esc(blockedMessage(state))+'</strong></div><div class="controls"><a class="btn" href="product.html?id='+encodeURIComponent(p.id)+'">'+(state==='choose'?'CHOOSE OPTIONS':'VIEW PRODUCT')+'</a><button class="remove" data-vremove>REMOVE</button></div></div><div><div class="line-total">Unavailable</div></div></article>'}const price=Number(v?.price_override??p.price??0);return '<article class="item" data-variant-line="'+esc(key)+'">'+image(p,v,'pic')+'<div><div class="name"><a href="product.html?id='+encodeURIComponent(p.id)+'">'+esc(p.name)+'</a></div><div class="meta">'+esc(p.category||'General')+' · GST '+Number(p.gst_rate||0)+'%</div>'+(v?'<div class="meta"><strong>'+esc(variantText(v))+'</strong></div>':'')+'<div class="unit">'+money(price)+' / piece</div>'+(q>=10?'<div class="bulk">LARGER QUANTITY · '+q+' PCS</div>':'')+'<div class="controls"><div class="qty"><button data-vdec>−</button><input data-vqty type="number" min="1" max="500" value="'+q+'"><button data-vinc>+</button></div><button class="remove" data-vremove>REMOVE</button></div></div><div><div class="line-total">'+money(price*q)+'</div><div class="line-gst">before applicable GST</div></div></article>'}).join('');
cartBox.querySelectorAll('[data-variant-line]').forEach(el=>{const [pid,vidRaw]=el.dataset.variantLine.split(':'),vid=vidRaw==='base'?null:Number(vidRaw),line=active.find(x=>String(x.id)===pid&&String(x.variant_id??'base')===vidRaw),inc=el.querySelector('[data-vinc]'),dec=el.querySelector('[data-vdec]'),qty=el.querySelector('[data-vqty]'),remove=el.querySelector('[data-vremove]');if(inc)inc.onclick=()=>{api().updateLine(pid,vid,Math.min(500,line.qty+1));location.reload()};if(dec)dec.onclick=()=>{api().updateLine(pid,vid,line.qty-1);location.reload()};if(qty)qty.onchange=e=>{api().updateLine(pid,vid,Math.max(1,Math.min(500,Math.floor(Number(e.target.value)||1))));location.reload()};if(remove)remove.onclick=()=>{api().removeLine(pid,vid);location.reload()}});const place=document.getElementById('place');if(place&&blocked)place.disabled=true;const verify=document.getElementById('verifyBox');if(verify&&blocked){verify.textContent='Choose or remove unavailable product options before checkout.';verify.className='verify err'}return true}
async function renderCheckout(){const box=document.getElementById('itemsBox');if(!box||!api()?.readLines)return false;await repairLines();const lines=api().readLines();const[pMap,vMap]=await Promise.all([productMap(lines),variantMap(lines)]);const active=lines.filter(l=>pMap.has(Number(l.id)));if(!active.length)return false;const enhanced=active.some(line=>line.variant_id!=null||pMap.get(Number(line.id))?.has_variants===true);if(!enhanced)return false;let blocked=false;box.className='';box.innerHTML=active.map(line=>{const p=pMap.get(Number(line.id)),v=vMap.get(Number(line.variant_id)),state=lineState(line,p,v),q=Number(line.qty);if(state!=='ready'){blocked=true;return '<div class="item">'+image(p,null,'thumb')+'<div><div class="name">'+esc(p.name)+'</div><div class="meta"><strong>'+esc(blockedMessage(state))+'</strong></div><div class="meta"><a href="product.html?id='+encodeURIComponent(p.id)+'">'+(state==='choose'?'Choose product options':'View product')+'</a> or return to the cart to remove it.</div></div><div class="line-total">Unavailable</div></div>'}const price=Number(v?.price_override??p.price??0);return '<div class="item">'+image(p,v,'thumb')+'<div><div class="name">'+esc(p.name)+'</div><div class="meta">'+esc(p.category||'General')+(v?' · <strong>'+esc(variantText(v))+'</strong>':'')+'</div><div class="price">'+money(price)+' <span class="unit-suffix">/ piece</span></div>'+(q>=10?'<div class="bulk-note">Larger quantity · '+q+' pieces</div>':'')+'<div class="meta quantity-meta">Quantity: '+q+'</div></div><div class="line-total">'+money(price*q)+'</div></div>'}).join('');if(blocked){const button=document.getElementById('continueBtn');if(button)button.disabled=true;const status=document.getElementById('checkoutStatus');if(status){status.textContent='Choose or remove unavailable product options before payment.';status.className='status show error'}}return true}
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
async function waitForBaseSurface(page){const selector=page==='cart.html'?'#cart':'#itemsBox';for(let i=0;i<60;i++){const box=document.querySelector(selector);if(box){const text=(box.textContent||'').trim();if(page==='cart.html'){if(!box.querySelector('.loading')&&(box.querySelector('.item')||box.querySelector('.empty')))return}else if(!/^Loading products/i.test(text))return}await sleep(100)}}
async function start(){try{const page=pageName();if(page!=='cart.html'&&page!=='checkout.html')return;await waitForBaseSurface(page);if(page==='cart.html')await renderCart();if(page==='checkout.html')await renderCheckout()}catch(e){console.error('Variant cart UI enhancement failed',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>start(),{once:true});else start();
})();
