const {
  KEY_ID, KEY_SECRET, SUPABASE_URL, serverHeaders, cors, json, readBody,
  basicAuth, getSupabaseUser, roundMoney
} = require('../lib');

async function rest(path, options = {}) { const response=await fetch(SUPABASE_URL+'/rest/v1/'+path,{...options,headers:{...serverHeaders,...(options.headers||{})}}); const data=await response.json().catch(()=>null); if(!response.ok){const error=new Error(data?.message||data?.error||'Order cancellation failed');error.status=response.status;throw error} return data }
async function rpc(name,args){const response=await fetch(SUPABASE_URL+'/rest/v1/rpc/'+name,{method:'POST',headers:{...serverHeaders,'Content-Type':'application/json'},body:JSON.stringify(args)});const data=await response.json().catch(()=>null);if(!response.ok){const error=new Error(data?.message||data?.error||'Order reconciliation failed');error.status=response.status;throw error}return data}
async function restoreCancelledOrder(order){await rpc('release_order_inventory',{p_order_id:order.id});await rpc('restock_cancelled_order_inventory',{p_order_id:order.id});await rpc('restore_cancelled_order_promotions',{p_order_id:order.id,p_user_id:order.user_id})}
async function tryRestoreCancelledOrder(order){try{await restoreCancelledOrder(order);return true}catch(error){console.error('Cancellation resource reconciliation pending:',{order_id:order?.id,message:error.message});return false}}
function cleanReason(value){const reason=String(value||'').trim();if(!reason)throw new Error('Please select a cancellation reason');if(reason.length>180)throw new Error('Cancellation reason is too long');return reason}
function pricing(order){const items=Array.isArray(order.items)?order.items:[];const subtotal=roundMoney(items.reduce((sum,item)=>sum+Number(item?.taxable_amount??(Number(item?.unit_price||0)*Number(item?.qty||1))),0));const gst=roundMoney(items.reduce((sum,item)=>sum+Number(item?.gst_amount||0),0));const coupon=roundMoney(order.coupon_discount||0),gift=roundMoney(order.gift_card_discount||0),total=roundMoney(order.total_amount||0),delivery=roundMoney(Math.max(0,total-subtotal-gst+coupon+gift)),refundable=roundMoney(Math.max(0,total-delivery));return{subtotal,gst,coupon,gift,delivery,total,refundable}}
function refundReference(refund){return refund?.acquirer_data?.arn||refund?.acquirer_data?.rrn||refund?.acquirer_data?.utr||null}
async function createRazorpayRefund(order,amount){if(!KEY_ID||!KEY_SECRET){const e=new Error('Refund service is not configured');e.status=503;throw e}if(!order.razorpay_payment_id){const e=new Error('Payment reference is missing for this order');e.status=409;throw e}const payload={amount:Math.round(Number(amount)*100),speed:'normal',receipt:'FF_CANCEL_'+String(order.id),notes:{store_order_id:String(order.id),source:'customer_cancellation'}};const response=await fetch('https://api.razorpay.com/v1/payments/'+encodeURIComponent(order.razorpay_payment_id)+'/refund',{method:'POST',headers:{Authorization:basicAuth(),'Content-Type':'application/json','X-Refund-Idempotency':'ff_cancel_'+String(order.id)+'_refund'},body:JSON.stringify(payload)});const refund=await response.json().catch(()=>({}));if(!response.ok||!refund?.id){const e=new Error(refund?.error?.description||'Refund could not be initiated');e.status=response.status===409?409:502;throw e}return refund}
async function patchCancelledOrder(order,nextStatus,audit={}){const now=new Date().toISOString(),patch={status:nextStatus,fulfillment_status:'cancelled',fulfillment_updated_at:now,cancellation_reason:audit.reason||null,cancelled_at:now};if(audit.refund){patch.refund_id=audit.refund.id||null;patch.refund_status=audit.refund.status||null;patch.refund_reference=refundReference(audit.refund);patch.refund_amount=roundMoney(Number(audit.refund.amount||0)/100);patch.refund_updated_at=now}const updated=await rest('orders?id=eq.'+encodeURIComponent(order.id)+'&user_id=eq.'+encodeURIComponent(order.user_id)+'&status=eq.'+encodeURIComponent(String(order.status||'').toLowerCase())+'&fulfillment_status=in.(ordered,packed)',{method:'PATCH',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(patch)});if(!updated?.length){const e=new Error('Order status changed before cancellation. Please refresh and try again.');e.status=409;throw e}const resourcesReconciled=await tryRestoreCancelledOrder(updated[0]);return{order:updated[0],resourcesReconciled}}
async function claimPrepaidCancellation(order,reason,refundAmount){const claimed=await rpc('claim_prepaid_order_cancellation',{p_order_id:order.id,p_user_id:order.user_id,p_reason:reason,p_refund_amount:refundAmount});const claimedOrder=Array.isArray(claimed)?claimed[0]:claimed;if(!claimedOrder?.id){const e=new Error('Order cancellation could not be reserved. Please refresh and try again.');e.status=409;throw e}return{order:claimedOrder,resourcesReconciled:await tryRestoreCancelledOrder(claimedOrder)}}
async function recordRefundResult(order,nextStatus,refund,fallbackStatus){const now=new Date().toISOString(),patch={status:nextStatus,refund_status:refund?.status||fallbackStatus||null,refund_updated_at:now};if(refund?.id){patch.refund_id=refund.id;patch.refund_reference=refundReference(refund);patch.refund_amount=roundMoney(Number(refund.amount||0)/100)}const updated=await rest('orders?id=eq.'+encodeURIComponent(order.id)+'&status=eq.refund_initiated&fulfillment_status=eq.cancelled',{method:'PATCH',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(patch)});if(!updated?.length){const e=new Error('Cancellation was reserved, but the refund audit state changed unexpectedly. Support review is required.');e.status=409;throw e}return updated[0]}
module.exports=async function cancelOrder(req,res){cors(req,res);if(req.method==='OPTIONS'){res.statusCode=204;return res.end()}if(req.method!=='POST')return json(req,res,405,{error:'Method not allowed'});try{const user=await getSupabaseUser(req),body=await readBody(req),orderId=Number(body.order_id),reason=cleanReason(body.reason);if(!Number.isInteger(orderId)||orderId<1)return json(req,res,400,{error:'Invalid order ID'});const rows=await rest('orders?id=eq.'+encodeURIComponent(orderId)+'&user_id=eq.'+encodeURIComponent(user.id)+'&select=id,display_order_id,user_id,status,payment_method,fulfillment_status,total_amount,items,coupon_discount,gift_card_discount,razorpay_payment_id&limit=1'),order=rows?.[0];if(!order)return json(req,res,404,{error:'Order not found'});const status=String(order.status||'').toLowerCase(),paymentMethod=String(order.payment_method||'').toLowerCase(),fulfillment=String(order.fulfillment_status||'ordered').toLowerCase(),terminal=['cancelled','cod_cancelled','refunded','payment_failed','expired','refund_initiated','refund_pending','refund_failed'];if(terminal.includes(status)||fulfillment==='cancelled'){await tryRestoreCancelledOrder(order);return json(req,res,409,{error:'This order is already closed'})}if(!['ordered','packed'].includes(fulfillment))return json(req,res,409,{error:'This order can no longer be cancelled because fulfilment has progressed'});const breakdown=pricing(order);
if(paymentMethod==='cod'){if(status!=='cod_pending')return json(req,res,409,{error:'This COD order is not in a cancellable payment state'});const cancelled=await patchCancelledOrder(order,'cod_cancelled',{reason});return json(req,res,200,{ok:true,order_id:orderId,display_order_id:order.display_order_id,status:'cod_cancelled',fulfillment_status:'cancelled',reason,resources_reconciled:cancelled.resourcesReconciled,refund:{required:false,amount:0,delivery_non_refundable:breakdown.delivery,destination:null,message:'No refund is required because payment was not collected for this COD order.'}})}
if(paymentMethod!=='prepaid'||status!=='paid')return json(req,res,409,{error:'This prepaid order is not in a cancellable payment state'});if(breakdown.refundable<=0){const cancelled=await patchCancelledOrder(order,'cancelled',{reason});return json(req,res,200,{ok:true,order_id:orderId,display_order_id:order.display_order_id,status:'cancelled',fulfillment_status:'cancelled',reason,resources_reconciled:cancelled.resourcesReconciled,refund:{required:false,amount:0,delivery_non_refundable:breakdown.delivery,destination:'original_payment_method',gift_card_restored:cancelled.resourcesReconciled&&breakdown.gift>0,message:'No payment refund is due.'}})}
const claimed=await claimPrepaidCancellation(order,reason,breakdown.refundable);let refund;try{refund=await createRazorpayRefund(order,breakdown.refundable)}catch(refundError){await recordRefundResult(claimed.order,'refund_failed',null,'failed').catch(auditError=>console.error('Failed to persist refund failure state:',auditError));throw refundError}const processed=String(refund.status||'').toLowerCase()==='processed',nextStatus=processed?'refunded':'refund_initiated';await recordRefundResult(claimed.order,nextStatus,refund,refund.status||(processed?'processed':'pending'));return json(req,res,200,{ok:true,order_id:orderId,display_order_id:order.display_order_id,status:nextStatus,fulfillment_status:'cancelled',reason,resources_reconciled:claimed.resourcesReconciled,refund:{required:true,id:refund.id,status:refund.status||'pending',amount:roundMoney(Number(refund.amount||0)/100),delivery_non_refundable:breakdown.delivery,destination:'original_payment_method',reference:refundReference(refund),speed:refund.speed_processed||refund.speed_requested||'normal',gift_card_restored:claimed.resourcesReconciled&&breakdown.gift>0,message:processed?'Refund processed to the original payment method.':'Refund initiated to the original payment method.'}})}catch(error){console.error('cancel-order error:',error);return json(req,res,error.status||400,{error:error.message||'Unable to cancel order'})}};
