function json(status,body,origin){
  const headers={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Vary':'Origin'};
  if(origin){headers['Access-Control-Allow-Origin']=origin;headers['Access-Control-Allow-Credentials']='true';headers['Access-Control-Allow-Headers']='Content-Type, Authorization';headers['Access-Control-Allow-Methods']='POST, OPTIONS'}
  return new Response(JSON.stringify(body),{status,headers});
}
function clean(v){return String(v||'').trim()}
function allowedOrigin(origin){return ['https://fashionfussion.in','https://www.fashionfussion.in','https://seller.fashionfussion.in'].includes(clean(origin))?clean(origin):''}
function normalizePhone(value){const raw=clean(value);if(!raw)return'';const digits=raw.replace(/\D/g,'');if(/^\d{10}$/.test(digits))return'+91'+digits;if(/^91\d{10}$/.test(digits))return'+'+digits;if(raw.startsWith('+')&&/^\d{8,15}$/.test(digits))return'+'+digits;return''}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}
function validAudience(v){return ['customer','retailer','seller'].includes(v)}
function hex(bytes){return Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('')}
async function sha256(value){return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))}
async function hmac(secret,value){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return hex(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value)))}
function serverKey(env){return clean(env.SUPABASE_SERVICE_ROLE_KEY||env.SUPABASE_SECRET_KEY)}
function requireConfig(env){const missing=[];for(const k of ['SUPABASE_URL','WHATSAPP_ACCESS_TOKEN','WHATSAPP_PHONE_NUMBER_ID','WHATSAPP_OTP_SECRET'])if(!clean(env[k]))missing.push(k);if(missing.length)throw Object.assign(new Error('WhatsApp OTP server configuration is incomplete'),{status:503,details:missing})}
async function rest(env,path,options={}){const key=serverKey(env);if(!key||!clean(env.SUPABASE_URL))throw Object.assign(new Error('Database configuration is missing'),{status:503});const r=await fetch(clean(env.SUPABASE_URL).replace(/\/$/,'')+'/rest/v1/'+path,{...options,headers:{apikey:key,Authorization:'Bearer '+key,'Content-Type':'application/json',...(options.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw Object.assign(new Error(data?.message||data?.error||'Database request failed'),{status:r.status});return data}
function ipFrom(request){return clean(request.headers.get('CF-Connecting-IP')||request.headers.get('X-Forwarded-For')?.split(',')[0])}
async function authUser(request,env){const auth=clean(request.headers.get('Authorization'));if(!auth.startsWith('Bearer '))throw Object.assign(new Error('Authentication required'),{status:401});const key=serverKey(env);const r=await fetch(clean(env.SUPABASE_URL).replace(/\/$/,'')+'/auth/v1/user',{headers:{apikey:key,Authorization:auth}});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.id)throw Object.assign(new Error('Session expired'),{status:401});return d}
async function sendTemplate(env,phone,otp){const version=clean(env.WHATSAPP_API_VERSION||'v26.0');const template=clean(env.WHATSAPP_OTP_TEMPLATE||'fashion_fussion_otp');const language=clean(env.WHATSAPP_OTP_LANGUAGE||'en');const body={messaging_product:'whatsapp',to:phone.replace(/^\+/,''),type:'template',template:{name:template,language:{code:language},components:[{type:'body',parameters:[{type:'text',text:otp}]},{type:'button',sub_type:'url',index:'0',parameters:[{type:'text',text:otp}]}]}};const r=await fetch(`https://graph.facebook.com/${version}/${encodeURIComponent(clean(env.WHATSAPP_PHONE_NUMBER_ID))}/messages`,{method:'POST',headers:{Authorization:'Bearer '+clean(env.WHATSAPP_ACCESS_TOKEN),'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(d?.error?.message||'WhatsApp could not send the OTP'),{status:502});return d}
async function enforceRateLimit(env,phone,email,ipHash){const since=new Date(Date.now()-15*60*1000).toISOString();const encodedPhone=encodeURIComponent(phone),encodedEmail=encodeURIComponent(email);const phoneRows=await rest(env,`phone_otp_challenges?phone_e164=eq.${encodedPhone}&created_at=gte.${encodeURIComponent(since)}&select=id,last_sent_at&order=created_at.desc&limit=6`);if(phoneRows?.[0]){const last=new Date(phoneRows[0].last_sent_at).getTime();if(Number.isFinite(last)&&Date.now()-last<60000)throw Object.assign(new Error('Please wait 60 seconds before requesting another code.'),{status:429})}if((phoneRows||[]).length>=5)throw Object.assign(new Error('Too many OTP requests for this mobile number. Try again later.'),{status:429});const emailRows=await rest(env,`phone_otp_challenges?email=eq.${encodedEmail}&created_at=gte.${encodeURIComponent(since)}&select=id&limit=6`);if((emailRows||[]).length>=5)throw Object.assign(new Error('Too many OTP requests for this email. Try again later.'),{status:429});if(ipHash){const ipRows=await rest(env,`phone_otp_challenges?request_ip_hash=eq.${encodeURIComponent(ipHash)}&created_at=gte.${encodeURIComponent(since)}&select=id&limit=11`);if((ipRows||[]).length>=10)throw Object.assign(new Error('Too many OTP requests. Try again later.'),{status:429})}}
async function sendOtp(request,env,body){requireConfig(env);const phone=normalizePhone(body.phone),email=clean(body.email).toLowerCase(),audience=clean(body.audience).toLowerCase();if(!phone)throw Object.assign(new Error('Enter a valid mobile number.'),{status:400});if(!validEmail(email))throw Object.assign(new Error('Enter a valid email address.'),{status:400});if(!validAudience(audience))throw Object.assign(new Error('Invalid account type.'),{status:400});const ip=ipFrom(request),ipHash=ip?await sha256(ip):null;await enforceRateLimit(env,phone,email,ipHash);const otp=String(crypto.getRandomValues(new Uint32Array(1))[0]%1000000).padStart(6,'0');const otpHash=await hmac(clean(env.WHATSAPP_OTP_SECRET),otp);const expiresAt=new Date(Date.now()+5*60*1000).toISOString();const rows=await rest(env,'phone_otp_challenges',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({phone_e164:phone,email,audience,otp_hash:otpHash,request_ip_hash:ipHash,expires_at:expiresAt,last_sent_at:new Date().toISOString()})});const challenge=rows?.[0];if(!challenge?.id)throw Object.assign(new Error('Could not create OTP challenge'),{status:500});try{await sendTemplate(env,phone,otp)}catch(error){await rest(env,`phone_otp_challenges?id=eq.${encodeURIComponent(challenge.id)}`,{method:'DELETE'}).catch(()=>{});throw error}return{ok:true,challenge_id:challenge.id,expires_in:300,resend_after:60,phone_hint:'••••••'+phone.slice(-4)}}
async function verifyOtp(env,body){requireConfig(env);const id=clean(body.challenge_id),otp=clean(body.otp).replace(/\D/g,'');if(!id||!/^[0-9]{6}$/.test(otp))throw Object.assign(new Error('Enter the 6-digit OTP.'),{status:400});const rows=await rest(env,`phone_otp_challenges?id=eq.${encodeURIComponent(id)}&select=id,phone_e164,email,audience,otp_hash,attempt_count,expires_at,verified_at,consumed_at&limit=1`);const row=rows?.[0];if(!row)throw Object.assign(new Error('OTP request was not found.'),{status:404});if(row.consumed_at)throw Object.assign(new Error('This OTP has already been used.'),{status:409});if(row.verified_at)return{ok:true,verified:true,phone_hint:'••••••'+String(row.phone_e164).slice(-4)};if(new Date(row.expires_at).getTime()<Date.now())throw Object.assign(new Error('OTP expired. Request a new code.'),{status:410});if(Number(row.attempt_count)>=5)throw Object.assign(new Error('Too many incorrect attempts. Request a new code.'),{status:429});const candidate=await hmac(clean(env.WHATSAPP_OTP_SECRET),otp);if(candidate!==row.otp_hash){await rest(env,`phone_otp_challenges?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({attempt_count:Number(row.attempt_count||0)+1})});throw Object.assign(new Error('Incorrect OTP.'),{status:400})}await rest(env,`phone_otp_challenges?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({verified_at:new Date().toISOString()})});return{ok:true,verified:true,phone_hint:'••••••'+String(row.phone_e164).slice(-4)}}
async function finalize(request,env,body){requireConfig(env);const user=await authUser(request,env);const email=clean(user.email).toLowerCase();const audience=clean(body.audience).toLowerCase();if(!email||!validAudience(audience))throw Object.assign(new Error('Verified account email and account type are required.'),{status:400});const since=new Date(Date.now()-24*60*60*1000).toISOString();const rows=await rest(env,`phone_otp_challenges?email=eq.${encodeURIComponent(email)}&audience=eq.${encodeURIComponent(audience)}&verified_at=not.is.null&consumed_at=is.null&verified_at=gte.${encodeURIComponent(since)}&select=id,phone_e164,verified_at&order=verified_at.desc&limit=1`);const row=rows?.[0];if(!row)throw Object.assign(new Error('No recent WhatsApp verification was found for this account. Verify your mobile number again.'),{status:409});const now=new Date().toISOString();if(audience==='seller'){await rest(env,`seller_profiles?user_id=eq.${encodeURIComponent(user.id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({phone:String(row.phone_e164).replace(/^\+91/,''),phone_verified_at:now,phone_verification_method:'whatsapp',updated_at:now})})}else{await rest(env,`profiles?id=eq.${encodeURIComponent(user.id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({phone:String(row.phone_e164).replace(/^\+91/,''),phone_verified_at:now,phone_verification_method:'whatsapp',updated_at:now})})}await rest(env,`phone_otp_challenges?id=eq.${encodeURIComponent(row.id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({consumed_at:now})});return{ok:true,verified:true,phone:String(row.phone_e164)}}
export async function onRequest(context){const{request,env}=context;const origin=allowedOrigin(request.headers.get('Origin'));if(request.headers.get('Origin')&&!origin)return json(403,{error:'Origin not allowed'});if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':origin||'https://fashionfussion.in','Access-Control-Allow-Credentials':'true','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Max-Age':'86400','Vary':'Origin'}});if(request.method!=='POST')return json(405,{error:'Method not allowed'},origin);try{const body=await request.json().catch(()=>({}));const action=clean(body.action).toLowerCase();let result;if(action==='send')result=await sendOtp(request,env,body);else if(action==='verify')result=await verifyOtp(env,body);else if(action==='finalize')result=await finalize(request,env,body);else throw Object.assign(new Error('Unsupported action'),{status:400});return json(200,result,origin)}catch(error){console.error('[WhatsApp OTP]',error);return json(error.status||500,{error:error.message||'WhatsApp OTP request failed'},origin)}}
