'use strict';
const form=document.getElementById('form'),email=document.getElementById('email'),password=document.getElementById('password'),submit=document.getElementById('submit'),banner=document.getElementById('banner');
const adminSupabaseReady=window.ffAdminSupabaseReady||Promise.resolve(window.supabaseClient);
function show(message,type='error'){banner.textContent=message;banner.className='banner show '+type}
async function client(){const value=await adminSupabaseReady;if(!value?.auth)throw new Error('Admin authentication service is unavailable.');return value}
async function isAdmin(user,db){if(!user?.id)return false;const{data,error}=await db.from('profiles').select('is_admin').eq('id',user.id).maybeSingle();if(error)throw error;return data?.is_admin===true}
async function redirectExisting(){const db=await client();const{data:{session},error}=await db.auth.getSession();if(error||!session?.user)return;if(await isAdmin(session.user,db)){location.replace('admin.html');return}await db.auth.signOut();show('This account does not have administrator access.')}
form.addEventListener('submit',async event=>{event.preventDefault();const mail=email.value.trim();if(!mail||!password.value){show('Enter your administrator email and password.');return}submit.disabled=true;submit.textContent='Checking access…';try{const db=await client();const{data,error}=await db.auth.signInWithPassword({email:mail,password:password.value});if(error)throw error;if(!data?.user)throw new Error('Sign in could not be completed.');if(!await isAdmin(data.user,db)){await db.auth.signOut();throw new Error('Administrator privileges are required.')}show('Administrator verified. Opening dashboard…','success');location.replace('admin.html')}catch(error){show(error.message||'Unable to sign in.')}finally{submit.disabled=false;submit.textContent='Sign in to Admin'}});
document.getElementById('forgot').onclick=async()=>{const mail=email.value.trim();if(!mail){show('Enter your administrator email address first.');email.focus();return}try{const db=await client();const redirectTo=new URL('reset-password.html',location.href).href;const{error}=await db.auth.resetPasswordForEmail(mail,{redirectTo});if(error)throw error;show('Password reset email sent. Check your inbox.','success')}catch(error){show(error.message||'Unable to send reset email.')}};
redirectExisting().catch(error=>{console.error(error);show('Unable to verify the current administrator session.')});
