const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.resolve(__dirname,'..');
const htmlFiles=fs.readdirSync(root).filter(f=>f.endsWith('.html')&&!f.startsWith('google'));
const jsFiles=fs.readdirSync(root).filter(f=>f.endsWith('.js'));
const customerCommerceFiles=new Set(['index.html','search.html','product.html','cart.html','checkout.html','quote-checkout.html','order-confirmation.html','wishlist.html','account.html','order-details.html']);
let errors=[];
const localRef=/\b(?:src|href)=["']([^"']+)["']/gi;
for(const file of htmlFiles){
  const full=path.join(root,file),text=fs.readFileSync(full,'utf8');
  if(/Fashion_FUSSION/.test(text))errors.push(`${file}: obsolete brand Fashion_FUSSION`);
  if(/₹599|DELIVERY_THRESHOLD\s*=\s*599|Same-week dispatch/i.test(text))errors.push(`${file}: obsolete delivery/copy value`);
  if(/cdn\.jsdelivr\.net\/npm\/@supabase\/supabase-js@2(?!\.116\.0)/.test(text))errors.push(`${file}: Supabase browser SDK must be pinned to 2.116.0`);
  if(/localStorage\.(?:setItem|getItem)\(\s*["']customer_(?:name|phone)["']/.test(text))errors.push(`${file}: profile PII must not persist in localStorage`);
  if(customerCommerceFiles.has(file)){
    if(/selling_price/.test(text))errors.push(`${file}: customer storefront must use live products.price, not selling_price`);
    if(/★★★★★|★★★★☆|verified catalogue review/i.test(text))errors.push(`${file}: unsupported/fake review presentation detected`);
    if(/Available to order/i.test(text))errors.push(`${file}: unsupported stock availability claim detected`);
  }
  let ref; while((ref=localRef.exec(text))){const value=ref[1];if(/^(?:https?:|mailto:|tel:|#|javascript:|data:|\/\/)/i.test(value))continue;const clean=value.split('#')[0].split('?')[0];if(clean&&!fs.existsSync(path.join(root,clean)))errors.push(`${file}: missing local reference ${value}`)}
  const re=/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi; let m,i=0;
  while((m=re.exec(text))){i++;try{new vm.Script(m[1],{filename:`${file}:inline-script-${i}`})}catch(e){errors.push(e.message)}}
}
for(const file of jsFiles){const full=path.join(root,file),text=fs.readFileSync(full,'utf8');if(/localStorage\.(?:setItem|getItem)\(\s*["']customer_(?:name|phone)["']/.test(text))errors.push(`${file}: profile PII must not persist in localStorage`);try{new vm.Script(text,{filename:file})}catch(e){errors.push(e.message)}}
const lib=fs.readFileSync(path.join(root,'backend/lib.js'),'utf8');
if(/GST_RATES|GST_MAX_SUPPORTED_ID/.test(lib))errors.push('backend/lib.js: hardcoded product GST map detected');
if(/\.select\(["'](?:[^"']*,)?cost(?:,|["'])/.test(fs.readFileSync(path.join(root,'index.html'),'utf8')))errors.push('index.html: product cost must not be public');
if(!/PAYMENT_HANDLING_FEE\s*=\s*0/.test(lib))errors.push('backend/lib.js: payment handling fee must remain zero');
if(!/PREPAID_DISCOUNT\s*=\s*0/.test(lib))errors.push('backend/lib.js: prepaid discount compatibility field must remain zero');
if(!/cod_fee_non_refundable:\s*false/.test(lib))errors.push('backend/lib.js: COD non-refundable fee flag must remain false');
for(const required of ['has_variants','getVariantsByIds','getInventoryByVariantIds','variant_id','product_variants','inventory_levels','Selected variant does not have enough stock'])if(!lib.includes(required))errors.push(`backend/lib.js: variant/inventory pricing guard missing ${required}`);
const createOrder=fs.readFileSync(path.join(root,'backend/api/create-order.js'),'utf8');
for(const required of ['reserve_order_inventory','commit_order_inventory','release_order_inventory','reserveCheckout','failCheckout'])if(!createOrder.includes(required))errors.push(`backend/api/create-order.js: inventory lifecycle missing ${required}`);
const verifyPayment=fs.readFileSync(path.join(root,'backend/api/verify-payment.js'),'utf8');
for(const required of ['commit_order_inventory','commitInventory','Inventory finalization is being reconciled'])if(!verifyPayment.includes(required))errors.push(`backend/api/verify-payment.js: captured-payment inventory reconciliation missing ${required}`);
const cancelOrder=fs.readFileSync(path.join(root,'backend/api/cancel-order.js'),'utf8');
for(const required of ['cancellation_reason','cancelled_at','refund_id','refund_status','refund_reference','refund_amount','refund_updated_at'])if(!cancelOrder.includes(required))errors.push(`backend/api/cancel-order.js: cancellation/refund audit persistence missing ${required}`);
for(const required of ['release_order_inventory','restock_cancelled_order_inventory'])if(!cancelOrder.includes(required))errors.push(`backend/api/cancel-order.js: cancellation inventory reconciliation missing ${required}`);
const refundStatus=fs.readFileSync(path.join(root,'backend/api/refund-status.js'),'utf8');
for(const required of ['refund_id','refund_status','refund_reference','refund_amount','refund_updated_at'])if(!refundStatus.includes(required))errors.push(`backend/api/refund-status.js: refund reconciliation audit persistence missing ${required}`);
const processReturnRefund=fs.readFileSync(path.join(root,'backend/api/process-return-refund.js'),'utf8');
for(const required of ['Administrator access required','return_request_id','return_refund','X-Refund-Idempotency','COD_PAYOUT_REQUIRED','DISCOUNT_ALLOCATION_REQUIRED','refund_id','refund_status','refund_reference','refund_amount','refund_updated_at'])if(!processReturnRefund.includes(required))errors.push(`backend/api/process-return-refund.js: secure return-refund processing guard missing ${required}`);
const returnRefundStatus=fs.readFileSync(path.join(root,'backend/api/return-refund-status.js'),'utf8');
for(const required of ['getSupabaseUser','return_request_id','user_id=eq.','/v1/refunds/','Refund reference mismatch','Refund amount mismatch','return_processing','completed','approved','original_payment_method'])if(!returnRefundStatus.includes(required))errors.push(`backend/api/return-refund-status.js: customer return-refund reconciliation guard missing ${required}`);
const webhook=fs.readFileSync(path.join(root,'backend/api/razorpay-webhook.js'),'utf8');
for(const required of ['refund.created','refund.processed','refund.failed','x-razorpay-signature','expectedRefundAmount(','refund_pending','refund_id','refund_status','refund_reference','refund_amount','refund_updated_at','loadReturnRequestByRefund','updateReturnRefundStatus','return_refund_updated'])if(!webhook.includes(required))errors.push(`backend/api/razorpay-webhook.js: refund lifecycle/audit guard missing ${required}`);
for(const required of ['commit_order_inventory','commitOrderInventory','inventory_reconciled','inventory_committed'])if(!webhook.includes(required))errors.push(`backend/api/razorpay-webhook.js: payment inventory reconciliation missing ${required}`);
if(!/String\(refund\.status\s*\|\|\s*['"]{2}\)\.toLowerCase\(\)/.test(webhook))errors.push('backend/api/razorpay-webhook.js: refund webhook must validate processor refund status');
if(!/different_refund_reference/.test(webhook))errors.push('backend/api/razorpay-webhook.js: webhook must reject a different refund reference once an order refund is persisted');
if(!/refund_reference:\s*refundReference\(refund\)\s*\|\|\s*order\.refund_reference\s*\|\|\s*null/.test(webhook))errors.push('backend/api/razorpay-webhook.js: webhook must preserve an existing refund reference when later events omit acquirer data');
const checkout=fs.readFileSync(path.join(root,'checkout.html'),'utf8');
for(const required of ['id="addressSection"','id="addressState"','name="deliveryAddress"','customer_addresses','shipping_address:{id:address.id}','order-confirmation.html?id='])if(!checkout.includes(required))errors.push(`checkout.html: inline address/confirmation flow missing ${required}`);
if(/\.eq\(['"]is_default['"],true\)\.limit\(1\)\.maybeSingle\(\)/.test(checkout))errors.push('checkout.html: checkout must load selectable saved addresses, not only the default address');
const quoteCheckout=fs.readFileSync(path.join(root,'quote-checkout.html'),'utf8');
for(const required of ['Business quote checkout','bulk_quotes','bulk_quote_items','quoted_subtotal','quoted_gst','quoted_delivery','quoted_total','/api/create-quote-order','/api/verify-payment','purchase_order_no','Coupons and gift cards are not applied'])if(!quoteCheckout.includes(required))errors.push(`quote-checkout.html: secure accepted quote checkout missing ${required}`);
if(/coupon_code|gift_card_code/.test(quoteCheckout))errors.push('quote-checkout.html: negotiated quote checkout must not submit coupon or gift-card pricing');
const quoteOrder=fs.readFileSync(path.join(root,'backend/api/create-quote-order.js'),'utf8');
for(const required of ['bulk_quote_id','status!==\'accepted\'','quoted_subtotal','quoted_gst','quoted_delivery','quoted_total','business_billing_address:quote.business_billing_address','createRazorpayOrder','findExistingQuoteOrder'])if(!quoteOrder.includes(required))errors.push(`backend/api/create-quote-order.js: authoritative quote order guard missing ${required}`);
if(/calculate\(body\.items\)|getDiscounts\(/.test(quoteOrder))errors.push('backend/api/create-quote-order.js: accepted quote checkout must not reprice through retail cart/coupon logic');
const accountBusiness=fs.readFileSync(path.join(root,'account-business.js'),'utf8');
for(const required of ['create_bulk_quote_request','accept_bulk_quote','quote-checkout.html?quote=','data-accept-quote','ordered_at','Order placed','This quote expired before acceptance','already been used for an order','cannot be checked out again'])if(!accountBusiness.includes(required))errors.push(`account-business.js: business quote lifecycle missing ${required}`);
if(!/q\.status==='accepted'\?/.test(accountBusiness))errors.push('account-business.js: accepted quote checkout CTA guard missing');
if(!/q\.status==='ordered'\?/.test(accountBusiness))errors.push('account-business.js: ordered quote must render without a checkout CTA');
const adminQuotes=fs.readFileSync(path.join(root,'admin-business-quotes.js'),'utf8');
for(const required of ['finalize_bulk_quote','quoted_unit_price','quoted_subtotal','quoted_gst','quoted_delivery','ordered_at','LOCKED_STATUS','ordered','This quote is read-only'])if(!adminQuotes.includes(required))errors.push(`admin-business-quotes.js: authoritative admin quote lifecycle missing ${required}`);
if(/['"]accepted['"]/.test(adminQuotes.match(/const MANUAL_STATUS=[^;]+/)?.[0]||''))errors.push('admin-business-quotes.js: admin manual status list must not allow customer acceptance');
if(/['"]ordered['"]/.test(adminQuotes.match(/const MANUAL_STATUS=[^;]+/)?.[0]||''))errors.push('admin-business-quotes.js: admin manual status list must not allow ordered status');
const orderBusiness=fs.readFileSync(path.join(root,'order-business-details.js'),'utf8');
for(const required of ['business_name','business_gstin','business_billing_address','purchase_order_no','bulk_quote_id','does not claim that a statutory GST invoice'])if(!orderBusiness.includes(required))errors.push(`order-business-details.js: business order snapshot display missing ${required}`);
const orderDetails=fs.readFileSync(path.join(root,'order-details.html'),'utf8');
for(const anchor of ['trackingSection','actionsSection','helpSection'])if(!orderDetails.includes(`id="${anchor}"`))errors.push(`order-details.html: missing ${anchor} hash target`);
for(const required of ['id="refundFeedback"','aria-live="polite"','setRefundFeedback(','/api/refund-status'])if(!orderDetails.includes(required))errors.push(`order-details.html: inline refund feedback missing ${required}`);
if(/\balert\s*\(/.test(orderDetails))errors.push('order-details.html: refund/order status must use inline feedback, not browser alerts');
if(/razorpay_payment_id|razorpay_order_id/.test(orderDetails))errors.push('order-details.html: raw Razorpay identifiers must not be selected or exposed');
const refundTracker=fs.readFileSync(path.join(root,'order-refund-tracker.js'),'utf8');
for(const required of ['cancellation_reason','cancelled_at','refund_id','refund_status','refund_reference','refund_amount','refund_updated_at','Original payment method'])if(!refundTracker.includes(required))errors.push(`order-refund-tracker.js: persisted customer refund tracker missing ${required}`);
if(/razorpay_payment_id|razorpay_order_id/.test(refundTracker))errors.push('order-refund-tracker.js: raw Razorpay identifiers must not be selected or exposed');
const returnExchange=fs.readFileSync(path.join(root,'order-return-exchange.js'),'utf8');
for(const required of ['create_return_request','return_requests','exchange_size','return_refund','report_issue','p_item_index','p_quantity','p_reason','p_requested_size','Requested size is not a stock promise'])if(!returnExchange.includes(required))errors.push(`order-return-exchange.js: customer return/exchange flow missing ${required}`);
if(/razorpay_payment_id|razorpay_order_id/.test(returnExchange))errors.push('order-return-exchange.js: raw Razorpay identifiers must not be selected or exposed');
const confirmation=fs.readFileSync(path.join(root,'order-confirmation.html'),'utf8');
for(const required of ['id="orderRef"','id="items"','id="address"','id="payment"','id="detailsLink"'])if(!confirmation.includes(required))errors.push(`order-confirmation.html: missing ${required}`);
if(/razorpay_payment_id|razorpay_order_id/.test(confirmation))errors.push('order-confirmation.html: raw Razorpay identifiers must not be exposed');
const supabaseConfig=fs.readFileSync(path.join(root,'supabase-config.js'),'utf8');
const legacyInjectors=['account-dashboard.js','customer-addresses.js','order-tracking.js'];
for(const legacy of legacyInjectors){if(supabaseConfig.includes(`add('${legacy}`))errors.push(`supabase-config.js: premium account must not load legacy ${legacy} runtime injector`);if(fs.existsSync(path.join(root,legacy)))errors.push(`${legacy}: obsolete runtime injector must stay removed`)}
for(const required of ["variant-commerce.js?v=1','data-variant-commerce", "product-variants.js?v=1','data-product-variants", "order-refund-tracker.js?v=1','data-order-refund-tracker", "account-refunds.js?v=1','data-account-refunds", "order-return-exchange.js?v=1','data-order-return-exchange", "account-returns.js?v=2','data-account-returns", "account-business.js?v=4','data-account-business", "order-business-details.js?v=1','data-order-business-details", "admin-business-quotes.js?v=3','data-admin-business-quotes"])if(!supabaseConfig.includes(required))errors.push(`supabase-config.js: customer/admin commerce runtime injector missing ${required}`);
for(const file of ['variant-commerce.js','product-variants.js'])if(!fs.existsSync(path.join(root,file)))errors.push(`${file}: variant commerce runtime is missing`);
const variantCommerce=fs.readFileSync(path.join(root,'variant-commerce.js'),'utf8');
for(const required of ['variant_id','/api/quote-order','/api/create-order'])if(!variantCommerce.includes(required))errors.push(`variant-commerce.js: variant checkout propagation missing ${required}`);
const productVariants=fs.readFileSync(path.join(root,'product-variants.js'),'utf8');
for(const required of ['product_variants','get_variant_availability','variant-option','currently unavailable','FashionVariantCart'])if(!productVariants.includes(required))errors.push(`product-variants.js: inventory-backed product selector missing ${required}`);
const account=fs.readFileSync(path.join(root,'account.html'),'utf8');
for(const required of ['data-view="addresses"','id="addressesView"','id="addressForm"','customer_addresses','set_default_customer_address'])if(!account.includes(required))errors.push(`account.html: integrated address management missing ${required}`);
const accountRefunds=fs.readFileSync(path.join(root,'account-refunds.js'),'utf8');
for(const required of ['refund_id','refund_status','refund_reference','refund_amount','refund_updated_at','cancellation_reason','Original payment method','order-details.html?id=','hydrateAudit(','mergeAudit('])if(!accountRefunds.includes(required))errors.push(`account-refunds.js: persisted account refund view missing ${required}`);
if(/razorpay_payment_id|razorpay_order_id/.test(accountRefunds))errors.push('account-refunds.js: raw Razorpay identifiers must not be selected or exposed');
const accountReturns=fs.readFileSync(path.join(root,'account-returns.js'),'utf8');
for(const required of ['Returns & Exchanges','return_requests','requested_size','order-details.html?id=','#returns','exchange_size','return_refund','/api/return-refund-status','Check refund status','refund_id','refund_status','refund_reference','refund_amount','refund_updated_at'])if(!accountReturns.includes(required))errors.push(`account-returns.js: account returns/refunds view missing ${required}`);
if(/admin_note/.test(accountReturns))errors.push('account-returns.js: internal admin notes must not be exposed in customer return history');
if(!/Report an Issue/.test(accountReturns))errors.push('account-returns.js: account return history must label report-issue requests for customers');
if(/razorpay_payment_id|razorpay_order_id/.test(accountReturns))errors.push('account-returns.js: raw Razorpay identifiers must not be selected or exposed');
const adminReturns=fs.readFileSync(path.join(root,'admin-returns.js'),'utf8');
for(const required of ['/api/process-return-refund','Initiate refund','refund_id','refund_status','refund_reference','refund_amount','refund_updated_at'])if(!adminReturns.includes(required))errors.push(`admin-returns.js: admin return refund workflow missing ${required}`);
if(errors.length){console.error(errors.join('\n'));process.exit(1)}
console.log(`Source quality checks passed (${htmlFiles.length} HTML, ${jsFiles.length} JS)`);
