alter table public.products
  add column if not exists has_variants boolean not null default false;

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  sku text not null,
  title text,
  size text,
  color text,
  price_override numeric,
  image_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_variants_sku_not_blank check (length(btrim(sku)) between 1 and 120),
  constraint product_variants_title_length check (title is null or length(title) <= 160),
  constraint product_variants_size_length check (size is null or length(size) <= 80),
  constraint product_variants_color_length check (color is null or length(color) <= 80),
  constraint product_variants_price_override_positive check (price_override is null or price_override > 0),
  constraint product_variants_unique_sku unique (sku)
);

create index if not exists product_variants_product_active_idx
  on public.product_variants(product_id, is_active);

create table if not exists public.inventory_levels (
  variant_id bigint primary key references public.product_variants(id) on delete cascade,
  on_hand integer not null default 0,
  reserved integer not null default 0,
  reorder_level integer not null default 0,
  updated_at timestamptz not null default now(),
  constraint inventory_levels_nonnegative check (on_hand >= 0 and reserved >= 0 and reorder_level >= 0),
  constraint inventory_levels_reserved_not_above_on_hand check (reserved <= on_hand)
);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  variant_id bigint not null references public.product_variants(id) on delete cascade,
  movement_type text not null,
  quantity_delta integer not null,
  reference_type text,
  reference_id text,
  note text,
  actor_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint inventory_movements_type_check check (movement_type in ('stock_in','stock_out','reserve','release','adjustment','order_commit','return_restock')),
  constraint inventory_movements_nonzero check (quantity_delta <> 0),
  constraint inventory_movements_note_length check (note is null or length(note) <= 1000)
);

create index if not exists inventory_movements_variant_created_idx
  on public.inventory_movements(variant_id, created_at desc);

alter table public.product_variants enable row level security;
alter table public.inventory_levels enable row level security;
alter table public.inventory_movements enable row level security;

create policy product_variants_anon_read_active
  on public.product_variants for select to anon
  using (is_active = true and exists (
    select 1 from public.products p where p.id = product_id and p.is_active = true
  ));

create policy product_variants_authenticated_read
  on public.product_variants for select to authenticated
  using (
    (is_active = true and exists (select 1 from public.products p where p.id = product_id and p.is_active = true))
    or exists (select 1 from public.profiles pr where pr.id = auth.uid() and pr.is_admin = true)
  );

create policy product_variants_admin_insert
  on public.product_variants for insert to authenticated
  with check (exists (select 1 from public.profiles pr where pr.id = auth.uid() and pr.is_admin = true));

create policy product_variants_admin_update
  on public.product_variants for update to authenticated
  using (exists (select 1 from public.profiles pr where pr.id = auth.uid() and pr.is_admin = true))
  with check (exists (select 1 from public.profiles pr where pr.id = auth.uid() and pr.is_admin = true));

create policy product_variants_admin_delete
  on public.product_variants for delete to authenticated
  using (exists (select 1 from public.profiles pr where pr.id = auth.uid() and pr.is_admin = true));

create policy inventory_levels_admin_all
  on public.inventory_levels for all to authenticated
  using (exists (select 1 from public.profiles pr where pr.id = auth.uid() and pr.is_admin = true))
  with check (exists (select 1 from public.profiles pr where pr.id = auth.uid() and pr.is_admin = true));

create policy inventory_movements_admin_select
  on public.inventory_movements for select to authenticated
  using (exists (select 1 from public.profiles pr where pr.id = auth.uid() and pr.is_admin = true));

create policy inventory_movements_admin_insert
  on public.inventory_movements for insert to authenticated
  with check (exists (select 1 from public.profiles pr where pr.id = auth.uid() and pr.is_admin = true));

create or replace function public.get_variant_availability(p_product_id bigint)
returns table(variant_id bigint, in_stock boolean)
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select v.id,
         coalesce(i.on_hand - i.reserved, 0) > 0 as in_stock
  from public.product_variants v
  join public.products p on p.id = v.product_id
  left join public.inventory_levels i on i.variant_id = v.id
  where v.product_id = p_product_id
    and v.is_active = true
    and p.is_active = true
  order by v.id;
$$;

revoke all on function public.get_variant_availability(bigint) from public;
grant execute on function public.get_variant_availability(bigint) to anon, authenticated;
