alter table public.products
  add column if not exists bulk_enabled boolean not null default false,
  add column if not exists bulk_min_qty integer;

alter table public.products
  drop constraint if exists products_bulk_min_qty_check;
alter table public.products
  add constraint products_bulk_min_qty_check check (bulk_min_qty is null or bulk_min_qty >= 2);

create table if not exists public.business_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  business_name text not null,
  gstin text,
  billing_address jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint business_profiles_name_check check (char_length(trim(business_name)) between 2 and 160),
  constraint business_profiles_gstin_check check (gstin is null or gstin ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$')
);

alter table public.business_profiles enable row level security;
drop policy if exists business_profiles_select_own on public.business_profiles;
create policy business_profiles_select_own on public.business_profiles for select to authenticated using (auth.uid() = user_id);
drop policy if exists business_profiles_insert_own on public.business_profiles;
create policy business_profiles_insert_own on public.business_profiles for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists business_profiles_update_own on public.business_profiles;
create policy business_profiles_update_own on public.business_profiles for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table if not exists public.product_bulk_tiers (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  min_qty integer not null,
  unit_price numeric(12,2) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_bulk_tiers_qty_check check (min_qty >= 2),
  constraint product_bulk_tiers_price_check check (unit_price > 0),
  constraint product_bulk_tiers_unique unique(product_id,min_qty)
);

alter table public.product_bulk_tiers enable row level security;
drop policy if exists product_bulk_tiers_public_read on public.product_bulk_tiers;
create policy product_bulk_tiers_public_read on public.product_bulk_tiers for select to anon, authenticated using (true);

create table if not exists public.bulk_quotes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  business_name text not null,
  gstin text,
  status text not null default 'requested',
  customer_note text,
  admin_note text,
  quoted_total numeric(12,2),
  valid_until timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bulk_quotes_status_check check (status in ('requested','under_review','quoted','accepted','rejected','expired','cancelled')),
  constraint bulk_quotes_total_check check (quoted_total is null or quoted_total >= 0)
);

alter table public.bulk_quotes enable row level security;
drop policy if exists bulk_quotes_select_own on public.bulk_quotes;
create policy bulk_quotes_select_own on public.bulk_quotes for select to authenticated using (auth.uid() = user_id);
drop policy if exists bulk_quotes_insert_own on public.bulk_quotes;
create policy bulk_quotes_insert_own on public.bulk_quotes for insert to authenticated with check (auth.uid() = user_id);

create table if not exists public.bulk_quote_items (
  id bigint generated by default as identity primary key,
  quote_id bigint not null references public.bulk_quotes(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity integer not null,
  requested_unit_price numeric(12,2),
  quoted_unit_price numeric(12,2),
  created_at timestamptz not null default now(),
  constraint bulk_quote_items_qty_check check (quantity >= 2),
  constraint bulk_quote_items_requested_price_check check (requested_unit_price is null or requested_unit_price > 0),
  constraint bulk_quote_items_quoted_price_check check (quoted_unit_price is null or quoted_unit_price > 0)
);

alter table public.bulk_quote_items enable row level security;
drop policy if exists bulk_quote_items_select_own on public.bulk_quote_items;
create policy bulk_quote_items_select_own on public.bulk_quote_items for select to authenticated using (exists (select 1 from public.bulk_quotes q where q.id=quote_id and q.user_id=auth.uid()));
drop policy if exists bulk_quote_items_insert_own on public.bulk_quote_items;
create policy bulk_quote_items_insert_own on public.bulk_quote_items for insert to authenticated with check (exists (select 1 from public.bulk_quotes q where q.id=quote_id and q.user_id=auth.uid()));

create index if not exists product_bulk_tiers_product_qty_idx on public.product_bulk_tiers(product_id,min_qty);
create index if not exists bulk_quotes_user_created_idx on public.bulk_quotes(user_id,created_at desc);
create index if not exists bulk_quote_items_quote_idx on public.bulk_quote_items(quote_id);
