create table if not exists public.return_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_id bigint not null references public.orders(id) on delete cascade,
  item_index integer not null,
  request_type text not null,
  quantity integer not null default 1,
  reason text not null,
  requested_size text,
  status text not null default 'requested',
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz,
  constraint return_requests_item_index_nonnegative check (item_index >= 0),
  constraint return_requests_quantity_positive check (quantity > 0),
  constraint return_requests_type_check check (request_type in ('exchange_size','return_refund','report_issue')),
  constraint return_requests_status_check check (status in ('requested','under_review','approved','rejected','exchange_processing','return_processing','completed','cancelled')),
  constraint return_requests_reason_length check (char_length(btrim(reason)) between 3 and 500),
  constraint return_requests_exchange_size_check check (request_type <> 'exchange_size' or nullif(btrim(requested_size),'') is not null)
);

create index if not exists return_requests_user_created_idx on public.return_requests(user_id, created_at desc);
create index if not exists return_requests_order_idx on public.return_requests(order_id, created_at desc);

alter table public.return_requests enable row level security;

drop policy if exists "Customers can view own return requests" on public.return_requests;
create policy "Customers can view own return requests"
on public.return_requests for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Admins can view return requests" on public.return_requests;
create policy "Admins can view return requests"
on public.return_requests for select
to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin = true));

drop policy if exists "Admins can update return requests" on public.return_requests;
create policy "Admins can update return requests"
on public.return_requests for update
to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin = true))
with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin = true));

create or replace function public.create_return_request(
  p_order_id bigint,
  p_item_index integer,
  p_request_type text,
  p_quantity integer,
  p_reason text,
  p_requested_size text default null
)
returns public.return_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_order public.orders%rowtype;
  v_item jsonb;
  v_item_qty integer;
  v_request public.return_requests%rowtype;
begin
  if v_uid is null then raise exception 'Authentication required'; end if;
  if p_request_type not in ('exchange_size','return_refund','report_issue') then raise exception 'Invalid request type'; end if;
  if p_item_index is null or p_item_index < 0 then raise exception 'Invalid order item'; end if;
  if p_quantity is null or p_quantity < 1 then raise exception 'Invalid quantity'; end if;
  if char_length(btrim(coalesce(p_reason,''))) < 3 or char_length(btrim(coalesce(p_reason,''))) > 500 then raise exception 'Please provide a valid reason'; end if;
  if p_request_type = 'exchange_size' and nullif(btrim(coalesce(p_requested_size,'')),'') is null then raise exception 'Requested size is required for exchange'; end if;

  select * into v_order from public.orders where id = p_order_id and user_id = v_uid limit 1;
  if not found then raise exception 'Order not found'; end if;
  if coalesce(v_order.fulfillment_status,'') <> 'delivered' then raise exception 'Returns and exchanges are available after delivery'; end if;

  v_item := v_order.items -> p_item_index;
  if v_item is null then raise exception 'Order item not found'; end if;
  v_item_qty := greatest(1, coalesce((v_item->>'qty')::integer, (v_item->>'quantity')::integer, 1));
  if p_quantity > v_item_qty then raise exception 'Requested quantity exceeds ordered quantity'; end if;

  if exists (
    select 1 from public.return_requests r
    where r.user_id = v_uid and r.order_id = p_order_id and r.item_index = p_item_index
      and r.status in ('requested','under_review','approved','exchange_processing','return_processing')
  ) then raise exception 'A request for this item is already active'; end if;

  insert into public.return_requests(user_id,order_id,item_index,request_type,quantity,reason,requested_size)
  values(v_uid,p_order_id,p_item_index,p_request_type,p_quantity,btrim(p_reason),nullif(btrim(coalesce(p_requested_size,'')),''))
  returning * into v_request;
  return v_request;
end;
$$;

revoke all on function public.create_return_request(bigint,integer,text,integer,text,text) from public;
grant execute on function public.create_return_request(bigint,integer,text,integer,text,text) to authenticated;
