create table if not exists public.seller_compliance_profiles (
  seller_id uuid primary key references public.seller_profiles(user_id) on delete cascade,
  legal_name text,
  trade_name text,
  entity_type text not null default 'individual' check (entity_type in ('individual','business','manufacturer','wholesaler')),
  primary_category text,
  gst_registered boolean not null default false,
  pan_last4 text,
  gstin_last4 text,
  verification_status text not null default 'draft' check (verification_status in ('draft','pending_review','verified','rejected')),
  rejection_reason text,
  submitted_at timestamptz,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seller_payout_profiles (
  seller_id uuid primary key references public.seller_profiles(user_id) on delete cascade,
  account_holder_name text,
  bank_name text,
  ifsc text,
  account_number_last4 text,
  account_type text not null default 'current' check (account_type in ('current','savings')),
  provider_fund_account_ref text,
  verification_status text not null default 'draft' check (verification_status in ('draft','pending_review','verified','rejected')),
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seller_pickup_locations (
  id bigint generated by default as identity primary key,
  seller_id uuid not null references public.seller_profiles(user_id) on delete cascade,
  label text not null default 'Primary pickup',
  contact_name text not null,
  phone text not null,
  line1 text not null,
  line2 text,
  city text not null,
  state text not null,
  pincode text not null,
  landmark text,
  is_default boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (phone ~ '^[0-9]{10}$'),
  check (pincode ~ '^[1-9][0-9]{5}$')
);
create unique index if not exists seller_pickup_one_default_idx on public.seller_pickup_locations(seller_id) where is_default and is_active;

create table if not exists public.seller_settlements (
  id bigint generated by default as identity primary key,
  seller_id uuid not null references public.seller_profiles(user_id) on delete cascade,
  period_start date not null,
  period_end date not null,
  gross_amount numeric(14,2) not null default 0,
  fees_amount numeric(14,2) not null default 0,
  refunds_amount numeric(14,2) not null default 0,
  net_amount numeric(14,2) not null default 0,
  currency text not null default 'INR',
  status text not null default 'pending' check (status in ('pending','processing','paid','failed','held')),
  provider_payout_ref text,
  failure_reason text,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (period_end >= period_start)
);

alter table public.seller_compliance_profiles enable row level security;
alter table public.seller_payout_profiles enable row level security;
alter table public.seller_pickup_locations enable row level security;
alter table public.seller_settlements enable row level security;

drop policy if exists seller_compliance_read_own on public.seller_compliance_profiles;
create policy seller_compliance_read_own on public.seller_compliance_profiles for select to authenticated using (seller_id = auth.uid());
drop policy if exists seller_payout_read_own on public.seller_payout_profiles;
create policy seller_payout_read_own on public.seller_payout_profiles for select to authenticated using (seller_id = auth.uid());
drop policy if exists seller_pickup_read_own on public.seller_pickup_locations;
create policy seller_pickup_read_own on public.seller_pickup_locations for select to authenticated using (seller_id = auth.uid());
drop policy if exists seller_settlement_read_own on public.seller_settlements;
create policy seller_settlement_read_own on public.seller_settlements for select to authenticated using (seller_id = auth.uid());

revoke insert, update, delete on public.seller_compliance_profiles from authenticated;
revoke insert, update, delete on public.seller_payout_profiles from authenticated;
revoke insert, update, delete on public.seller_pickup_locations from authenticated;
revoke insert, update, delete on public.seller_settlements from authenticated;
grant select on public.seller_compliance_profiles, public.seller_payout_profiles, public.seller_pickup_locations, public.seller_settlements to authenticated;

create or replace function public.get_seller_finance_profile() returns jsonb
language sql stable security definer set search_path = public
as $$
  select jsonb_build_object(
    'compliance', coalesce((select to_jsonb(c) - 'seller_id' from public.seller_compliance_profiles c where c.seller_id=auth.uid()), '{}'::jsonb),
    'payout', coalesce((select (to_jsonb(p) - 'seller_id' - 'provider_fund_account_ref') from public.seller_payout_profiles p where p.seller_id=auth.uid()), '{}'::jsonb),
    'pickup_locations', coalesce((select jsonb_agg(to_jsonb(l) - 'seller_id' order by l.is_default desc,l.updated_at desc) from public.seller_pickup_locations l where l.seller_id=auth.uid() and l.is_active), '[]'::jsonb),
    'settlements', coalesce((select jsonb_agg((to_jsonb(s) - 'seller_id' - 'provider_payout_ref') order by s.period_end desc,s.id desc) from public.seller_settlements s where s.seller_id=auth.uid()), '[]'::jsonb)
  )
$$;

create or replace function public.save_seller_compliance_profile(
  p_legal_name text,p_trade_name text,p_entity_type text,p_primary_category text,p_gst_registered boolean,p_pan text,p_gstin text,
  p_account_holder_name text,p_bank_name text,p_ifsc text,p_account_number text,p_account_type text
) returns jsonb language plpgsql security definer set search_path = public as $$
declare v_seller uuid:=auth.uid(); v_pan text:=upper(regexp_replace(coalesce(p_pan,''),'[^A-Za-z0-9]','','g')); v_gstin text:=upper(regexp_replace(coalesce(p_gstin,''),'[^A-Za-z0-9]','','g')); v_account text:=regexp_replace(coalesce(p_account_number,''),'[^0-9]','','g'); v_ifsc text:=upper(trim(coalesce(p_ifsc,'')));
begin
  if v_seller is null or not exists(select 1 from public.seller_profiles where user_id=v_seller and status='active') then raise exception 'Active seller account required'; end if;
  if nullif(trim(coalesce(p_legal_name,'')),'') is null then raise exception 'Legal name is required'; end if;
  if coalesce(p_entity_type,'') not in ('individual','business','manufacturer','wholesaler') then raise exception 'Invalid entity type'; end if;
  if v_pan<>'' and v_pan !~ '^[A-Z]{5}[0-9]{4}[A-Z]$' then raise exception 'Invalid PAN format'; end if;
  if coalesce(p_gst_registered,false) and v_gstin !~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$' then raise exception 'Valid GSTIN is required'; end if;
  if nullif(trim(coalesce(p_account_holder_name,'')),'') is not null or nullif(trim(coalesce(p_bank_name,'')),'') is not null or v_ifsc<>'' or v_account<>'' then
    if v_ifsc !~ '^[A-Z]{4}0[A-Z0-9]{6}$' then raise exception 'Invalid IFSC format'; end if;
    if v_account !~ '^[0-9]{9,18}$' then raise exception 'Invalid bank account number'; end if;
    if coalesce(p_account_type,'') not in ('current','savings') then raise exception 'Invalid account type'; end if;
  end if;
  insert into public.seller_compliance_profiles(seller_id,legal_name,trade_name,entity_type,primary_category,gst_registered,pan_last4,gstin_last4,verification_status,rejection_reason,updated_at)
  values(v_seller,trim(p_legal_name),nullif(trim(p_trade_name),''),p_entity_type,nullif(trim(p_primary_category),''),coalesce(p_gst_registered,false),case when v_pan='' then null else right(v_pan,4) end,case when v_gstin='' then null else right(v_gstin,4) end,'draft',null,now())
  on conflict(seller_id) do update set legal_name=excluded.legal_name,trade_name=excluded.trade_name,entity_type=excluded.entity_type,primary_category=excluded.primary_category,gst_registered=excluded.gst_registered,pan_last4=excluded.pan_last4,gstin_last4=excluded.gstin_last4,verification_status=case when seller_compliance_profiles.verification_status='verified' then 'verified' else 'draft' end,rejection_reason=null,updated_at=now();
  if nullif(trim(coalesce(p_account_holder_name,'')),'') is not null or nullif(trim(coalesce(p_bank_name,'')),'') is not null or v_ifsc<>'' or v_account<>'' then
    insert into public.seller_payout_profiles(seller_id,account_holder_name,bank_name,ifsc,account_number_last4,account_type,verification_status,rejection_reason,updated_at)
    values(v_seller,trim(p_account_holder_name),trim(p_bank_name),v_ifsc,right(v_account,4),p_account_type,'draft',null,now())
    on conflict(seller_id) do update set account_holder_name=excluded.account_holder_name,bank_name=excluded.bank_name,ifsc=excluded.ifsc,account_number_last4=excluded.account_number_last4,account_type=excluded.account_type,verification_status=case when seller_payout_profiles.verification_status='verified' then 'verified' else 'draft' end,rejection_reason=null,updated_at=now();
  end if;
  return public.get_seller_finance_profile();
end $$;

create or replace function public.save_seller_pickup_location(p_location_id bigint,p_label text,p_contact_name text,p_phone text,p_line1 text,p_line2 text,p_city text,p_state text,p_pincode text,p_landmark text,p_is_default boolean) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_seller uuid:=auth.uid(); v_id bigint; v_phone text:=regexp_replace(coalesce(p_phone,''),'[^0-9]','','g'); v_pin text:=regexp_replace(coalesce(p_pincode,''),'[^0-9]','','g');
begin
  if v_seller is null or not exists(select 1 from public.seller_profiles where user_id=v_seller and status='active') then raise exception 'Active seller account required'; end if;
  if nullif(trim(coalesce(p_contact_name,'')),'') is null or nullif(trim(coalesce(p_line1,'')),'') is null or nullif(trim(coalesce(p_city,'')),'') is null or nullif(trim(coalesce(p_state,'')),'') is null then raise exception 'Complete pickup address'; end if;
  if v_phone !~ '^[0-9]{10}$' then raise exception 'Invalid phone number'; end if; if v_pin !~ '^[1-9][0-9]{5}$' then raise exception 'Invalid pincode'; end if;
  if coalesce(p_is_default,false) then update public.seller_pickup_locations set is_default=false,updated_at=now() where seller_id=v_seller and is_default; end if;
  if p_location_id is null then insert into public.seller_pickup_locations(seller_id,label,contact_name,phone,line1,line2,city,state,pincode,landmark,is_default) values(v_seller,coalesce(nullif(trim(p_label),''),'Primary pickup'),trim(p_contact_name),v_phone,trim(p_line1),nullif(trim(p_line2),''),trim(p_city),trim(p_state),v_pin,nullif(trim(p_landmark),''),coalesce(p_is_default,false)) returning id into v_id;
  else update public.seller_pickup_locations set label=coalesce(nullif(trim(p_label),''),'Primary pickup'),contact_name=trim(p_contact_name),phone=v_phone,line1=trim(p_line1),line2=nullif(trim(p_line2),''),city=trim(p_city),state=trim(p_state),pincode=v_pin,landmark=nullif(trim(p_landmark),''),is_default=coalesce(p_is_default,false),updated_at=now() where id=p_location_id and seller_id=v_seller returning id into v_id; if v_id is null then raise exception 'Pickup location not found'; end if; end if;
  return public.get_seller_finance_profile();
end $$;

create or replace function public.submit_seller_verification() returns jsonb language plpgsql security definer set search_path=public as $$
declare v_seller uuid:=auth.uid(); begin
  if v_seller is null then raise exception 'Authentication required'; end if;
  if not exists(select 1 from public.seller_compliance_profiles where seller_id=v_seller and legal_name is not null and pan_last4 is not null and (not gst_registered or gstin_last4 is not null)) then raise exception 'Complete business identity first'; end if;
  if not exists(select 1 from public.seller_payout_profiles where seller_id=v_seller and account_holder_name is not null and bank_name is not null and ifsc is not null and account_number_last4 is not null) then raise exception 'Complete payout account first'; end if;
  if not exists(select 1 from public.seller_pickup_locations where seller_id=v_seller and is_active) then raise exception 'Add a pickup location first'; end if;
  update public.seller_compliance_profiles set verification_status='pending_review',submitted_at=now(),rejection_reason=null,updated_at=now() where seller_id=v_seller and verification_status<>'verified';
  update public.seller_payout_profiles set verification_status='pending_review',rejection_reason=null,updated_at=now() where seller_id=v_seller and verification_status<>'verified';
  return public.get_seller_finance_profile();
end $$;

grant execute on function public.save_seller_compliance_profile(text,text,text,text,boolean,text,text,text,text,text,text,text) to authenticated;
grant execute on function public.save_seller_pickup_location(bigint,text,text,text,text,text,text,text,text,text,boolean) to authenticated;
grant execute on function public.submit_seller_verification() to authenticated;
grant execute on function public.get_seller_finance_profile() to authenticated;
