-- Recovery bundle reconstructed from production supabase_migrations.schema_migrations.
-- It replays the lost 20260918194908..20260918195952 migrations in their original order.

-- BEGIN RECOVERED 20260918194908_seller_marketplace_approval_workflow
create table if not exists public.seller_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  store_name text not null check (char_length(trim(store_name)) between 2 and 120),
  seller_type text not null default 'individual' check (seller_type in ('individual','business','manufacturer','wholesaler')),
  phone text,
  status text not null default 'active' check (status in ('active','suspended','pending')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seller_product_submissions (
  id bigint generated by default as identity primary key,
  seller_id uuid not null references auth.users(id) on delete cascade,
  sku text not null,
  name text not null,
  category text,
  price numeric not null check (price > 0),
  mrp numeric check (mrp is null or mrp >= price),
  gst_rate numeric not null default 18 check (gst_rate >= 0 and gst_rate <= 100),
  description text,
  image_url text,
  brand text,
  country_origin text,
  hsn text,
  stock integer not null default 0 check (stock >= 0),
  bulk_enabled boolean not null default false,
  bulk_min_qty integer,
  bulk_price numeric,
  submission_payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  rejection_reason text,
  approved_product_id bigint references public.products(id) on delete set null,
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (seller_id, sku)
);

create index if not exists seller_product_submissions_seller_status_idx on public.seller_product_submissions(seller_id,status,updated_at desc);
create index if not exists seller_product_submissions_status_idx on public.seller_product_submissions(status,submitted_at asc);

alter table public.seller_profiles enable row level security;
alter table public.seller_product_submissions enable row level security;

revoke all on public.seller_profiles from anon;
revoke all on public.seller_product_submissions from anon;
grant select on public.seller_profiles to authenticated;
grant select on public.seller_product_submissions to authenticated;

create policy seller_profiles_owner_select on public.seller_profiles for select to authenticated
using ((select auth.uid()) = user_id or exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.is_admin=true));

create policy seller_submissions_owner_or_admin_select on public.seller_product_submissions for select to authenticated
using (seller_id=(select auth.uid()) or exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.is_admin=true));

create or replace function public.register_seller_profile(p_store_name text,p_seller_type text default 'individual',p_phone text default null)
returns public.seller_profiles
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare v_uid uuid; v_row public.seller_profiles;
begin
  v_uid := auth.uid();
  if v_uid is null then raise exception 'Authentication required'; end if;
  if trim(coalesce(p_store_name,''))='' then raise exception 'Store name is required'; end if;
  if p_seller_type not in ('individual','business','manufacturer','wholesaler') then raise exception 'Invalid seller type'; end if;
  insert into public.seller_profiles(user_id,store_name,seller_type,phone,updated_at)
  values(v_uid,trim(p_store_name),p_seller_type,nullif(trim(coalesce(p_phone,'')),''),now())
  on conflict(user_id) do update set store_name=excluded.store_name,seller_type=excluded.seller_type,phone=excluded.phone,updated_at=now()
  returning * into v_row;
  return v_row;
end;$$;

create or replace function public.submit_seller_product(
 p_submission_id bigint,
 p_sku text,p_name text,p_category text,p_price numeric,p_mrp numeric,p_gst_rate numeric,
 p_description text,p_image_url text,p_brand text,p_country_origin text,p_hsn text,p_stock integer,
 p_bulk_enabled boolean,p_bulk_min_qty integer,p_bulk_price numeric,p_submission_payload jsonb default '{}'::jsonb)
returns public.seller_product_submissions
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare v_uid uuid; v_row public.seller_product_submissions; v_profile public.seller_profiles;
begin
  v_uid:=auth.uid(); if v_uid is null then raise exception 'Authentication required'; end if;
  select * into v_profile from public.seller_profiles where user_id=v_uid and status='active';
  if not found then raise exception 'Active seller profile required'; end if;
  if trim(coalesce(p_sku,''))='' or trim(coalesce(p_name,''))='' then raise exception 'SKU and name are required'; end if;
  if p_price is null or p_price<=0 then raise exception 'Price must be greater than zero'; end if;
  if p_mrp is not null and p_mrp<p_price then raise exception 'MRP cannot be lower than price'; end if;
  if coalesce(p_gst_rate,18)<0 or coalesce(p_gst_rate,18)>100 then raise exception 'Invalid GST rate'; end if;
  if coalesce(p_stock,0)<0 then raise exception 'Stock cannot be negative'; end if;
  if coalesce(p_bulk_enabled,false) and (coalesce(p_bulk_min_qty,0)<2 or p_bulk_price is null or p_bulk_price<=0 or p_bulk_price>p_price) then raise exception 'Invalid bulk pricing'; end if;
  if p_submission_id is null then
    insert into public.seller_product_submissions(seller_id,sku,name,category,price,mrp,gst_rate,description,image_url,brand,country_origin,hsn,stock,bulk_enabled,bulk_min_qty,bulk_price,submission_payload,status,rejection_reason,approved_product_id,reviewed_at,reviewed_by,submitted_at,updated_at)
    values(v_uid,upper(trim(p_sku)),trim(p_name),nullif(trim(coalesce(p_category,'')),''),p_price,p_mrp,coalesce(p_gst_rate,18),nullif(trim(coalesce(p_description,'')),''),nullif(trim(coalesce(p_image_url,'')),''),nullif(trim(coalesce(p_brand,'')),''),nullif(trim(coalesce(p_country_origin,'')),''),nullif(trim(coalesce(p_hsn,'')),''),coalesce(p_stock,0),coalesce(p_bulk_enabled,false),case when coalesce(p_bulk_enabled,false) then p_bulk_min_qty else null end,case when coalesce(p_bulk_enabled,false) then p_bulk_price else null end,coalesce(p_submission_payload,'{}'::jsonb),'pending',null,null,null,null,now(),now()) returning * into v_row;
  else
    update public.seller_product_submissions set sku=upper(trim(p_sku)),name=trim(p_name),category=nullif(trim(coalesce(p_category,'')),''),price=p_price,mrp=p_mrp,gst_rate=coalesce(p_gst_rate,18),description=nullif(trim(coalesce(p_description,'')),''),image_url=nullif(trim(coalesce(p_image_url,'')),''),brand=nullif(trim(coalesce(p_brand,'')),''),country_origin=nullif(trim(coalesce(p_country_origin,'')),''),hsn=nullif(trim(coalesce(p_hsn,'')),''),stock=coalesce(p_stock,0),bulk_enabled=coalesce(p_bulk_enabled,false),bulk_min_qty=case when coalesce(p_bulk_enabled,false) then p_bulk_min_qty else null end,bulk_price=case when coalesce(p_bulk_enabled,false) then p_bulk_price else null end,submission_payload=coalesce(p_submission_payload,'{}'::jsonb),status='pending',rejection_reason=null,approved_product_id=null,reviewed_at=null,reviewed_by=null,submitted_at=now(),updated_at=now()
    where id=p_submission_id and seller_id=v_uid and status in ('pending','rejected') returning * into v_row;
    if not found then raise exception 'Submission not found or cannot be edited'; end if;
  end if;
  return v_row;
end;$$;

create or replace function public.admin_review_seller_product(p_submission_id bigint,p_decision text,p_rejection_reason text default null)
returns public.seller_product_submissions
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare v_uid uuid; v_sub public.seller_product_submissions; v_product_id bigint;
begin
  v_uid:=auth.uid(); if v_uid is null then raise exception 'Authentication required'; end if;
  if not exists(select 1 from public.profiles p where p.id=v_uid and p.is_admin=true) then raise exception 'Administrator access required'; end if;
  if p_decision not in ('approve','reject') then raise exception 'Decision must be approve or reject'; end if;
  select * into v_sub from public.seller_product_submissions where id=p_submission_id for update;
  if not found then raise exception 'Submission not found'; end if;
  if v_sub.status<>'pending' then raise exception 'Only pending submissions can be reviewed'; end if;
  if p_decision='reject' then
    if trim(coalesce(p_rejection_reason,''))='' then raise exception 'Rejection reason is required'; end if;
    update public.seller_product_submissions set status='rejected',rejection_reason=trim(p_rejection_reason),approved_product_id=null,reviewed_at=now(),reviewed_by=v_uid,updated_at=now() where id=p_submission_id returning * into v_sub;
    return v_sub;
  end if;
  insert into public.products(name,category,cost,price,rating,reviews,image_url,badge,description,is_active,gst_rate,bulk_enabled,bulk_min_qty,has_variants,updated_at)
  values(v_sub.name,v_sub.category,0,v_sub.price,0,0,v_sub.image_url,null,v_sub.description,true,v_sub.gst_rate,v_sub.bulk_enabled,v_sub.bulk_min_qty,false,now())
  returning id into v_product_id;
  update public.seller_product_submissions set status='approved',rejection_reason=null,approved_product_id=v_product_id,reviewed_at=now(),reviewed_by=v_uid,updated_at=now() where id=p_submission_id returning * into v_sub;
  return v_sub;
end;$$;

revoke all on function public.register_seller_profile(text,text,text) from public,anon;
revoke all on function public.submit_seller_product(bigint,text,text,text,numeric,numeric,numeric,text,text,text,text,text,integer,boolean,integer,numeric,jsonb) from public,anon;
revoke all on function public.admin_review_seller_product(bigint,text,text) from public,anon;
grant execute on function public.register_seller_profile(text,text,text) to authenticated;
grant execute on function public.submit_seller_product(bigint,text,text,text,numeric,numeric,numeric,text,text,text,text,text,integer,boolean,integer,numeric,jsonb) to authenticated;
grant execute on function public.admin_review_seller_product(bigint,text,text) to authenticated;

grant usage,select on sequence public.seller_product_submissions_id_seq to authenticated;
-- END RECOVERED 20260918194908

-- BEGIN RECOVERED 20260918195009_seller_approval_revision_and_product_ownership
alter table public.products add column if not exists source_seller_id uuid references auth.users(id) on delete set null;
alter table public.products add column if not exists seller_submission_id bigint references public.seller_product_submissions(id) on delete set null;
create unique index if not exists products_seller_submission_uidx on public.products(seller_submission_id) where seller_submission_id is not null;

create or replace function public.submit_seller_product(
 p_submission_id bigint,
 p_sku text,p_name text,p_category text,p_price numeric,p_mrp numeric,p_gst_rate numeric,
 p_description text,p_image_url text,p_brand text,p_country_origin text,p_hsn text,p_stock integer,
 p_bulk_enabled boolean,p_bulk_min_qty integer,p_bulk_price numeric,p_submission_payload jsonb default '{}'::jsonb)
returns public.seller_product_submissions
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare v_uid uuid; v_row public.seller_product_submissions; v_profile public.seller_profiles;
begin
  v_uid:=auth.uid(); if v_uid is null then raise exception 'Authentication required'; end if;
  select * into v_profile from public.seller_profiles where user_id=v_uid and status='active';
  if not found then raise exception 'Active seller profile required'; end if;
  if trim(coalesce(p_sku,''))='' or trim(coalesce(p_name,''))='' then raise exception 'SKU and name are required'; end if;
  if p_price is null or p_price<=0 then raise exception 'Price must be greater than zero'; end if;
  if p_mrp is not null and p_mrp<p_price then raise exception 'MRP cannot be lower than price'; end if;
  if coalesce(p_gst_rate,18)<0 or coalesce(p_gst_rate,18)>100 then raise exception 'Invalid GST rate'; end if;
  if coalesce(p_stock,0)<0 then raise exception 'Stock cannot be negative'; end if;
  if coalesce(p_bulk_enabled,false) and (coalesce(p_bulk_min_qty,0)<2 or p_bulk_price is null or p_bulk_price<=0 or p_bulk_price>p_price) then raise exception 'Invalid bulk pricing'; end if;
  if p_submission_id is null then
    insert into public.seller_product_submissions(seller_id,sku,name,category,price,mrp,gst_rate,description,image_url,brand,country_origin,hsn,stock,bulk_enabled,bulk_min_qty,bulk_price,submission_payload,status,rejection_reason,approved_product_id,reviewed_at,reviewed_by,submitted_at,updated_at)
    values(v_uid,upper(trim(p_sku)),trim(p_name),nullif(trim(coalesce(p_category,'')),''),p_price,p_mrp,coalesce(p_gst_rate,18),nullif(trim(coalesce(p_description,'')),''),nullif(trim(coalesce(p_image_url,'')),''),nullif(trim(coalesce(p_brand,'')),''),nullif(trim(coalesce(p_country_origin,'')),''),nullif(trim(coalesce(p_hsn,'')),''),coalesce(p_stock,0),coalesce(p_bulk_enabled,false),case when coalesce(p_bulk_enabled,false) then p_bulk_min_qty else null end,case when coalesce(p_bulk_enabled,false) then p_bulk_price else null end,coalesce(p_submission_payload,'{}'::jsonb),'pending',null,null,null,null,now(),now()) returning * into v_row;
  else
    update public.seller_product_submissions set sku=upper(trim(p_sku)),name=trim(p_name),category=nullif(trim(coalesce(p_category,'')),''),price=p_price,mrp=p_mrp,gst_rate=coalesce(p_gst_rate,18),description=nullif(trim(coalesce(p_description,'')),''),image_url=nullif(trim(coalesce(p_image_url,'')),''),brand=nullif(trim(coalesce(p_brand,'')),''),country_origin=nullif(trim(coalesce(p_country_origin,'')),''),hsn=nullif(trim(coalesce(p_hsn,'')),''),stock=coalesce(p_stock,0),bulk_enabled=coalesce(p_bulk_enabled,false),bulk_min_qty=case when coalesce(p_bulk_enabled,false) then p_bulk_min_qty else null end,bulk_price=case when coalesce(p_bulk_enabled,false) then p_bulk_price else null end,submission_payload=coalesce(p_submission_payload,'{}'::jsonb),status='pending',rejection_reason=null,reviewed_at=null,reviewed_by=null,submitted_at=now(),updated_at=now()
    where id=p_submission_id and seller_id=v_uid returning * into v_row;
    if not found then raise exception 'Submission not found'; end if;
    if v_row.approved_product_id is not null then update public.products set is_active=false,updated_at=now() where id=v_row.approved_product_id; end if;
  end if;
  return v_row;
end;$$;

create or replace function public.admin_review_seller_product(p_submission_id bigint,p_decision text,p_rejection_reason text default null)
returns public.seller_product_submissions
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare v_uid uuid; v_sub public.seller_product_submissions; v_product_id bigint;
begin
  v_uid:=auth.uid(); if v_uid is null then raise exception 'Authentication required'; end if;
  if not exists(select 1 from public.profiles p where p.id=v_uid and p.is_admin=true) then raise exception 'Administrator access required'; end if;
  if p_decision not in ('approve','reject') then raise exception 'Decision must be approve or reject'; end if;
  select * into v_sub from public.seller_product_submissions where id=p_submission_id for update;
  if not found then raise exception 'Submission not found'; end if;
  if v_sub.status<>'pending' then raise exception 'Only pending submissions can be reviewed'; end if;
  if p_decision='reject' then
    if trim(coalesce(p_rejection_reason,''))='' then raise exception 'Rejection reason is required'; end if;
    if v_sub.approved_product_id is not null then update public.products set is_active=false,updated_at=now() where id=v_sub.approved_product_id; end if;
    update public.seller_product_submissions set status='rejected',rejection_reason=trim(p_rejection_reason),reviewed_at=now(),reviewed_by=v_uid,updated_at=now() where id=p_submission_id returning * into v_sub;
    return v_sub;
  end if;
  if v_sub.approved_product_id is not null then
    update public.products set name=v_sub.name,category=v_sub.category,price=v_sub.price,image_url=v_sub.image_url,description=v_sub.description,is_active=true,gst_rate=v_sub.gst_rate,bulk_enabled=v_sub.bulk_enabled,bulk_min_qty=v_sub.bulk_min_qty,source_seller_id=v_sub.seller_id,seller_submission_id=v_sub.id,updated_at=now() where id=v_sub.approved_product_id returning id into v_product_id;
  else
    insert into public.products(name,category,cost,price,rating,reviews,image_url,badge,description,is_active,gst_rate,bulk_enabled,bulk_min_qty,has_variants,source_seller_id,seller_submission_id,updated_at)
    values(v_sub.name,v_sub.category,0,v_sub.price,0,0,v_sub.image_url,null,v_sub.description,true,v_sub.gst_rate,v_sub.bulk_enabled,v_sub.bulk_min_qty,false,v_sub.seller_id,v_sub.id,now()) returning id into v_product_id;
  end if;
  update public.seller_product_submissions set status='approved',rejection_reason=null,approved_product_id=v_product_id,reviewed_at=now(),reviewed_by=v_uid,updated_at=now() where id=p_submission_id returning * into v_sub;
  return v_sub;
end;$$;

create or replace function public.withdraw_seller_product(p_submission_id bigint)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare v_uid uuid; v_sub public.seller_product_submissions;
begin
  v_uid:=auth.uid(); if v_uid is null then raise exception 'Authentication required'; end if;
  select * into v_sub from public.seller_product_submissions where id=p_submission_id and seller_id=v_uid for update;
  if not found then raise exception 'Submission not found'; end if;
  if v_sub.approved_product_id is not null then update public.products set is_active=false,updated_at=now() where id=v_sub.approved_product_id; end if;
  delete from public.seller_product_submissions where id=p_submission_id and seller_id=v_uid;
  return true;
end;$$;

revoke all on function public.withdraw_seller_product(bigint) from public,anon;
grant execute on function public.withdraw_seller_product(bigint) to authenticated;
-- END RECOVERED 20260918195009

-- BEGIN RECOVERED 20260918195035_seller_approval_variants_inventory
create or replace function public.admin_review_seller_product(p_submission_id bigint,p_decision text,p_rejection_reason text default null)
returns public.seller_product_submissions
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_uid uuid;
  v_sub public.seller_product_submissions;
  v_product_id bigint;
  v_variants jsonb;
  v_variant jsonb;
  v_variant_id bigint;
  v_has_variants boolean;
  v_variant_stock integer;
begin
  v_uid:=auth.uid(); if v_uid is null then raise exception 'Authentication required'; end if;
  if not exists(select 1 from public.profiles p where p.id=v_uid and p.is_admin=true) then raise exception 'Administrator access required'; end if;
  if p_decision not in ('approve','reject') then raise exception 'Decision must be approve or reject'; end if;
  select * into v_sub from public.seller_product_submissions where id=p_submission_id for update;
  if not found then raise exception 'Submission not found'; end if;
  if v_sub.status<>'pending' then raise exception 'Only pending submissions can be reviewed'; end if;
  if p_decision='reject' then
    if trim(coalesce(p_rejection_reason,''))='' then raise exception 'Rejection reason is required'; end if;
    if v_sub.approved_product_id is not null then update public.products set is_active=false,updated_at=now() where id=v_sub.approved_product_id; end if;
    update public.seller_product_submissions set status='rejected',rejection_reason=trim(p_rejection_reason),reviewed_at=now(),reviewed_by=v_uid,updated_at=now() where id=p_submission_id returning * into v_sub;
    return v_sub;
  end if;

  v_variants := coalesce(v_sub.submission_payload->'variants','[]'::jsonb);
  v_has_variants := jsonb_typeof(v_variants)='array' and jsonb_array_length(v_variants)>0;

  if v_sub.approved_product_id is not null then
    update public.products set name=v_sub.name,category=v_sub.category,price=v_sub.price,image_url=v_sub.image_url,description=v_sub.description,is_active=true,gst_rate=v_sub.gst_rate,bulk_enabled=v_sub.bulk_enabled,bulk_min_qty=v_sub.bulk_min_qty,has_variants=v_has_variants,source_seller_id=v_sub.seller_id,seller_submission_id=v_sub.id,updated_at=now() where id=v_sub.approved_product_id returning id into v_product_id;
    delete from public.inventory_levels where variant_id in (select id from public.product_variants where product_id=v_product_id);
    delete from public.product_variants where product_id=v_product_id;
  else
    insert into public.products(name,category,cost,price,rating,reviews,image_url,badge,description,is_active,gst_rate,bulk_enabled,bulk_min_qty,has_variants,source_seller_id,seller_submission_id,updated_at)
    values(v_sub.name,v_sub.category,0,v_sub.price,0,0,v_sub.image_url,null,v_sub.description,true,v_sub.gst_rate,v_sub.bulk_enabled,v_sub.bulk_min_qty,v_has_variants,v_sub.seller_id,v_sub.id,now()) returning id into v_product_id;
  end if;

  if v_has_variants then
    for v_variant in select value from jsonb_array_elements(v_variants)
    loop
      if trim(coalesce(v_variant->>'sku',''))='' then raise exception 'Every variant requires a SKU'; end if;
      v_variant_stock:=greatest(0,coalesce((v_variant->>'stock')::integer,0));
      insert into public.product_variants(product_id,sku,title,size,color,price_override,image_url,is_active,updated_at)
      values(v_product_id,upper(trim(v_variant->>'sku')),nullif(trim(coalesce(v_variant->>'title','')),''),nullif(trim(coalesce(v_variant->>'size','')),''),nullif(trim(coalesce(v_variant->>'color','')),''),case when nullif(v_variant->>'priceOverride','') is null then null else (v_variant->>'priceOverride')::numeric end,nullif(trim(coalesce(v_variant->>'image','')),''),true,now())
      returning id into v_variant_id;
      insert into public.inventory_levels(variant_id,on_hand,reserved,reorder_level,updated_at)
      values(v_variant_id,v_variant_stock,0,greatest(0,coalesce((v_sub.submission_payload->>'lowStockThreshold')::integer,0)),now());
    end loop;
  end if;

  update public.seller_product_submissions set status='approved',rejection_reason=null,approved_product_id=v_product_id,reviewed_at=now(),reviewed_by=v_uid,updated_at=now() where id=p_submission_id returning * into v_sub;
  return v_sub;
end;$$;
-- END RECOVERED 20260918195035

-- BEGIN RECOVERED 20260918195427_seller_approval_bulk_tier_publish
create or replace function public.admin_review_seller_product(p_submission_id bigint,p_decision text,p_rejection_reason text default null)
returns public.seller_product_submissions
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_uid uuid; v_sub public.seller_product_submissions; v_product_id bigint; v_variants jsonb; v_variant jsonb; v_variant_id bigint; v_has_variants boolean; v_variant_stock integer;
begin
  v_uid:=auth.uid(); if v_uid is null then raise exception 'Authentication required'; end if;
  if not exists(select 1 from public.profiles p where p.id=v_uid and p.is_admin=true) then raise exception 'Administrator access required'; end if;
  if p_decision not in ('approve','reject') then raise exception 'Decision must be approve or reject'; end if;
  select * into v_sub from public.seller_product_submissions where id=p_submission_id for update;
  if not found then raise exception 'Submission not found'; end if;
  if v_sub.status<>'pending' then raise exception 'Only pending submissions can be reviewed'; end if;
  if p_decision='reject' then
    if trim(coalesce(p_rejection_reason,''))='' then raise exception 'Rejection reason is required'; end if;
    if v_sub.approved_product_id is not null then update public.products set is_active=false,updated_at=now() where id=v_sub.approved_product_id; end if;
    update public.seller_product_submissions set status='rejected',rejection_reason=trim(p_rejection_reason),reviewed_at=now(),reviewed_by=v_uid,updated_at=now() where id=p_submission_id returning * into v_sub;
    return v_sub;
  end if;
  v_variants:=coalesce(v_sub.submission_payload->'variants','[]'::jsonb);
  v_has_variants:=jsonb_typeof(v_variants)='array' and jsonb_array_length(v_variants)>0;
  if v_sub.approved_product_id is not null then
    update public.products set name=v_sub.name,category=v_sub.category,price=v_sub.price,image_url=v_sub.image_url,description=v_sub.description,is_active=true,gst_rate=v_sub.gst_rate,bulk_enabled=v_sub.bulk_enabled,bulk_min_qty=v_sub.bulk_min_qty,has_variants=v_has_variants,source_seller_id=v_sub.seller_id,seller_submission_id=v_sub.id,updated_at=now() where id=v_sub.approved_product_id returning id into v_product_id;
    delete from public.inventory_levels where variant_id in (select id from public.product_variants where product_id=v_product_id);
    delete from public.product_variants where product_id=v_product_id;
    delete from public.product_bulk_tiers where product_id=v_product_id;
  else
    insert into public.products(name,category,cost,price,rating,reviews,image_url,badge,description,is_active,gst_rate,bulk_enabled,bulk_min_qty,has_variants,source_seller_id,seller_submission_id,updated_at)
    values(v_sub.name,v_sub.category,0,v_sub.price,0,0,v_sub.image_url,null,v_sub.description,true,v_sub.gst_rate,v_sub.bulk_enabled,v_sub.bulk_min_qty,v_has_variants,v_sub.seller_id,v_sub.id,now()) returning id into v_product_id;
  end if;
  if v_sub.bulk_enabled and v_sub.bulk_min_qty is not null and v_sub.bulk_price is not null then
    insert into public.product_bulk_tiers(product_id,min_qty,unit_price,updated_at) values(v_product_id,v_sub.bulk_min_qty,v_sub.bulk_price,now());
  end if;
  if v_has_variants then
    for v_variant in select value from jsonb_array_elements(v_variants) loop
      if trim(coalesce(v_variant->>'sku',''))='' then raise exception 'Every variant requires a SKU'; end if;
      v_variant_stock:=greatest(0,coalesce((v_variant->>'stock')::integer,0));
      insert into public.product_variants(product_id,sku,title,size,color,price_override,image_url,is_active,updated_at)
      values(v_product_id,upper(trim(v_variant->>'sku')),nullif(trim(coalesce(v_variant->>'title','')),''),nullif(trim(coalesce(v_variant->>'size','')),''),nullif(trim(coalesce(v_variant->>'color','')),''),case when nullif(v_variant->>'priceOverride','') is null then null else (v_variant->>'priceOverride')::numeric end,nullif(trim(coalesce(v_variant->>'image','')),''),true,now()) returning id into v_variant_id;
      insert into public.inventory_levels(variant_id,on_hand,reserved,reorder_level,updated_at) values(v_variant_id,v_variant_stock,0,greatest(0,coalesce((v_sub.submission_payload->>'lowStockThreshold')::integer,0)),now());
    end loop;
  end if;
  update public.seller_product_submissions set status='approved',rejection_reason=null,approved_product_id=v_product_id,reviewed_at=now(),reviewed_by=v_uid,updated_at=now() where id=p_submission_id returning * into v_sub;
  return v_sub;
end;$$;
-- END RECOVERED 20260918195427

-- BEGIN RECOVERED 20260918195638_seller_approval_activation_order
create or replace function public.admin_review_seller_product(p_submission_id bigint,p_decision text,p_rejection_reason text default null)
returns public.seller_product_submissions
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_uid uuid; v_sub public.seller_product_submissions; v_product_id bigint; v_variants jsonb; v_variant jsonb; v_variant_id bigint; v_has_custom_variants boolean; v_variant_stock integer;
begin
  v_uid:=auth.uid(); if v_uid is null then raise exception 'Authentication required'; end if;
  if not exists(select 1 from public.profiles p where p.id=v_uid and p.is_admin=true) then raise exception 'Administrator access required'; end if;
  if p_decision not in ('approve','reject') then raise exception 'Decision must be approve or reject'; end if;
  select * into v_sub from public.seller_product_submissions where id=p_submission_id for update;
  if not found then raise exception 'Submission not found'; end if;
  if v_sub.status<>'pending' then raise exception 'Only pending submissions can be reviewed'; end if;
  if p_decision='reject' then
    if trim(coalesce(p_rejection_reason,''))='' then raise exception 'Rejection reason is required'; end if;
    if v_sub.approved_product_id is not null then update public.products set is_active=false,updated_at=now() where id=v_sub.approved_product_id; end if;
    update public.seller_product_submissions set status='rejected',rejection_reason=trim(p_rejection_reason),reviewed_at=now(),reviewed_by=v_uid,updated_at=now() where id=p_submission_id returning * into v_sub;
    return v_sub;
  end if;

  v_variants:=coalesce(v_sub.submission_payload->'variants','[]'::jsonb);
  v_has_custom_variants:=jsonb_typeof(v_variants)='array' and jsonb_array_length(v_variants)>0;

  if v_sub.approved_product_id is not null then
    v_product_id:=v_sub.approved_product_id;
    update public.products set is_active=false,name=v_sub.name,category=v_sub.category,price=v_sub.price,image_url=v_sub.image_url,description=v_sub.description,gst_rate=v_sub.gst_rate,bulk_enabled=v_sub.bulk_enabled,bulk_min_qty=v_sub.bulk_min_qty,has_variants=true,source_seller_id=v_sub.seller_id,seller_submission_id=v_sub.id,updated_at=now() where id=v_product_id;
    delete from public.inventory_levels where variant_id in (select id from public.product_variants where product_id=v_product_id);
    delete from public.product_variants where product_id=v_product_id;
    delete from public.product_bulk_tiers where product_id=v_product_id;
  else
    insert into public.products(name,category,cost,price,rating,reviews,image_url,badge,description,is_active,gst_rate,bulk_enabled,bulk_min_qty,has_variants,source_seller_id,seller_submission_id,updated_at)
    values(v_sub.name,v_sub.category,0,v_sub.price,0,0,v_sub.image_url,null,v_sub.description,false,v_sub.gst_rate,v_sub.bulk_enabled,v_sub.bulk_min_qty,true,v_sub.seller_id,v_sub.id,now()) returning id into v_product_id;
  end if;

  if v_sub.bulk_enabled and v_sub.bulk_min_qty is not null and v_sub.bulk_price is not null then
    insert into public.product_bulk_tiers(product_id,min_qty,unit_price,updated_at) values(v_product_id,v_sub.bulk_min_qty,v_sub.bulk_price,now());
  end if;

  if v_has_custom_variants then
    for v_variant in select value from jsonb_array_elements(v_variants) loop
      if trim(coalesce(v_variant->>'sku',''))='' then raise exception 'Every variant requires a SKU'; end if;
      v_variant_stock:=greatest(0,coalesce((v_variant->>'stock')::integer,0));
      insert into public.product_variants(product_id,sku,title,size,color,price_override,image_url,is_active,updated_at)
      values(v_product_id,upper(trim(v_variant->>'sku')),nullif(trim(coalesce(v_variant->>'title','')),''),nullif(trim(coalesce(v_variant->>'size','')),''),nullif(trim(coalesce(v_variant->>'color','')),''),case when nullif(v_variant->>'priceOverride','') is null then null else (v_variant->>'priceOverride')::numeric end,nullif(trim(coalesce(v_variant->>'image','')),''),true,now()) returning id into v_variant_id;
      insert into public.inventory_levels(variant_id,on_hand,reserved,reorder_level,updated_at) values(v_variant_id,v_variant_stock,0,greatest(0,coalesce((v_sub.submission_payload->>'lowStockThreshold')::integer,0)),now());
    end loop;
  else
    insert into public.product_variants(product_id,sku,title,size,color,price_override,image_url,is_active,updated_at)
    values(v_product_id,upper(trim(v_sub.sku)),'Default',null,null,null,v_sub.image_url,true,now()) returning id into v_variant_id;
    insert into public.inventory_levels(variant_id,on_hand,reserved,reorder_level,updated_at) values(v_variant_id,greatest(0,v_sub.stock),0,greatest(0,coalesce((v_sub.submission_payload->>'lowStockThreshold')::integer,0)),now());
  end if;

  if not exists(select 1 from public.product_variants v join public.inventory_levels i on i.variant_id=v.id where v.product_id=v_product_id and v.is_active=true and (i.on_hand-i.reserved)>0) then
    raise exception 'At least one active SKU must have available stock before approval';
  end if;

  update public.products set is_active=true,updated_at=now() where id=v_product_id;
  update public.seller_product_submissions set status='approved',rejection_reason=null,approved_product_id=v_product_id,reviewed_at=now(),reviewed_by=v_uid,updated_at=now() where id=p_submission_id returning * into v_sub;
  return v_sub;
end;$$;
-- END RECOVERED 20260918195638

-- BEGIN RECOVERED 20260918195719_seller_tables_privilege_hardening
revoke all privileges on table public.seller_profiles from authenticated;
revoke all privileges on table public.seller_product_submissions from authenticated;
grant select on table public.seller_profiles to authenticated;
grant select on table public.seller_product_submissions to authenticated;
revoke all privileges on sequence public.seller_product_submissions_id_seq from authenticated;
-- END RECOVERED 20260918195719

-- BEGIN RECOVERED 20260918195734_seller_submission_validation_hardening
create or replace function public.submit_seller_product(
 p_submission_id bigint,
 p_sku text,p_name text,p_category text,p_price numeric,p_mrp numeric,p_gst_rate numeric,
 p_description text,p_image_url text,p_brand text,p_country_origin text,p_hsn text,p_stock integer,
 p_bulk_enabled boolean,p_bulk_min_qty integer,p_bulk_price numeric,p_submission_payload jsonb default '{}'::jsonb)
returns public.seller_product_submissions
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare v_uid uuid; v_row public.seller_product_submissions; v_profile public.seller_profiles; v_variants jsonb;
begin
  v_uid:=auth.uid(); if v_uid is null then raise exception 'Authentication required'; end if;
  select * into v_profile from public.seller_profiles where user_id=v_uid and status='active';
  if not found then raise exception 'Active seller profile required'; end if;
  if trim(coalesce(p_sku,''))='' or char_length(trim(p_sku))>60 then raise exception 'SKU is required and must be 60 characters or fewer'; end if;
  if trim(coalesce(p_name,''))='' or char_length(trim(p_name))>160 then raise exception 'Product name is required and must be 160 characters or fewer'; end if;
  if char_length(coalesce(p_category,''))>100 then raise exception 'Category is too long'; end if;
  if char_length(coalesce(p_description,''))>5000 then raise exception 'Description is too long'; end if;
  if char_length(coalesce(p_brand,''))>80 or trim(coalesce(p_brand,''))='' then raise exception 'Brand is required and must be 80 characters or fewer'; end if;
  if char_length(coalesce(p_country_origin,''))>80 or trim(coalesce(p_country_origin,''))='' then raise exception 'Country of origin is required'; end if;
  if p_hsn is not null and trim(p_hsn)<>'' and trim(p_hsn) !~ '^[0-9]{4,8}$' then raise exception 'HSN must be 4 to 8 digits'; end if;
  if p_image_url is not null and trim(p_image_url)<>'' and trim(p_image_url) !~ '^https://[^[:space:]]+$' then raise exception 'Product image must use a public HTTPS URL'; end if;
  if p_price is null or p_price<=0 or p_price>100000000 then raise exception 'Price must be greater than zero and within allowed limits'; end if;
  if p_mrp is not null and (p_mrp<p_price or p_mrp>100000000) then raise exception 'MRP cannot be lower than price or exceed allowed limits'; end if;
  if coalesce(p_gst_rate,18)<0 or coalesce(p_gst_rate,18)>100 then raise exception 'Invalid GST rate'; end if;
  if coalesce(p_stock,0)<0 or coalesce(p_stock,0)>1000000 then raise exception 'Stock is outside allowed limits'; end if;
  if octet_length(coalesce(p_submission_payload,'{}'::jsonb)::text)>65536 then raise exception 'Product metadata is too large'; end if;
  v_variants:=coalesce(p_submission_payload->'variants','[]'::jsonb);
  if jsonb_typeof(v_variants)<>'array' then raise exception 'Variants payload must be an array'; end if;
  if jsonb_array_length(v_variants)>50 then raise exception 'Maximum 50 variants are allowed'; end if;
  if coalesce(p_bulk_enabled,false) and (coalesce(p_bulk_min_qty,0)<2 or p_bulk_min_qty>100000 or p_bulk_price is null or p_bulk_price<=0 or p_bulk_price>p_price) then raise exception 'Invalid bulk pricing'; end if;
  if p_submission_id is null then
    insert into public.seller_product_submissions(seller_id,sku,name,category,price,mrp,gst_rate,description,image_url,brand,country_origin,hsn,stock,bulk_enabled,bulk_min_qty,bulk_price,submission_payload,status,rejection_reason,approved_product_id,reviewed_at,reviewed_by,submitted_at,updated_at)
    values(v_uid,upper(trim(p_sku)),trim(p_name),nullif(trim(coalesce(p_category,'')),''),p_price,p_mrp,coalesce(p_gst_rate,18),nullif(trim(coalesce(p_description,'')),''),nullif(trim(coalesce(p_image_url,'')),''),trim(p_brand),trim(p_country_origin),nullif(trim(coalesce(p_hsn,'')),''),coalesce(p_stock,0),coalesce(p_bulk_enabled,false),case when coalesce(p_bulk_enabled,false) then p_bulk_min_qty else null end,case when coalesce(p_bulk_enabled,false) then p_bulk_price else null end,coalesce(p_submission_payload,'{}'::jsonb),'pending',null,null,null,null,now(),now()) returning * into v_row;
  else
    update public.seller_product_submissions set sku=upper(trim(p_sku)),name=trim(p_name),category=nullif(trim(coalesce(p_category,'')),''),price=p_price,mrp=p_mrp,gst_rate=coalesce(p_gst_rate,18),description=nullif(trim(coalesce(p_description,'')),''),image_url=nullif(trim(coalesce(p_image_url,'')),''),brand=trim(p_brand),country_origin=trim(p_country_origin),hsn=nullif(trim(coalesce(p_hsn,'')),''),stock=coalesce(p_stock,0),bulk_enabled=coalesce(p_bulk_enabled,false),bulk_min_qty=case when coalesce(p_bulk_enabled,false) then p_bulk_min_qty else null end,bulk_price=case when coalesce(p_bulk_enabled,false) then p_bulk_price else null end,submission_payload=coalesce(p_submission_payload,'{}'::jsonb),status='pending',rejection_reason=null,reviewed_at=null,reviewed_by=null,submitted_at=now(),updated_at=now()
    where id=p_submission_id and seller_id=v_uid returning * into v_row;
    if not found then raise exception 'Submission not found'; end if;
    if v_row.approved_product_id is not null then update public.products set is_active=false,updated_at=now() where id=v_row.approved_product_id; end if;
  end if;
  return v_row;
end;$$;
-- END RECOVERED 20260918195734

-- BEGIN RECOVERED 20260918195815_seller_workflow_foreign_key_indexes
create index if not exists products_source_seller_id_idx on public.products(source_seller_id) where source_seller_id is not null;
create index if not exists seller_product_submissions_approved_product_idx on public.seller_product_submissions(approved_product_id) where approved_product_id is not null;
create index if not exists seller_product_submissions_reviewed_by_idx on public.seller_product_submissions(reviewed_by) where reviewed_by is not null;
-- END RECOVERED 20260918195815

-- BEGIN RECOVERED 20260918195952_remove_public_seller_identity_from_products
create or replace function public.admin_review_seller_product(p_submission_id bigint,p_decision text,p_rejection_reason text default null)
returns public.seller_product_submissions
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_uid uuid; v_sub public.seller_product_submissions; v_product_id bigint; v_variants jsonb; v_variant jsonb; v_variant_id bigint; v_has_custom_variants boolean; v_variant_stock integer;
begin
  v_uid:=auth.uid(); if v_uid is null then raise exception 'Authentication required'; end if;
  if not exists(select 1 from public.profiles p where p.id=v_uid and p.is_admin=true) then raise exception 'Administrator access required'; end if;
  if p_decision not in ('approve','reject') then raise exception 'Decision must be approve or reject'; end if;
  select * into v_sub from public.seller_product_submissions where id=p_submission_id for update;
  if not found then raise exception 'Submission not found'; end if;
  if v_sub.status<>'pending' then raise exception 'Only pending submissions can be reviewed'; end if;
  if p_decision='reject' then
    if trim(coalesce(p_rejection_reason,''))='' then raise exception 'Rejection reason is required'; end if;
    if v_sub.approved_product_id is not null then update public.products set is_active=false,updated_at=now() where id=v_sub.approved_product_id; end if;
    update public.seller_product_submissions set status='rejected',rejection_reason=trim(p_rejection_reason),reviewed_at=now(),reviewed_by=v_uid,updated_at=now() where id=p_submission_id returning * into v_sub;
    return v_sub;
  end if;
  v_variants:=coalesce(v_sub.submission_payload->'variants','[]'::jsonb);
  v_has_custom_variants:=jsonb_typeof(v_variants)='array' and jsonb_array_length(v_variants)>0;
  if v_sub.approved_product_id is not null then
    v_product_id:=v_sub.approved_product_id;
    update public.products set is_active=false,name=v_sub.name,category=v_sub.category,price=v_sub.price,image_url=v_sub.image_url,description=v_sub.description,gst_rate=v_sub.gst_rate,bulk_enabled=v_sub.bulk_enabled,bulk_min_qty=v_sub.bulk_min_qty,has_variants=true,updated_at=now() where id=v_product_id;
    delete from public.inventory_levels where variant_id in (select id from public.product_variants where product_id=v_product_id);
    delete from public.product_variants where product_id=v_product_id;
    delete from public.product_bulk_tiers where product_id=v_product_id;
  else
    insert into public.products(name,category,cost,price,rating,reviews,image_url,badge,description,is_active,gst_rate,bulk_enabled,bulk_min_qty,has_variants,updated_at)
    values(v_sub.name,v_sub.category,0,v_sub.price,0,0,v_sub.image_url,null,v_sub.description,false,v_sub.gst_rate,v_sub.bulk_enabled,v_sub.bulk_min_qty,true,now()) returning id into v_product_id;
  end if;
  if v_sub.bulk_enabled and v_sub.bulk_min_qty is not null and v_sub.bulk_price is not null then
    insert into public.product_bulk_tiers(product_id,min_qty,unit_price,updated_at) values(v_product_id,v_sub.bulk_min_qty,v_sub.bulk_price,now());
  end if;
  if v_has_custom_variants then
    for v_variant in select value from jsonb_array_elements(v_variants) loop
      if trim(coalesce(v_variant->>'sku',''))='' then raise exception 'Every variant requires a SKU'; end if;
      v_variant_stock:=greatest(0,coalesce((v_variant->>'stock')::integer,0));
      insert into public.product_variants(product_id,sku,title,size,color,price_override,image_url,is_active,updated_at)
      values(v_product_id,upper(trim(v_variant->>'sku')),nullif(trim(coalesce(v_variant->>'title','')),''),nullif(trim(coalesce(v_variant->>'size','')),''),nullif(trim(coalesce(v_variant->>'color','')),''),case when nullif(v_variant->>'priceOverride','') is null then null else (v_variant->>'priceOverride')::numeric end,nullif(trim(coalesce(v_variant->>'image','')),''),true,now()) returning id into v_variant_id;
      insert into public.inventory_levels(variant_id,on_hand,reserved,reorder_level,updated_at) values(v_variant_id,v_variant_stock,0,greatest(0,coalesce((v_sub.submission_payload->>'lowStockThreshold')::integer,0)),now());
    end loop;
  else
    insert into public.product_variants(product_id,sku,title,size,color,price_override,image_url,is_active,updated_at)
    values(v_product_id,upper(trim(v_sub.sku)),'Default',null,null,null,v_sub.image_url,true,now()) returning id into v_variant_id;
    insert into public.inventory_levels(variant_id,on_hand,reserved,reorder_level,updated_at) values(v_variant_id,greatest(0,v_sub.stock),0,greatest(0,coalesce((v_sub.submission_payload->>'lowStockThreshold')::integer,0)),now());
  end if;
  if not exists(select 1 from public.product_variants v join public.inventory_levels i on i.variant_id=v.id where v.product_id=v_product_id and v.is_active=true and (i.on_hand-i.reserved)>0) then raise exception 'At least one active SKU must have available stock before approval'; end if;
  update public.products set is_active=true,updated_at=now() where id=v_product_id;
  update public.seller_product_submissions set status='approved',rejection_reason=null,approved_product_id=v_product_id,reviewed_at=now(),reviewed_by=v_uid,updated_at=now() where id=p_submission_id returning * into v_sub;
  return v_sub;
end;$$;

drop index if exists public.products_source_seller_id_idx;
drop index if exists public.products_seller_submission_uidx;
alter table public.products drop column if exists source_seller_id;
alter table public.products drop column if exists seller_submission_id;
-- END RECOVERED 20260918195952
