create table if not exists public.payment_recovery_notifications (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  user_id uuid not null,
  payment_id text not null,
  event_type text not null default 'payment_failed',
  recipient_email text not null,
  provider text not null default 'zoho_mail',
  status text not null default 'pending',
  provider_message_id text,
  attempt_count integer not null default 0,
  last_error text,
  created_at timestamptz not null default now(),
  last_attempt_at timestamptz,
  sent_at timestamptz,
  constraint payment_recovery_notifications_event_check
    check (event_type in ('payment_failed')),
  constraint payment_recovery_notifications_provider_check
    check (provider in ('zoho_mail')),
  constraint payment_recovery_notifications_status_check
    check (status in ('pending','sent','failed')),
  constraint payment_recovery_notifications_attempt_count_check
    check (attempt_count >= 0),
  constraint payment_recovery_notifications_identity_key
    unique (event_type, payment_id)
);

create index if not exists payment_recovery_notifications_status_idx
  on public.payment_recovery_notifications(status, created_at desc);

alter table public.payment_recovery_notifications enable row level security;

revoke all on table public.payment_recovery_notifications from public, anon, authenticated;
grant select, insert, update on table public.payment_recovery_notifications to service_role;
grant usage, select on sequence public.payment_recovery_notifications_id_seq to service_role;
