create table if not exists public.order_shipments (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  provider text not null default 'shiprocket' check (provider in ('shiprocket','delhivery')),
  direction text not null default 'forward' check (direction in ('forward','return')),
  provider_order_id text,
  provider_shipment_id text,
  awb_code text,
  courier_id text,
  courier_name text,
  status text not null default 'pending',
  provider_status text,
  tracking_url text,
  label_url text,
  package_weight_kg numeric(10,3) check (package_weight_kg is null or package_weight_kg > 0),
  package_length_cm numeric(10,2) check (package_length_cm is null or package_length_cm > 0),
  package_breadth_cm numeric(10,2) check (package_breadth_cm is null or package_breadth_cm > 0),
  package_height_cm numeric(10,2) check (package_height_cm is null or package_height_cm > 0),
  pickup_requested_at timestamptz,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (order_id, direction)
);

create index if not exists order_shipments_awb_idx
  on public.order_shipments (awb_code)
  where awb_code is not null;

create index if not exists order_shipments_provider_shipment_idx
  on public.order_shipments (provider_shipment_id)
  where provider_shipment_id is not null;

alter table public.order_shipments enable row level security;
revoke all on table public.order_shipments from anon, authenticated;
grant select, insert, update, delete on table public.order_shipments to service_role;
grant usage, select on sequence public.order_shipments_id_seq to service_role;
