create table if not exists public.seller_payout_webhook_events (
  id bigint generated by default as identity primary key,
  event_fingerprint text not null unique,
  event_type text not null,
  settlement_id bigint references public.seller_settlements(id) on delete set null,
  provider_payout_ref text,
  provider_status text,
  provider_utr text,
  status_details jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now()
);

alter table public.seller_payout_webhook_events enable row level security;
revoke all on public.seller_payout_webhook_events from public, anon, authenticated;
grant select, insert on public.seller_payout_webhook_events to service_role;

create or replace function public.service_record_seller_payout_webhook(
  p_event_fingerprint text,
  p_event_type text,
  p_settlement_id bigint,
  p_reference_id text,
  p_provider_payout_ref text,
  p_provider_status text,
  p_provider_utr text,
  p_failure_reason text,
  p_provider_details jsonb
) returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,public
as $$
declare
  v_set public.seller_settlements%rowtype;
  v_status text:=lower(trim(coalesce(p_provider_status,'')));
  v_final text;
  v_inserted bigint;
begin
  if nullif(trim(coalesce(p_event_fingerprint,'')),'') is null then raise exception 'Webhook fingerprint required'; end if;
  if nullif(trim(coalesce(p_event_type,'')),'') is null then raise exception 'Webhook event type required'; end if;
  if p_settlement_id is null or p_settlement_id < 1 then raise exception 'Invalid settlement id'; end if;
  if coalesce(p_reference_id,'') <> 'ff-settlement-'||p_settlement_id::text then raise exception 'Payout reference mismatch'; end if;

  select * into v_set from public.seller_settlements where id=p_settlement_id for update;
  if v_set.id is null then raise exception 'Settlement not found'; end if;
  if v_set.payout_idempotency_key is null then raise exception 'Settlement was not prepared for provider payout'; end if;
  if v_set.provider_payout_ref is not null and nullif(trim(coalesce(p_provider_payout_ref,'')),'') is not null and v_set.provider_payout_ref <> trim(p_provider_payout_ref) then
    raise exception 'Provider payout reference mismatch';
  end if;

  insert into public.seller_payout_webhook_events(event_fingerprint,event_type,settlement_id,provider_payout_ref,provider_status,provider_utr,status_details)
  values(trim(p_event_fingerprint),trim(p_event_type),p_settlement_id,nullif(trim(coalesce(p_provider_payout_ref,'')),''),nullif(v_status,''),nullif(trim(coalesce(p_provider_utr,'')),''),coalesce(p_provider_details,'{}'::jsonb))
  on conflict(event_fingerprint) do nothing
  returning id into v_inserted;

  if v_inserted is null then
    return jsonb_build_object('ok',true,'duplicate',true,'settlement_id',p_settlement_id,'status',v_set.status,'provider_status',v_set.provider_status);
  end if;

  v_final:=case
    when v_status in ('processed','paid') then 'paid'
    when v_status in ('rejected','failed','cancelled','reversed') then 'failed'
    else 'processing'
  end;

  update public.seller_settlements set
    provider_payout_ref=coalesce(nullif(trim(coalesce(p_provider_payout_ref,'')),''),provider_payout_ref),
    provider_status=nullif(v_status,''),
    provider_utr=coalesce(nullif(trim(coalesce(p_provider_utr,'')),''),provider_utr),
    provider_status_details=coalesce(p_provider_details,'{}'::jsonb),
    provider_synced_at=now(),
    failure_reason=case when v_final='failed' then nullif(trim(coalesce(p_failure_reason,'')),'') else null end,
    status=v_final,
    paid_at=case when v_final='paid' then coalesce(paid_at,now()) when v_final='failed' then null else paid_at end,
    updated_at=now()
  where id=v_set.id;

  return (select jsonb_build_object(
    'ok',true,'duplicate',false,'settlement_id',s.id,'status',s.status,'provider_status',s.provider_status,
    'provider_utr',s.provider_utr,'failure_reason',s.failure_reason,'paid_at',s.paid_at
  ) from public.seller_settlements s where s.id=v_set.id);
end $$;

revoke all on function public.service_record_seller_payout_webhook(text,text,bigint,text,text,text,text,text,jsonb) from public, anon, authenticated;
grant execute on function public.service_record_seller_payout_webhook(text,text,bigint,text,text,text,text,text,jsonb) to service_role;
