'use strict';
const $=id=>document.getElementById(id);
const client=window.supabaseClient;
const UI_SESSION_KEY='ff_seller_session_v1';
function setMessage(message,type=''){const box=$('authMessage');box.textContent=message;box.className='auth-message '+type}
function setMode(mode){document.querySelectorAll('[data-auth-mode]').forEach(b=>b.classList.toggle('active',b.dataset.authMode===mode));$('loginForm').hidden=mode!=='login';$('registerForm').hidden=mode!=='register';$('authTitle').textContent=mode==='login'?'Sign in to Seller Center':'Create your seller account';$('authSubtitle').textContent=mode==='login'?'Use your registered seller email and password.':'Create a seller account for catalog review and approval.';setMessage('')}
function cleanPhone(value){return String(value||'').replace(/\D/g,'').slice(-10)}
async function sellerProfile(user){const{data,error}=await client.from('seller_profiles').select('user_id,store_name,seller_type,phone,status').eq('user_id',user.id).maybeSingle();if(error)throw error;return data}
async function ensureSellerProfile(user){let profile=await sellerProfile(user);if(profile)return profile;const meta=user.user_metadata||{};if(!meta.seller_registration_intent)throw new Error('This account is not registered as a seller.');const{data,error}=await client.rpc('register_seller_profile',{p_store_name:meta.store_name||'Seller Store',p_seller_type:meta.seller_type||'individual',p_phone:meta.phone||null});if(error)throw error;return data}
function setUiSession(user,profile){const meta=user.user_metadata||{},name=meta.full_name||user.email?.split('@')[0]||'Seller';localStorage.setItem(UI_SESSION_KEY,JSON.stringify({sellerId:user.id,email:user.email,storeName:profile.store_name,name,createdAt:new Date().toISOString(),authProvider:'supabase'}));sessionStorage.removeItem(UI_SESSION_KEY)}
async function finishLogin(user){const profile=await ensureSellerProfile(user);if(profile?.status!=='active')throw new Error('Seller account is not active.');setUiSession(user,profile);location.href='index.html'}
(async()=>{const{data:{session}}=await client.auth.getSession();if(session?.user){try{await finishLogin(session.user)}catch{await client.auth.signOut();localStorage.removeItem(UI_SESSION_KEY)}}})();
document.querySelectorAll('[data-auth-mode]').forEach(btn=>btn.addEventListener('click',()=>setMode(btn.dataset.authMode)));
$('loginForm').addEventListener('submit',async event=>{event.preventDefault();const btn=$('loginSubmit');btn.disabled=true;setMessage('Signing in…');try{const{data,error}=await client.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(error)throw error;await finishLogin(data.user)}catch(error){await client.auth.signOut().catch(()=>{});localStorage.removeItem(UI_SESSION_KEY);setMessage(error.message||'Seller sign in failed.','err')}finally{btn.disabled=false}});
$('registerForm').addEventListener('submit',async event=>{event.preventDefault();const btn=$('registerSubmit'),mobile=cleanPhone($('mobile').value),storeName=$('storeName').value.trim();if(mobile.length!==10){setMessage('Enter a valid 10-digit mobile number.','err');return}if(storeName.length<2){setMessage('Enter a valid store name.','err');return}btn.disabled=true;setMessage('Creating seller account…');try{const first=$('firstName').value.trim(),last=$('lastName').value.trim(),sellerType=$('sellerType').value;const{data,error}=await client.auth.signUp({email:$('registerEmail').value.trim().toLowerCase(),password:$('registerPassword').value,options:{data:{full_name:[first,last].filter(Boolean).join(' '),store_name:storeName,seller_type:sellerType,phone:mobile,seller_registration_intent:true},emailRedirectTo:location.origin+'/login'}});if(error)throw error;if(data.session?.user){const{data:profile,error:profileError}=await client.rpc('register_seller_profile',{p_store_name:storeName,p_seller_type:sellerType,p_phone:mobile});if(profileError)throw profileError;setUiSession(data.session.user,profile);setMessage('Seller account created. Opening dashboard…','ok');location.href='index.html'}else{setMessage('Seller account created. Verify your email, then sign in.','ok');setMode('login')}}catch(error){setMessage(error.message||'Seller registration failed.','err')}finally{btn.disabled=false}});
