(function(){
'use strict';
const supa=window.supabaseClient;if(!supa)return;const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const fmt=d=>d?new Date(d).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—';let profile=null,current=null,channel=null;
function addStyle(){if($('sellerSupportStyle'))return;const s=document.createElement('style');s.id='sellerSupportStyle';s.textContent='.seller-support-grid{display:grid;grid-template-columns:320px 1fr;gap:16px}.seller-support-list{display:grid;gap:8px}.seller-ticket{border:1px solid #e2e8f0;background:#fff;border-radius:10px;padding:10px;text-align:left;cursor:pointer}.seller-ticket b,.seller-ticket small{display:block}.seller-ticket small{color:#7b8494;margin-top:3px}.seller-support-chat{border:1px solid #e2e8f0;border-radius:12px;background:#fff;min-height:360px;padding:14px}.seller-support-msg{padding:9px 11px;border-radius:9px;margin:7px 0;max-width:84%;white-space:pre-wrap}.seller-support-msg.mine{margin-left:auto;background:#eef4ff}.seller-support-msg.other{background:#f4f5f7}.seller-support-msg small{display:block;font-size:9px;color:#7b8494;margin-bottom:3px}.seller-support-compose{display:flex;gap:8px;margin-top:12px}.seller-support-compose input{flex:1}.seller-admin-contact{margin-bottom:16px}@media(max-width:900px){.seller-support-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
async function session(){const{data:{session},error}=await supa.auth.getSession();if(error||!session?.user)return null;return session.user}
function install(){if($('view-support-live'))return;addStyle();const nav=document.querySelector('.nav');const divider=nav?.querySelector('.nav-divider');const btn=document.createElement('button');btn.className='nav-item';btn.dataset.view='support-live';btn.innerHTML='<span>?</span>Support';if(divider)nav.insertBefore(btn,divider);else nav?.appendChild(btn);const main=document.querySelector('.main');const sec=document.createElement('section');sec.className='content view';sec.id='view-support-live';sec.innerHTML='<div class="page-head"><div><p class="eyebrow">SELLER SUPPORT</p><h1>Support</h1><p>Reply to customer Seller Support tickets and contact Fashion_Fussion Admin for seller-account issues.</p></div></div><section class="panel seller-admin-contact" id="sellerAdminContact"><div class="panel-head"><div><h2>Contact Admin</h2><p>Admin WhatsApp is read-only and tied to your verified Seller ID.</p></div></div><div id="sellerAdminContactBody">Loading…</div></section><div class="seller-support-grid"><section class="panel"><div class="panel-head"><div><h2>Customer tickets</h2><p>Only tickets linked to your seller products are visible.</p></div></div><div id="sellerTicketList" class="seller-support-list">Loading…</div></section><section class="seller-support-chat" id="sellerTicketChat"><p>Select a ticket to view the conversation.</p></section></div>';main?.appendChild(sec);btn.addEventListener('click',()=>{document.querySelectorAll('.nav-item[data-view]').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.content.view').forEach(x=>x.classList.toggle('active',x===sec));loadAll()})}
async function loadAll(){const u=await session();if(!u){location.href='login.html';return}await Promise.all([loadContact(),loadTickets()])}
async function loadContact(){const box=$('sellerAdminContactBody');if(!box)return;const{data,error}=await supa.rpc('get_seller_support_contact');if(error){box.textContent=error.message;return}profile=Array.isArray(data)?data[0]:data;if(!profile){box.textContent='Seller support identity unavailable.';return}const id=$('sellerDisplayId');if(id)id.textContent='Seller ID: '+profile.seller_code;box.innerHTML='<div class="notice info"><div><strong>'+esc(profile.seller_code)+' · '+esc(profile.store_name)+'</strong><p>Admin WhatsApp: +91 88529 76856</p><button class="primary" id="sellerWhatsAppAdmin" type="button">Contact Admin on WhatsApp</button></div></div>';$('sellerWhatsAppAdmin').onclick=openWhatsApp}
function openWhatsApp(){if(!profile)return;const text=['Fashion_Fussion Seller Support','Seller ID: '+profile.seller_code,'Store: '+profile.store_name,'Seller Type: '+profile.seller_type,'Registered Phone: '+(profile.registered_phone||'—'),'Registered Email: '+(profile.registered_email||'—'),'Seller Status: '+profile.seller_status,'','Issue: Please describe your issue here'].join('\n');const number=String(profile.admin_whatsapp_e164||'+918852976856').replace(/\D/g,'');window.open('https://wa.me/'+number+'?text='+encodeURIComponent(text),'_blank','noopener,noreferrer')}
async function loadTickets(){const box=$('sellerTicketList');if(!box)return;const u=await session();const{data,error}=await supa.from('support_tickets').select('id,ticket_code,subject,status,order_id,product_id,reopen_count,updated_at').eq('channel','seller_support').eq('seller_id',u.id).order('updated_at',{ascending:false}).limit(100);if(error){box.textContent=error.message;return}box.innerHTML=(data||[]).map(t=>'<button class="seller-ticket" data-ticket="'+t.id+'"><b>'+esc(t.ticket_code)+'</b><span>'+esc(t.subject)+'</span><small>'+esc(t.status)+' · Updated '+esc(fmt(t.updated_at))+'</small></button>').join('')||'<p>No customer Seller Support tickets.</p>';box.querySelectorAll('[data-ticket]').forEach(b=>b.onclick=()=>openTicket(Number(b.dataset.ticket)))}
async function openTicket(id){const chat=$('sellerTicketChat');const{data:t,error}=await supa.from('support_tickets').select('*').eq('id',id).maybeSingle();if(error||!t){chat.textContent=error?.message||'Ticket not found';return}current=t;const{data:m,error:me}=await supa.from('support_ticket_messages').select('id,sender_role,message,created_at').eq('ticket_id',id).order('created_at');if(me){chat.textContent=me.message;return}chat.innerHTML='<div><b>'+esc(t.ticket_code)+'</b><p>'+esc(t.subject)+' · '+esc(t.status)+'</p></div><div id="sellerSupportMessages">'+(m||[]).map(x=>'<div class="seller-support-msg '+(x.sender_role==='seller'?'mine':'other')+'"><small>'+esc(x.sender_role)+' · '+esc(fmt(x.created_at))+'</small>'+esc(x.message)+'</div>').join('')+'</div>'+(!['closed','resolved'].includes(t.status)?'<div class="seller-support-compose"><input id="sellerSupportReply" maxlength="5000" placeholder="Reply to customer"><button class="primary" id="sellerSupportSend">Send</button></div><button class="ghost" id="sellerSupportClose" type="button">Close as resolved</button>':'<p><b>Ticket closed.</b> Customer can reopen this same Ticket ID if the same issue returns.</p>');if($('sellerSupportSend'))$('sellerSupportSend').onclick=sendReply;if($('sellerSupportClose'))$('sellerSupportClose').onclick=closeTicket;subscribe(id)}
async function sendReply(){const msg=$('sellerSupportReply')?.value.trim();if(!current||!msg)return;const{error}=await supa.rpc('send_support_ticket_message',{p_ticket_id:current.id,p_message:msg});if(error){alert(error.message);return}await openTicket(current.id);await loadTickets()}
async function closeTicket(){const summary=prompt('Resolution summary:');if(!summary?.trim())return;const{error}=await supa.rpc('close_support_ticket',{p_ticket_id:current.id,p_resolution_summary:summary.trim()});if(error){alert(error.message);return}await openTicket(current.id);await loadTickets()}
function subscribe(id){if(channel)supa.removeChannel(channel);channel=supa.channel('seller-support-'+id).on('postgres_changes',{event:'*',schema:'public',table:'support_ticket_messages',filter:'ticket_id=eq.'+id},()=>openTicket(id)).on('postgres_changes',{event:'UPDATE',schema:'public',table:'support_tickets',filter:'id=eq.'+id},()=>openTicket(id)).subscribe()}
function init(){install();loadContact().catch(()=>{})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
